### ISSUE TITLE
mp4 video stream with different audio signal

### ISSUE THREAD

**Issue by chicco64** [ffplayout/ffplayout#113]
Hi !
I would like to know if it is possible to generate a video stream (example mp4 file sequence) but with an audio signal coming from another source.
Here is an example:

https://www.youtube.com/watch?v=K8kXcNqWN8g

You will be able to see "nocturnal" images accompanied by a separate lounge music source (simple mp3 playout).
Do you think it is possible?
Thank you so much !

**Comment by jb-alvarado** [comment]
I have some ideas in mind and need to move them around, but I can not guarantee that it will make it to version 4.0.0.

**Comment by jb-alvarado** [comment]
Maybe the playlist could support something like:

```JSON
{
    "in": 0,
    "out": 149,
    "duration": 149,
    "source": [
        "/path/image1.jpg",
        "/path/image2.jpg",
        "/path/image3.jpg",
    ]
    "audio": "/path/audio.mp3"
}
```

The `duration` needs to be the duration from the audio file.

To implement this in the frontend is difficult.

**Comment by Charles-Vaz** [comment]
Hello, I wanted some help, I would like my playlists to come with both all the audios of the video file, would it be possible? for he always takes the first. Is there any changes I can make.

**Comment by jb-alvarado** [comment]
Hello Charles,
does your question is related to this issue, where a separate audio file is needed? When not, please create a new issue.

**Comment by Charles-Vaz** [comment]
> Olá Charles, sua pergunta está relacionada a esse problema, onde é necessário um arquivo de áudio separado? Quando não, por favor, crie um novo problema.

sorry I opened a new one follow the link.     https://github.com/ffplayout/ffplayout/issues/158

**Comment by jb-alvarado** [comment]
This feature is now supported in v0.14.0. I mark it as experimental, because is not widely tested.
