### ISSUE TITLE
transmit dual movie audio.

### ISSUE THREAD

**Issue by Charles-Vaz** [ffplayout/ffplayout#158]
The playout is limiting only one audio, if my movie has two audios how can I transmit both in the same stream.
i need some help.

**Comment by Charles-Vaz** [comment]
That's not it..., I would like to play two audios in the same stream. for example when the movie is dubbed from english to portuguese, in this case my movie.mp4 has two audios, so the playout brings me only one in ffmpeg it is mapping the first but the second it discards. how can i solve this

**Comment by Charles-Vaz** [comment]
> Obrigado por criar um novo problema.
> 
> No momento, isso não é suportado, mas talvez não seja muito difícil de implementar. Para testar, você pode remover `-ac 2`de
> 
> https://github.com/ffplayout/ffplayout/blob/86d183ebfb61d04baa3096988683ea14fa7cf361/lib/src/utils/config.rs#L242
> 
> O problema que vejo com isso é: o que o playout deve fazer, quando nem todos os vídeos têm a mesma quantidade de linhas de áudio? Há um fallback necessário.

For example, my video has 2 audio lines, but the playout limits me in one, I can't use the other, if I can include two options, I can't modify the source, only the output_param, but that only changes what I have in the source . in this case I can't have two links in the source if I had this alternative, I can map it to the output of the output_param

**Comment by Charles-Vaz** [comment]
after installing the playout can i edit the config? because I didn't find it, I used ./installer to install on debian11 from what I saw it installs on .deb

**Comment by jb-alvarado** [comment]
Yes, you can do that by editing **/etc/ffplayout/ffplayout.yml**

**Comment by Charles-Vaz** [comment]
> Sim, você pode fazer isso editando **/etc/ffplayout/ffplayout.yml**


It runs in two estancias the ffmpeg right? the output I can change, but in this part {shortest=1[vout1] -map [vout1] -map 1:a -pix_fmt yuv420p -r 25 -c:v mpeg2video} where can I change it because that's where I'm limiting the audio, in this file that commented to me how can I change this?

**Comment by jb-alvarado** [comment]
Yes you are right. And you also get the right place from mapping (my comment about line 242 in config.rs was wrong).

At the moment it is not possible for users to change that part. The correct mapping is made in https://github.com/ffplayout/ffplayout/blob/master/lib/src/filter/mod.rs, it need a more deep investment to figure out, how this could work.

**Comment by jb-alvarado** [comment]
I don't know what you are writing, because I don't speak your language.

Anyway, a full integration of this feature is a bigger task, which at the moment I have no time for it. The filter logic has to be rewritten to apply the audio filters on every track. It would need a new config option `audio_track_count` for more generic use.

There is a workaround, which could work, but not in all situations. When you use the hls output mode with this parms:

```YAML
    output_param: >-
        -map "0:a:1"  # <---------
        -c:v libx264
        -crf 23
        -x264-params keyint=50:min-keyint=25:scenecut=-1
        -maxrate 1300k
        -bufsize 2600k
        -preset faster
        -tune zerolatency
        -profile:v Main
        -level 3.1
        -c:a aac
        -ar 44100
        -b:a 128k
        -flags +global_header
        -flags +cgop
        -f hls
        -hls_time 6
        -hls_list_size 600
        -hls_flags append_list+delete_segments+omit_endlist
        -hls_segment_filename /var/www/html/live/stream-%d.ts /var/www/html/live//stream.m3u8
```

**Comment by cooliobr** [comment]
> I don't know what you are writing, because I don't speak your language.
> 
> Anyway, a full integration of this feature is a bigger task, which at the moment I have no time for it. The filter logic has to be rewritten to apply the audio filters on every track. It would need a new config option `audio_track_count` for more generic use.
> 
> There is a workaround, which could work, but not in all situations. When you use the hls output mode with this parms:
> 
> ```yaml
>     output_param: >-
>         -map "0:a:1"  # <---------
>         -c:v libx264
>         -crf 23
>         -x264-params keyint=50:min-keyint=25:scenecut=-1
>         -maxrate 1300k
>         -bufsize 2600k
>         -preset faster
>         -tune zerolatency
>         -profile:v Main
>         -level 3.1
>         -c:a aac
>         -ar 44100
>         -b:a 128k
>         -flags +global_header
>         -flags +cgop
>         -f hls
>         -hls_time 6
>         -hls_list_size 600
>         -hls_flags append_list+delete_segments+omit_endlist
>         -hls_segment_filename /var/www/html/live/stream-%d.ts /var/www/html/live//stream.m3u8
> ```
You can use this parameter, it will map all audio tracks
-map "0:a?"  # <---------
