### ISSUE TITLE
How to change output from rtmp to rtsp

### ISSUE THREAD

**Issue by ZelleAP** [ffplayout/ffplayout#165]
Sorry not a bug but a question!

How I can change the out from rtmp to rtsp or UDP mpeg ts stream?

**Comment by ZelleAP** [comment]
Here my failed attempt:
-c:v libx264 -crf 23 -x264-params keyint=50:min-keyint=25:scenecut=-1 -maxrate 1300k -bufsize 2600k -preset faster -tune zerolatency -profile:v Main -level 3.1 -c:a aac -ar 44100 -b:a 128k -flags +global_header -f rtsp -rtsp_transport tcp rtsp://localhost/live

Unfortunately i don't have much experience with ffmpeg. Have now already tried a few output parameters. unfortunately I can not pick up the stream with VLC. If someone would be so kind and would post here an example for a rtsp output?

**Comment by jb-alvarado** [comment]
I don't think you can pickup the stream. You need a rtsp server for listening on **rtsp://localhost/live**

see: https://superuser.com/questions/1420328/streaming-rtsp-with-ffmpeg
