### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by sankamaduranga** [ffplayout/ffplayout#174]
please give how to install command on my ubuntu vps

**Comment by jb-alvarado** [comment]
The readme contains everything.

**Comment by sankamaduranga** [comment]
> 

i tired so many times please help me give me example command

**Comment by jb-alvarado** [comment]
You have ask about install commands, and this are here: [install.md](https://github.com/ffplayout/ffplayout/blob/master/docs/install.md). 

If this is not not working, you need o give more details.

**Comment by sankamaduranga** [comment]
> 

that is not run in my ubuntu vps  
           how to run this can i give command for install this one

**Comment by sankamaduranga** [comment]
> 

1 ) sudo dpkg -i  https://github.com/ffplayout/ffplayout/releases/download/v0.13.2/ffplayout_0.13.2_arm64.deb
2) apt install /tmp/ffplayout_0.13.2_amd64.deb
 
Am i Correct

**Comment by jb-alvarado** [comment]
```
# wget https://github.com/ffplayout/ffplayout/releases/download/v0.13.2/ffplayout_0.13.2_amd64.deb -P /tmp/
# apt install /tmp/ffplayout_0.13.2_amd64.deb
```

**Comment by sankamaduranga** [comment]
how to go to stream preview page

**Comment by jb-alvarado** [comment]
Entschuldigung, ich möchte nicht unfreundlich sein, aber ich würde dich bitten dein Anliegen besser und ausführlicher zu beschreiben. So weiß ich nicht wirklich was du möchtest.

Als allgemeine Regel in etwa:
1. Was möchtest du erreichen?
2. Was hast du schon probiert?
3. Hast du schon die Hilfedokumente unter [/docs/](/docs) angeschaut?
4. Was genau geht nicht?
5. Eventuell Logging output
6. Aktuelle Konfiguration
