### ISSUE TITLE
multiple and animated logos

### ISSUE THREAD

**Issue by nativemad** [ffplayout/ffplayout#183]
Hi
I have a friend who is a quite talented artist and he keeps making awesome logos for my tv channels.
I currently use a little wrapper to randomly pick a logo from a folder and set it's path in the yml config, right before ffplayout gets started (on demand through tvheadend).
This is working fine, but it would be great if I could get rid of that wrapper and set a folder instead of a specific logo directly.
Another issue I get asked for are animated logos. Currently it just shows the first frame if a gif is set as logo.

Thank you for keeping me and my friends entertained for years already! :-)

**Comment by stevenjohnk** [comment]
Share the script you are using now

**Comment by nativemad** [comment]
[madtv.sh.txt](https://github.com/ffplayout/ffplayout/files/9442213/madtv.sh.txt)

**Comment by jb-alvarado** [comment]
Hello @nativemad,
at the moment I can not imagine to integrate the function for a folder with random picking a logo. It would be not to difficult, but in my opinion it to specific and not many people need this. This makes it difficult to maintain.

An animated logo is different, this is a more general useful feature. I will see what I can do to make it possible.

What I can also image:
- to expose the hole filter string from logo overlay, which would look like: `movie=input.png,loop=loop=-1:size=1:start=0,format=rgba,colorchannelmixer=aa=0.7[l];[v][l]overlay=12:12:shortest=1"` But I'm afraid that for a normal user this is to complex.
- give a generic `custom_filter:` parameter in the config,  so user can add his own filters.

Both options could be uses to apply multiple logos.

A third option would be, to integrate a `filter:` option to every playlist item. With that you could apply a custom filter to every video clip.

**Comment by nativemad** [comment]
Thank you @jb-alvarado 
I would be happy with either option 1 or 2.
That way I could also watch out for a gif extension within my wrapper and apply a different filter in that case.
The third option is probably a bit too much for my case, as I don't use a playlist. I use the folder option for playing random clips.

**Comment by jb-alvarado** [comment]
Maybe with option 1 or 2 you don't even need your wrapper script. Because there is a filter [maskedmerge](https://ffmpeg.org/ffmpeg-filters.html#maskedmerge), which has timeline support. I think you can use this for an expression to switch your logos, or to use zmq to switch manually.

**Comment by jb-alvarado** [comment]
Here would be a example with zmq:

```
ffmpeg -re -i input.mp4 -filter_complex "movie=logo1.jpg,scale=200:200[l1];movie=logo2.jpg,scale=200:200[l2];color=black:s=200x200,zmq[s];[l1][l2][s]maskedmerge[m];[0:v][m]overlay=12:12[o]" -map "[o]" -c:v rawvideo -f nut - | ffplay -
```

Switching works then with:

```
echo Parsed_color_4 c white | zmqsend
echo Parsed_color_4 c black | zmqsend
```

But it works not correctly with alpha channels.

**Comment by nativemad** [comment]
>But it works not correctly with alpha channels.
Yes, it somehow merges the two logos and only applies the outlines of the first one.
I guess it would be easier to just work with one logo per startup through the wrapper...

**Comment by nativemad** [comment]
> [jb-alvarado](https://github.com/jb-alvarado) added a commit to jb-alvarado/ffplayout that referenced this issue

Wow, you are my hero! 
The animation is a bit faster than usually, but it works! :-)
Thank you so much, I certainly owe you more than just a beer! ;-)

**Comment by jb-alvarado** [comment]
> The animation is a bit faster than usually, but it works! :-) 

Would it be possible to have an example? Then I can check why this is happen.
The program normally gets the FPS from the animated image and apply it, but maybe something went wrong with that.

> Thank you so much, I certainly owe you more than just a beer! ;-)

You are welcome!

**Comment by nativemad** [comment]
![MadTV_Break_1](https://user-images.githubusercontent.com/834800/187372191-f6a71579-c48d-4ba0-9fde-b7f887ce67af.gif)

**Comment by jb-alvarado** [comment]
Thank you, I think I see the problem. I though I can get only the first number from FPS (41/3), which would be 43, but I think that is not correct. Can you ask your friend, if the original FPS was 13,6? Just to be sure :-).

**Comment by jb-alvarado** [comment]
No worry I got it already ;-).
