### ISSUE TITLE
[Decoder] stuffing too large

### ISSUE THREAD

**Issue by MrTheFirst** [ffplayout/ffplayout#200]
**Describe the bug**

I wan run video playlist stream with SRS.

1. Working ffmpeg + playlist.tx + SRS but this is inconvenient: 
- the playlist is managed manually
- work through the console
- no schedule

playlist.txt (I download the video from my youtube)
`file /home/video/super1.mp4`
run command:
`ffmpeg -stream_loop -1 -re -f concat -safe 0 -i playlist.txt -c copy -f flv rtmp://localhost/live/livestream`

Server load:
![Screenshot 2022-10-05 at 16 45 01](https://user-images.githubusercontent.com/4955590/194075762-43b1a8b0-8660-4ae2-a765-2331a81b3d11.png)

output:
```
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55c29750c3c0] Auto-inserting h264_mp4toannexb bitstream filter
Input #0, concat, from 'playlist.txt':
  Duration: N/A, start: 0.000000, bitrate: 1365 kb/s
  Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 1237 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc
    Metadata:
      creation_time   : 2019-03-14T10:34:51.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 03/14/2019.
      vendor_id       : [0][0][0][0]
  Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s
    Metadata:
      creation_time   : 2019-03-14T10:34:51.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 03/14/2019.
      vendor_id       : [0][0][0][0]
Output #0, flv, to 'rtmp://localhost/live/livestream':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0(und): Video: h264 (High) ([7][0][0][0] / 0x0007), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 1237 kb/s, 25 fps, 25 tbr, 1k tbn, 12800 tbc
    Metadata:
      creation_time   : 2019-03-14T10:34:51.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 03/14/2019.
      vendor_id       : [0][0][0][0]
  Stream #0:1(eng): Audio: aac (LC) ([10][0][0][0] / 0x000A), 44100 Hz, stereo, fltp, 128 kb/s
    Metadata:
      creation_time   : 2019-03-14T10:34:51.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 03/14/2019.
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=  485 fps= 25 q=-1.0 size=    3178kB time=00:00:19.32 bitrate=1347.3kbits/s speed=   1x 
```

2. The new solution is ffplayout + SRS.
Tried different configuration, failed to include what works in the first solution. When I run the same video file, I get an error.
```
[2022-10-05 13:24:28.01065] [ WARN] ffmpeg contains no libfdk-aac! Can't use high quality aac encoder...
[2022-10-05 13:24:28.01079] [DEBUG] Status file path: /home/ffpu/.ffp_status
[2022-10-05 13:24:28.01121] [ INFO] Playout in folder mode
[2022-10-05 13:24:28.01127] [DEBUG] Monitor folder: /home/video
[2022-10-05 13:24:28.01157] [DEBUG] Encoder CMD: "ffmpeg -hide_banner -nostats -v level+error -re -i pipe:0 -c:v mpeg2video -crf 23 -x264-params keyint=50:min-keyint=25:scenecut=-1 -pix_fmt yuv720p -maxrate 1300k -bufsize 2600k -preset faster -tune zerolatency -profile:v Main -level 3.1 -c:a aac -ar 44100 -b:a 128k -flags +cgop -level 3.1 -f flv rtmp://localhost/live/livestream"
[2022-10-05 13:24:28.13610] [ INFO] Play for 00:01:27.841: /home/video/super1.mp4  
[2022-10-05 13:24:28.13618] [DEBUG] Decoder CMD: "ffmpeg -hide_banner -nostats -v level+error -i /home/video/super1.mp4 -filter_complex [0:v]null[vout1] -map [vout1] -map 0:a -pix_fmt yuv420p -r 25 -c:v mpeg2video -g 1 -b:v 92160k -minrate 92160k -maxrate 92160k -bufsize 46080k -c:a s302m -strict -2 -sample_fmt s16 -ar 48000 -ac 2 -f mpegts -"
[2022-10-05 13:24:28.28505] [ERROR] [Decoder] [mpeg2video @ 0x55a5073eaa80]  stuffing too large
[2022-10-05 13:24:28.28519] [ERROR] [Decoder]  Video encoding failed
```
And CPU load to 100%
![Screenshot 2022-10-05 at 16 49 31](https://user-images.githubusercontent.com/4955590/194076838-409784db-51ed-422e-bf22-bdfae1c11038.png)

How can I run my playlist similar to the first solution but through ffplayout to get all the control flexibility?

my ffplayout.yml are set to default other than output params:
```
out:
  mode: stream
  output_param: >-
        -f flv rtmp://localhost/live/livestream
```

**Comment by jb-alvarado** [comment]
You are using the wrong codec for output. Try something like:

``YAML
output_param: >-
        -c:v libx264
        -crf 23
        -x264-params keyint=50:min-keyint=25:scenecut=-1
        -maxrate 1300k
        -bufsize 2600k
        -preset faster
        -tune zerolatency
        -profile:v Main
        -level 3.1
        -c:a aac
        -ar 44100
        -b:a 128k
        -flags +global_header
        -f flv rtmp://localhost/live/livestream
``` 

I don't now if this is the only problem, but try this first.

**Comment by MrTheFirst** [comment]
@jb-alvarado Спасибо за ответ, но это не помогло. Уже эксперементировал с различными конфигами. 
```
[2022-10-05 14:43:24.57439] [ INFO] Play for 00:01:27.841: /home/video/super1.mp4  
[2022-10-05 14:43:24.57449] [DEBUG] Decoder CMD: "ffmpeg -hide_banner -nostats -v level+error -i /home/video/super1.mp4 -filter_complex [0:v]null[vout1] -map [vout1] -map 0:a -pix_fmt yuv420p -r 25 -c:v mpeg2video -g 1 -b:v 92160k -minrate 92160k -maxrate 92160k -bufsize 46080k -c:a s302m -strict -2 -sample_fmt s16 -ar 48000 -ac 2 -f mpegts -"
[2022-10-05 14:43:24.74478] [ERROR] [Decoder] [mpeg2video @ 0x56452cc8aa80]  stuffing too large
[2022-10-05 14:43:24.74494] [ERROR] [Decoder]  Video encoding failed
```

As I understand it, the wrong codec is used and there is not enough processor power for decoding. At the same time, the solution through ffmpeg uses automatic parameters (`[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55e2622dc800] Auto-inserting h264_mp4toannexb bitstream filter`) and the processor is not even 10% loaded.

I want to configure ffplayout to work in a similar way, without loading the processor.

P.S. I may be wrong in the definitions.

**Comment by jb-alvarado** [comment]
Hm that is wired, never had this error before. I don't think the problem is `h264_mp4toannexb`, as I understand this only fixes the concat, but maybe I'm wrong. Can you provide a example video file? But please only legal, non age restricted content.

With ffplayout you will have a bit overhead compared to only ffmpeg, but not that much.

**Comment by MrTheFirst** [comment]
[Videofile](https://api.emelyanov.pw/super1.mp4)
It's not scary if the load is greater, but not ten times?
Now I'm using a very weak server - CPU: 1, RAM: 1 GB. But it handles fine with ffmpeg. If I manage to solve the problem, then I will choose a more powerful server.

**Comment by jb-alvarado** [comment]
> Now I'm using a very weak server - CPU: 1, RAM: 1 GB. 

Ah, that is the problem. For ffplayout I recommend at least 4 Cores and 3 GB. Less could be possible, but have to test.

> But it handles fine with ffmpeg.

Yes, but with ffmpeg you have used `-c copy`, which is not* possible in ffplayout.

\* When your srs creates HLS, or you have no problems with gaps between the clips, you can try to cheat with:
use output mode **hls** but with outputting rtmp. But I can not guarantee how good this will work.

**Comment by MrTheFirst** [comment]
Indeed, a more productive server (CPU x4) allowed the solution to run. Failed only in playlist mode, but that's another story)
Thanks for the replies, sorry for not thinking about the performance of the machine right away.
