### ISSUE TITLE
FLV decoder ffmpeg cmd throws error when launched in shell

### ISSUE THREAD

**Issue by Ch41r05** [ffplayout/ffplayout#202]
**Describe the bug**

When looking at the logs, for testing purposes, I was trying to launch the Decoder command that is being printed, which is:

`ffmpeg -hide_banner -nostats -v level+error -i /var/lib/ffplayout/tv-media/myvideo.mp4 -filter_complex [0:v]scale=-1:576,pad=max(iw\,ih*(1024/576)):ow/(1024/576):(ow-iw)/2:(oh-ih)/2,fps=25,scale=1024:576,setdar=dar=1.778[vout1] -map [vout1] -map 0:a -pix_fmt yuv420p -r 25 -c:v mpeg2video -g 1 -b:v 58982k -minrate 58982k -maxrate 58982k -bufsize 29491k -c:a s302m -strict -2 -sample_fmt s16 -ar 48000 -ac 2 -f mpegts -`

 but I get:

`-bash: syntax error near unexpected token '('`

**To Reproduce**

1. Go to 'Logging' tab in frontend
2. Run the ffmpeg Decoder CMD command while having another session up with the encoder

**Expected behavior**

What is printed in the log should actually be exectutable, provided correct pathing

**Desktop/Server/Software (please complete the following information):**

 - OS: Linux DietPi 5.15.61-v8+ 
- ffplayout: 0.15.2
- ffmpeg: 4.3.4
- are you using the current master of ffplayout? Yes

Looking into the source code, I identified the issue in file ffplayout-engine/src/output/mod.rs lines 112:129 since the output is generated before the actual object is instantiated so if the object becomes different from the simple string concatenation of parameters, the two wouldn't be equal anymore.

**Config Settings:**

- command line arguments
- config fie

**Logging:**

- content of: ffplayout.log

**Comment by jb-alvarado** [comment]
When you want to run comments in terminal, you have to put the filters and mapping parameters in quote's.

**Comment by Ch41r05** [comment]
Thanks, @jb-alvarado I think I understood what you mean, would you mind providing an example for future reference so I can also double-check if what I'm doing is the intended way?

**Comment by jb-alvarado** [comment]
You can run them in one session, like:

```BASH
ffmpeg -hide_banner -nostats -v level+error -i /var/lib/ffplayout/tv-media/myfile.mp4 \
    -filter_complex "[0:v]scale=1024:576[vout1]" -map "[vout1]" -map 0:a \
    -pix_fmt yuv420p -r 25 -c:v mpeg2video -g 1 -b:v 58982k -minrate 58982k -maxrate 58982k -bufsize 29491k \
    -c:a s302m -strict -2 -sample_fmt s16 -ar 48000 -ac 2 \
    -f mpegts - | \
ffmpeg -hide_banner -nostats -v level+error -re -i pipe:0 -c:v:0 libx264 -crf 23 \
    -x264-params keyint=50:min-keyint=25:scenecut=-1 -maxrate:0 1300k -bufsize:0 2600k \
    -preset veryfast -tune zerolatency -profile:v Main -level 3.1 -c:a:0 aac -ar:0 44100 -b:a:0 128k \
    -flags +global_header -f flv rtmp_server
```
