### ISSUE TITLE
RAM memory use

### ISSUE THREAD

**Issue by cooliobr** [ffplayout/ffplayout#215]
After some tests and facing many problems with full ram use when video have 2 audios output and subtitle output in WEBVTT, i using this filter to keep RAM in 1.7Gb 
https://github.com/cooliobr/ffplayout/commit/810d63c461e152eced521c47e11d7ee62b0f4fd9

**Comment by jb-alvarado** [comment]
This is not a good use of movie filter for logos, because it not produce a correct timestamp, with animated logos it will become more clear that this is not working.

Beside this, the RAM usage is higher.

**1. Old way:**
```
ffmpeg -re -i tests/assets/with_audio.mp4 -filter_complex \
    "[0:v]null[v];movie=tests/assets/logo.png:loop=0,setpts=N/(FRAME_RATE*TB),format=rgba,colorchannelmixer=aa=0.7[l];[v][l]overlay=W-w-12:12:shortest=1[vout0]" \
    -map "[vout0]" -map "0:a" -f null -
```
Uses 433056 Bytes of RAM.

**2. Your way:**
```
ffmpeg -re -i tests/assets/with_audio.mp4 -filter_complex \
    "[0:v]null[v];movie=tests/assets/logo.png[p];[p]format=rgba,colorchannelmixer=aa=0.5[l];[v][l]overlay=main_w-overlay_w-25:25:format=auto,format=yuv420p[vout0]" \
    -map "[vout0]" -map "0:a" -f null -           
```
Uses 509352 Bytes of RAM.

**Comment by jb-alvarado** [comment]
Ok with [test file](https://github.com/jb-alvarado/ffplayout/blob/master/tests/assets/dual_audio_vtt.mkv), I can reproduce this error.

Is an issue with ffmpeg, which also happens with:

```
ffmpeg -re -i tests/assets/dual_audio_vtt.mkv -stream_loop -1 -i tests/assets/logo.png -filter_complex \
    "[0:v]null[v];[1:v]format=rgba,colorchannelmixer=aa=0.5[l];[v][l]overlay=main_w-overlay_w-25:25:format=auto,format=yuv420p[vout0]" \
    -map "[vout0]" -map "0:a:0" -map "0:a:1" -map 0:s:0 -c:s srt -f null -
```
As soon as the logo get looped, this problem pops up.

**Comment by cooliobr** [comment]
OK, this way will keep animated logos in loop without increase memory

`ffmpeg -re -i tests/assets/with_audio.mp4 -filter_complex \
    "[0:v]null[v];movie=tests/assets/logo.png:loop=0,setpts=N/(25*TB)[p];[p]format=rgba,colorchannelmixer=aa=0.5[l];[v][l]overlay=main_w-overlay_w-25:25:format=auto,format=yuv420p[vout0]" \
    -map "[vout0]" -map "0:a" -f null -           `

**Comment by cooliobr** [comment]
my test command

` ffmpeg -i /var/lib/ffplayout/tv-media/Filmes/Lucy.mp4 -filter_complex "movie=mulher.gif:loop=0,setpts=N/(25*TB)[l];[l][0]scale2ref=w=oh*mdar:h=ih*0.13[logo][video];[logo]format=rgba,colorchannelmixer=aa=0.3[ltrans];[video][ltrans]overlay=main_w-overlay_w-25:25:format=auto,format=yuv420p" -c:v h264_nvenc -f nut - | ffplay -`

**Comment by jb-alvarado** [comment]
I think I had something like this before and it was not working so good to. The problem is also, that gifs have different framerates.

I wrote in the ffmpeg user Mailinglist, but got no response.

Maybe it would be good to create a bug report on the tracker.

**Comment by jb-alvarado** [comment]
Ah and I see you are using another test file. You need to use a file with subtitles. The problem only come up in combination with loop image, overlay it and pass a subtitle.

**Comment by cooliobr** [comment]
Yes, I'm using a file with subtitle, all of my files have 2 or 3 audio tracks and sub tracks.

**Comment by jb-alvarado** [comment]
> my test command
> 
> ` ffmpeg -i /var/lib/ffplayout/tv-media/Filmes/Lucy.mp4 -filter_complex "movie=mulher.gif:loop=0,setpts=N/(25*TB)[l];[l][0]scale2ref=w=oh*mdar:h=ih*0.13[logo][video];[logo]format=rgba,colorchannelmixer=aa=0.3[ltrans];[video][ltrans]overlay=main_w-overlay_w-25:25:format=auto,format=yuv420p" -c:v h264_nvenc -f nut - | ffplay -`

You forgot the mapping, try this and you will see that is the same problem:

``
ffmpeg -re -i tests/assets/dual_audio_vtt.mkv -filter_complex "movie=cute.gi':loop=0,setpts=N/(25*TB)[l];[l][0]scale2ref=w=oh*mdar:h=ih*0.13[logo][video];[logo]format=rgba,colorchannelmixer=aa=0.3[ltrans];[video][ltrans]overlay=main_w-overlay_w-25:25:format=auto,format=yuv420p" -map 0 -c:v libx264 -c:s webvtt -f mpegts - | ffplay -v quiet -
``

I think that combination is not working. Maybe you want to create a bug tracker entry by ffmpeg? 

The only solution at the moment I see, is to skip the logo, when the subtitle is important.

**Comment by cooliobr** [comment]
I will open a bug tracker, but on my case it is working at last 24h 😀 , no delay, no restar, with vtt subtitle and 2 audios, now i will change ffmpeg source to remove `#EXT-X-DISCONTINUITY` in hls  to prevent any stop of stream play

**Comment by jb-alvarado** [comment]
That is great, that it works for you.

Normally you don't need to patch ffplayout for the functionality. Just deactivate the logo and add it with [custom filter](https://github.com/ffplayout/ffplayout/blob/master/docs/custom_filters.md).

**Comment by cooliobr** [comment]
![Captura de Tela 2022-10-21 às 11 23 03](https://user-images.githubusercontent.com/4358538/197219052-0c70f8ff-0198-4c77-b567-db1e2cfbdd58.png)

![Captura de Tela 2022-10-21 às 11 27 43](https://user-images.githubusercontent.com/4358538/197219872-6a3b0bad-7252-4fe7-9a02-5ed0337947ad.png)
@jb-alvarado two channels in 720p, two audio tracks and subtitle. see load and cpu use and GPU use on second image.
Now i looking for any to reduce start time of encoding because this i facing some "loading" issue on screen when change videos. but now i guess that this playout system  is better than pro systems

**Comment by jb-alvarado** [comment]
Nice! Whit the example setting I had not notice any loading issues, but with your setup I have no experience.

**Comment by cooliobr** [comment]
is the first time that I use HLS output with Playout, may it is because segment list stop for some time before re start playlist, may I need to test it with multicast.

**Comment by jb-alvarado** [comment]
Whit `-hls_flags append_list+delete_segments+omit_endlist` it should not restart the playlist, it should continue the existing one.

**Comment by cooliobr** [comment]
> Whit `-hls_flags append_list+delete_segments+omit_endlist` it should not restart the playlist, it should continue the existing one.

Yes I know, but when video change, the new .ts file on the playlist will be appended 12 or 16 seconds after ffmpeg start, then it will do some "loading" on screen/player, I will do some tests with concat [https://trac.ffmpeg.org/wiki/Concatenate](https://trac.ffmpeg.org/wiki/Concatenate)

**Comment by jb-alvarado** [comment]
> the new .ts file on the playlist will be appended 12 or 16 seconds after ffmpeg start

When your `hls_time` is only 6 seconds and it takes 12-16 seconds for ffmpeg to add a new segment, then something is not working correctly. it should take some milliseconds to pick a new file and start encoding. And HLS players normally don't play really "realtime". The most of them takes around 30 seconds to start playing. So in theories the is plenty of time.

**Comment by cooliobr** [comment]
I found my problem, when I set -var_stream_map and -master_pl_name it increase time of validation of chuncks, then I remove these parameters, create a playlist.m3u8 manualy and clean folder of channel. now it don't load when restart ffplayout.

my output_param
`-c:v h264_nvenc -aspect 16:9 -r:v 30 -b:v 3200k -maxrate 3900k -bufsize 4900k -profile:v main -preset p4 -level 41 -delay 0 -ar 48000 -b:a 128k -c:a libfdk_aac -map 0:s:0 -c:s webvtt -metadata:s:a:1 language=Por -metadata:s:a:0 language=Eng -colorspace:v bt709 -color_primaries:v bt709 -color_trc:v bt709 -color_range:v tv -f hls -hls_time 5 -hls_list_size 20 -hls_flags second_level_segment_index+append_list+omit_endlist+delete_segments+program_date_time -strftime 1 -hls_segment_filename /home/playout/stream/stream-%v-%%04d.ts /home/playout/stream/stream_%v.m3u8` 

my playlist.m3u8
`#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subtitle",NAME="subtitle_0",DEFAULT=YES,LANGUAGE="Por",URI="stream_0_vtt.m3u8"
#EXT-X-STREAM-INF:BANDWIDTH=3660800,RESOLUTION=1280x720,CODECS="avc1.4d4029,mp4a.40.2",SUBTITLES="subtitle"
stream_0.m3u8`
