### ISSUE TITLE
Logo scale

### ISSUE THREAD

**Issue by cooliobr** [ffplayout/ffplayout#244]
can you put a logo scale in lib/filter/mod? line 292
I saw, in your code don't apply scale of logo
       -     "null[v];movie={}:loop=0,setpts=N/(FRAME_RATE*TB),format=rgba,colorchannelmixer=aa={}[l];[v][l]{}:shortest=1",
       +     "null[v];movie={}:loop=0,setpts=N/(FRAME_RATE*TB),format=rgba,colorchannelmixer=aa={},scale=iw*0.{}:-1[l];[v][l]{}:shortest=1",

       -     config.processing.logo, config.processing.logo_opacity, config.processing.logo_filter
       +    config.processing.logo, config.processing.logo_opacity, config.processing.logo_scale, config.processing.logo_filter

**Comment by jb-alvarado** [comment]
Hm strange... one time in the past it was there 🙂.

I will add it.

**Comment by jb-alvarado** [comment]
Thanks. I think we should open a new HW issue, to gather there all the infos. At the moment we talk in 3 issues about this topic, that is to confusing :-).

**Comment by cooliobr** [comment]
Ok... it is only to expose my version
