### ISSUE TITLE
Animated logo in QuickTime "mov" file - how to disable loop animation

### ISSUE THREAD

**Issue by sdorpl** [ffplayout/ffplayout#247]
Hello. In python version(v4.x) I was using animated logo in "mov" file with alpha channel, to make it work I modified "/opt/ffplayout_engine/ffplayout/filters/default.py".
In versions written in Rust (v5.x), the animation also works, but there is one problem - it is looped. How to make the animation stop at the last frame after the animation is done?
I am sending the file "default.py" from the python version that works for me:

https://pastebin.pl/view/1841d6d3

Regards.

**Comment by jb-alvarado** [comment]
Hello @sdorpl, you have two options:

1. you can modify this line: https://github.com/ffplayout/ffplayout/blob/37e08b0ec7e5f68f65e3348bfb0d1bf1139665fa/lib/src/filter/mod.rs#L292 and compile ffplayout by your own. 

2. You can disable logo in config, and add you logo in the `custom_filter:` setting. Examples for this you found here: [custom_filters](https://github.com/ffplayout/ffplayout/blob/master/docs/custom_filters.md)

**Comment by sdorpl** [comment]
Thanks for instucions. Can you share instuction for compile IT ? I have a windows or Linux os,.

**Comment by jb-alvarado** [comment]
There is some introductions [here](https://github.com/ffplayout/ffplayout/blob/master/docs/developer.md). When you install Rust from [rustup](https://rustup.rs/) and you run ffplayout on the same machine where you compile, you only need to run `cargo build --release`, or use the comment from introduction to build a deb-package.
