### ISSUE TITLE
Error when try to create channel by API

### ISSUE THREAD

**Issue by cooliobr** [ffplayout/ffplayout#251]
Hi, i try this command to create a channel but i receive this error.
last version of ffplayout i dont try it with other version yet

curl -X POST http://127.0.0.1:8787/api/channel/ -H "Content-Type: application/json" \
 -d '{ "name": "Channel 5", "preview_url": "http://localhost/live/channel2.m3u8", \
 "config_path": "/etc/ffplayout/channel006.yml", "extra_extensions": "jpg,jpeg,png",
 "service": "ffplayout@channel005.service" }' \
 -H "Authorization: Bearer XXXXXXXXXX"

**Json deserialize error: key must be a string at line 1 column 78**

**Comment by jb-alvarado** [comment]
Hello @cooliobr, maybe the json object can not go over [multiple line](https://stackoverflow.com/questions/34847981/curl-with-multiline-of-json)? Can you try, to use this in one line?

**Comment by cooliobr** [comment]
> Hello @cooliobr, maybe the json object can not go over [multiple line](https://stackoverflow.com/questions/34847981/curl-with-multiline-of-json)? Can you try, to use this in one line?

in one link it works, but I was using  example line that have in docs/api ...
but now I know how to exec these commands

**Comment by jb-alvarado** [comment]
Yes, I should change this, in the docs.
