### ISSUE TITLE
Slow when have many files in playlist

### ISSUE THREAD

**Issue by cooliobr** [ffplayout/ffplayout#256]
I have a playlist with about 70 video files, when I click on player, it takes about 30 seconds to load the screen with the playlist, to place new files or to click on some function, it becomes very heavy.
i have tried in Chrome, Safari, Firefox, Firefox Developer.

If i remove some files and keep only 10, it show ok and fast.

Any suggestion to this?

**Comment by jb-alvarado** [comment]
70 Files normal should be ok, but in general you need a bit patience :-). I'm working on a frontend update with Nuxt 3 and bootstrap 5. It should have a big performance improvement.

**Comment by cooliobr** [comment]
Thanks
