### ISSUE TITLE
windows issues

### ISSUE THREAD

**Issue by jeremy123g** [ffplayout/ffplayout#268]
obviously windows is the most popular operating system but all the instructions don't mention windows but obviously there's a windows version of ffplayout in the releases.  

all i wanna do is install ffplayout and use the frontend if possible

**Comment by jb-alvarado** [comment]
Hi Jeremy, I will try to answer both of your questions here as they are related.

Yes, you are right, Windows is the most popular *desktop* system and if you search for playout software, professional or free, almost all of them are made for Windows. When it comes to Linux, open source and **headless** running playout it becomes very rare. 

With this in mind, ffplayout was created. I wanted a lightweight solution that could run in Linux cloud environments. But of course it is always nice to support more platforms, but at the moment I see the Windows support more for simple usage, testing and in general to get an idea of ffplayout. For production, Linux is the way to go.

At the moment there are some big drawbacks to running ffplayout on other platforms than Linux:
- Only Linux has a service management and only here it is possible to start and stop ffplayout from the frontend.
- There is no installer to set everything up.
- The user has to manage the startup on boot, restart on error, etc. by himself.
- Lack of documentation and support. 
- ffplayout does not have a classic GUI, it is a terminal application with a web frontend.

### Now to your question
1. about the logging: in the configuration you can set a path where the logging should be written to. But you can also set the path via the command line. You can run ffplayout from a terminal with the `-h` option to get an idea of the possible options. For example, if you do `ffplayout -l none', the logging will not go to a file, but to the terminal.

2. If you want to run the frontend, you have to run for example `ffpapi -l 127.0.0.1:8787`, open your web browser and go to `http://127.0.0.1:8787`. But first you have to init ffpapi and add a user:

```
ffpapi -i
ffpapi -a
```
But as I said, when it comes to controlling ffplayout, this will not be possible in Windows. You can fast forward, rewind, and reset the playback state, but you cannot start, stop, or restart from the frontend.

So in a second terminal you have to run the ffplayout engine.

It can be that ffplayout is not exactly what you are looking for, then maybe [obs](https://obsproject.com/de), [casparCG](http://casparcg.com/), [vmix](https://www.vmix.com/), [DPO 100](https://www.datavideo.com/de/product/DPO-100) or even [VLC](https://www.videolan.org/vlc/index.de.html) fits better.

If there is still a real need for better Windows support, I can observe if it is possible to easily create a installer.  terminal application, with an web frontend.

### Now to your question
1. about he logging: in the configuration you can set a path, where the logging should be written to. But you can also set the path over the commend line. You can run ffplayout from terminal with option `-h` to get an idea for the possible options. For example when you can `ffplayout -l none` logging goes not to an file, but to the terminal.

2. When you want to run the frontend, you need to run for example `ffpapi -l 127.0.0.1:8787` open your web browser an go to `http://127.0.0.1:8787`. But for that you have to init ffpapi first, and add a user:

```
ffpapi -i
ffpapi -a
```
But as I say, when it come to controlling ffplayout, this will not be possible in Windows. You can move forward, backward and reset play state, but you can not start, stop or restart over the frontend. So you need to run the ffplayout engine in a second terminal.

It may be that ffplayout is not exactly what you are looking for, then maybe [obs](https://obsproject.com/de), [casparCG](http://casparcg.com/), [vmix](https://www.vmix.com/), [DPO 100](https://www.datavideo.com/de/product/DPO-100) or even [VLC](https://www.videolan.org/vlc/index.de.html) will fit better.

If there is still a real need for better Windows support, I can see if it is possible to easily create an installer.
