### ISSUE TITLE
Error when trying to install on centos 7

### ISSUE THREAD

**Issue by 0DUDDU** [ffplayout/ffplayout#273]
**Describe the bug**

Got this error when trying to install on centos 7

```
rpm -i ffplayout-0.16.7-1.x86_64.rpm 
error: unpacking of archive failed: cpio: Bad magic
error: ffplayout-0:0.16.7-1.x86_64: install failed
```

**To Reproduce**

1. Download the latest release
2. Try install

**Desktop/Server/Software (please complete the following information):**

 - OS: 
 ```
 cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)
```

**Comment by jb-alvarado** [comment]
Hello @0DUDDU,
thank you for the report. I was not aware of that there could be incompatibility in different rpm versions. I found no fast way to build the installer package under Centos 7. If you need a rpm packages, you could dive in the **scripts/build.sh** script, and check if you can manage the build by your self. But you need at least nodejs 16.

Or you just follow the [manual install instruction](https://github.com/ffplayout/ffplayout/blob/v0.17.0/docs/install.md#manual-install). If there is a step, you stuck on, feel free to ask.

**Comment by 0DUDDU** [comment]
Hi, thanks for your fast reply
I managed to make the rpm usable by adding `--payload-compress none`
like this `cargo generate-rpm --payload-compress none --target=x86_64-unknown-linux-musl -o ../ffplayout-${version}-1.x86_64.rpm`

**Comment by jb-alvarado** [comment]
Ah, cool! I will see if I can apply this to the new builds.
