### ISSUE TITLE
How i can put multiple logos with custom filter?

### ISSUE THREAD

**Issue by AndrewMercedesBrito** [ffplayout/ffplayout#287]
i trying to put another logo with this line in custom filter.

in.png -filter_complex "[1]format=yuva444p,colorchannelmixer=aa=0.5[in2];[0][in2]overlay"[c_v_out]

but is give me error!, please help me!.

**Comment by jb-alvarado** [comment]
Hello Andrew,
did you check the [custom_filters](https://github.com/ffplayout/ffplayout/blob/master/docs/custom_filters.md) docs? There is an example for lower thirds, which should fit your need.

It only can be that you have to use the latest v0.17 beta, because there is bug fix related to the custom filter.

**Comment by AndrewMercedesBrito** [comment]
Ok, you can make me a line?, for a logo in a 640x480 stream?

**Comment by jb-alvarado** [comment]
Something like:

```YAML
custom_filter: "[v_in];movie=/path/to/logo.png:loop=0,setpts=N/(25*TB)[l];[v_in][l]overlay=W-w-12:12:shortest=1[c_v_out]"
```

But the position you have to adjust.

**Comment by AndrewMercedesBrito** [comment]
fmpeg error on position 7 - 08:22:07.815: /var/lib/ffplayout/tv-media/Series/meteoro/MNG-01x02 - Serieslan.com.mp4:
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x5613f4457480] Invalid stream specifier: v_in.
Stream specifier 'v_in' in filtergraph description [0:v:0]pad=max(iw\,ih*(640/480)):ow/(640/480):(ow-iw)/2:(oh-ih)/2,scale=640:480,setdar=dar=4.3;movie=/usr/share/ffplayout/logo.png:loop=0,setpts=N/(25*TB)[l];[v_in][l]overlay=W-w-0:0:shortest=1[vout0];[0:a:0]anull,loudnorm=I=-18:TP=-1.5:LRA=11[aout0] matches no streams.

**Comment by AndrewMercedesBrito** [comment]
i got error when i put it!......

**Comment by jb-alvarado** [comment]
Which ffplayout version did you use?

**Comment by AndrewMercedesBrito** [comment]
https://github.com/ffplayout/ffplayout/releases/tag/v0.16.7

**Comment by jb-alvarado** [comment]
Ah ok, that I was saying in my second post, that there was a bug. You have to use the latest v0.17 beta.

The next days I will create a final release, but in general the beta should be stable enough.

**Comment by AndrewMercedesBrito** [comment]
Omg is works nowwww!!! thank you Alvarado, you great.... regards from puerto rico.
