### ISSUE TITLE
Docker is not displaying the video file's time.

### ISSUE THREAD

**Issue by cooliobr** [ffplayout/ffplayout#295]
Maybe because I've never used the rpm version, I had never noticed this, but this version via Docker is not showing the video time and it doesn't finish uploading.
Maybe I'm not doing something right, can you help me?

![Captura de Tela 2023-03-26 às 10 12 48](https://user-images.githubusercontent.com/4358538/227778054-d4940173-3250-46bd-8da4-673d4795eb74.png)
![Captura de Tela 2023-03-26 às 10 14 09](https://user-images.githubusercontent.com/4358538/227778101-4be5fd9e-7c7a-488a-b58b-d5288f0d24f2.png)

**Comment by jb-alvarado** [comment]
The progress bar from upload dialogue is not filled correctly, so it could be that the upload is finished, but it looks like is not. When it shows `done...` it should be fine. 
About the missing video duration, I don't know, maybe @0DUDDU has an idea? Maybe ffprobe is missing? Is there any logging?

**Comment by cooliobr** [comment]
ffprobe is ok, i test it manual, tomorrow I will test more

**Comment by 0DUDDU** [comment]
Hello, can you share logs from `/var/log/ffplayout/` ?

**Comment by jb-alvarado** [comment]
I created the latest beta. When we fix this issue I will create a final release.

**Comment by 0DUDDU** [comment]
an other info, don't know if it's related but I know that docker run a bit differently on macOS compared to Linux

I tested the upload and it's working fine for me, but I'm using k8s so not really docker

about the timing not showing in playlist, got same problem, the `browse` endpoint return a duration at 0 for every file

**Comment by cooliobr** [comment]
my work environment is:
HOST = Ubuntu 18.04
Nvidia Tesla k80
Nvidia RTX3060

Docker image = Centos 7
ffmpeg from "fromsource.Dockerfile" without Nvidia 



Ps.: If I install it directly on the HOST machine, everything works perfectly. ( .deb )

**Comment by jb-alvarado** [comment]
Not in a special way, the program just runs the system command: ffprobe ..., the same way it calls ffmpeg.

I have some more issues, also in the GUI, so I remove latest beta.

**Comment by cooliobr** [comment]
> Not in a special way, the program just runs the system command: ffprobe ..., the same way it calls ffmpeg.
> 
> I have some more issues, also in the GUI, so I remove latest beta.

i was testing the last beta... heheheh 
now i will try to use docker with nvenc+ffmpeg

**Comment by 0DUDDU** [comment]
after further test, I have found what is missing. The ffpu user doesn't have the path to lib in env
`LD_LIBRARY_PATH=/usr/local/lib64:/usr/local/lib` 

I will open a PR soon to fix this for docker

**Comment by 0DUDDU** [comment]
Here it is #298

**Comment by 0DUDDU** [comment]
It's better to separate local executables from other, https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s09.html
And the build/install of ffmpeg from source is done in `/usr/local` and then it copy all the content of `/usr/local` into same place in the image, so if we build it in `/usr` it will copy some unecessary files. If we copy `/usr/local` to `/usr` it may override system libs

**Comment by cooliobr** [comment]
I made some modifications to use CUDA and Nvidia, and added some paths for better performance. After that, I will export the image for everyone to use.

**Comment by jb-alvarado** [comment]
Nice to hear! But please have in mind that you can not publish an image with ffmpeg non free option. If you want to can create a pull request with a Dockerfile.

**Comment by jb-alvarado** [comment]
v0.17.0 is out and both issues should be fixed, so I can can close here. 🙂
