### ISSUE TITLE
Upload media file (mp4 or mkv) not work

### ISSUE THREAD

**Issue by jb-alvarado** [ffplayout/ffplayout#309]
### Discussed in https://github.com/ffplayout/ffplayout/discussions/308

<div type='discussions-op-text'>

<sup>Originally posted by **operadorhal** April  5, 2023</sup>
Hello, there is an error uploading video files (*.mp4), in the MEDIA window, the search window for the file to upload opens, once selected from the PC by pressing the UPLOAD button, the window will open. it closes without any kind of message, so you don't know if it's uploading or not. Also note that files larger than 80mb are not always uploaded, that is, some are, but most are not.
</div>

**Comment by jb-alvarado** [comment]
@operadorhal, I move the conversation to here, because there was a bug. Thanks for the posted details!

One issue I think I could fix, but it could be that there is another issue with you proxy related to the file size. I could be that the proxy only allow an upload size from 80MB, this you have to figure out.

If you want, you could test the attached packages and see if the other error is gone. 
[ffplayout_0.17.1_amd64.zip](https://github.com/ffplayout/ffplayout/files/11168497/ffplayout_0.17.1_amd64.zip)

**Comment by operadorhal** [comment]
> @operadorhal, I move the conversation to here, because there was a bug. Thanks for the posted details!
> 
> One issue I think I could fix, but it could be that there is another issue with you proxy related to the file size. I could be that the proxy only allow an upload size from 80MB, this you have to figure out.
> 
> If you want, you could test the attached packages and see if the other error is gone. [ffplayout_0.17.1_amd64.zip](https://github.com/ffplayout/ffplayout/files/11168497/ffplayout_0.17.1_amd64.zip)



Hello, I understand, thank you.
Well I will download the file to install on a new machine, I will also check the proxy restrictions.

I will answer soon, thanks for your good disposition,
I like this, but I'm not an expert

**Comment by operadorhal** [comment]
> > @operadorhal, I move the conversation to here, because there was a bug. Thanks for the posted details!
> > One issue I think I could fix, but it could be that there is another issue with you proxy related to the file size. I could be that the proxy only allow an upload size from 80MB, this you have to figure out.
> > If you want, you could test the attached packages and see if the other error is gone. [ffplayout_0.17.1_amd64.zip](https://github.com/ffplayout/ffplayout/files/11168497/ffplayout_0.17.1_amd64.zip)
> 
> Hello, I understand, thank you. Well I will download the file to install on a new machine, I will also check the proxy restrictions.
> 
> I will answer soon, thanks for your good disposition, I like this, but I'm not an expert

-----------------------------------------------------------------------------------------------------------

07/04/2023
Hello, I ran the tests, several, the result is that in local mode, it works fine in general.
But in remote mode, it only allows files smaller than 100mb.
I leave here video of tests: 1 local connection and another remote connection


https://user-images.githubusercontent.com/124960449/230542252-6c2bb04f-baa9-4513-9fbb-2feedf5e0b07.mp4


https://user-images.githubusercontent.com/124960449/230542257-91c7877f-0232-4af1-bdf7-adb44fdef2a9.mp4

**Comment by jb-alvarado** [comment]
Thank you for the records! I need to see that I can add better errors response.

I found this information:

https://community.cloudflare.com/t/limit-on-file-uploads-via-cloudflare-access/435226

Maybe that is the case?!

**Comment by operadorhal** [comment]
> Thank you for the records! I need to see that I can add better errors response.
> 
> I found this information:
> 
> https://community.cloudflare.com/t/limit-on-file-uploads-via-cloudflare-access/435226
> 
> Maybe that is the case?!

It is definitely proxy settings, cloudflare free version does not allow more than 100mb upload.

**Comment by jb-alvarado** [comment]
That is strange, that they don't allow more... But you can upload your files via ssh.

**Comment by IVEN2022** [comment]
hello @operadorhal   ,please can you tell detailed steps how you enable the preview please , thank you
