### ISSUE TITLE
scale of logo

### ISSUE THREAD

**Issue by cooliobr** [ffplayout/ffplayout#312]
Hi, ffplayout 0.17.1 is not doing logo scale again

**Comment by jb-alvarado** [comment]
Hello @cooliobr, can you show me your scale value from config? When I set it for example to: `200:-1` it works like it should.

**Comment by cooliobr** [comment]
conf..
`  mode: playlist
  audio_only: false
  width: 1920
  height: 1080
  aspect: 1.0
  fps: 30.0
  add_logo: true
  logo: /usr/share/ffplayout/Imagens/Htotv150x114png.png
  logo_scale: '0.1'
  logo_opacity: 0.7
  logo_filter: overlay=W-w-25:25
`

output
-filter_complex [0:v:0]pad=max(iw\,ih*(1920/1080)):ow/(1920/1080):(ow-iw)/2:(oh-ih)/2,null,setdar=dar=1,null[v];movie=/usr/share/ffplayout/Imagens/Htotv150x114png.png:loop=0,setpts=N/(FRAME_RATE*TB),format=rgba,colorchannelmixer=aa=0.7[l];[v][l]overlay=W-w-30:30:shortest=1,realtime=speed=1.0000582667778577[vout0];[0:a:0]anull[aout0]

**Comment by cooliobr** [comment]
Sorry, i never used like 200:-1, on 0.16 i use factor.

**Comment by jb-alvarado** [comment]
Maybe before was no validation. I can look again to the filter syntax and see if I can adjust the validation.

**Comment by jb-alvarado** [comment]
I can remove the validation, but only a scale factor is not supported by scale filter. I don't think it has work in v0.16. You can check with:

```
ffmpeg -f x11grab -y -framerate 25 -s 1280x720 -i :1.0 -vf scale=0.2 -f null -
```

**Comment by cooliobr** [comment]
"ffmpeg -hide_banner -threads 4 -hwaccel cuvid -c:v h264_cuvid
-fix_sub_duration -drop_second_field true -nostats -v level+error -i
/mnt/disco/hallo/docs/214bd5c98f0eec4602a00e5d1719e617.mp4 -filter_complex
[0:v:0]scale_npp=format=yuv420p,scale_npp=1280:720:interp_algo=super:force_original_aspect_ratio=decrease,hwdownload,pad=1280:720:(ow-iw)/2:(oh-ih)/2:color=black,setdar=16:9,setsar=1:1,hwupload[v];movie=/usr/share/ffplayout/HALLO_Doc.png[l0];[l0]format=rgba,colorchannelmixer=aa=0.7,
*scale=iw*0.07:-1*,hwupload_cuda[l];[v][l]overlay_cuda=main_w-overlay_w-50:33[vout0];[0:a:0]anull[aout0]
-map [vout0] -map [aout0] -r 29 -c:v h264_nvenc -b:v 2700k -g 30 -c:a s302m
-strict -2 -sample_fmt s16 -ar 48000 -ac 2 -f mpegts -"

i´m using this
Att.

Rafael Machado
*HALLO! Midia Group.*




Em qua., 12 de abr. de 2023 às 16:49, jb-alvarado ***@***.***>
escreveu:

**Comment by cooliobr** [comment]
> I can remove the validation, but only a scale factor is not supported by scale filter. I don't think it has work in v0.16. You can check with:
> 
> ```
> ffmpeg -f x11grab -y -framerate 25 -s 1280x720 -i :1.0 -vf scale=0.2 -f null -
> ```

` "ffmpeg -hide_banner -threads 4 -hwaccel cuvid -c:v h264_cuvid -fix_sub_duration -drop_second_field true -nostats -v level+error -i /mnt/disco/hallo/docs/214bd5c98f0eec4602a00e5d1719e617.mp4 -filter_complex [0:v:0]scale_npp=format=yuv420p,scale_npp=1280:720:interp_algo=super:force_original_aspect_ratio=decrease,hwdownload,pad=1280:720:(ow-iw)/2:(oh-ih)/2:color=black,setdar=16:9,setsar=1:1,hwupload[v];movie=/usr/share/ffplayout/HALLO_Doc.png[l0];[l0]format=rgba,colorchannelmixer=aa=0.7,scale=iw*0.07:-1,hwupload_cuda[l];[v][l]overlay_cuda=main_w-overlay_w-50:33[vout0];[0:a:0]anull[aout0] -map [vout0] -map [aout0] -r 29 -c:v h264_nvenc -b:v 2700k -g 30 -c:a s302m -strict -2 -sample_fmt s16 -ar 48000 -ac 2 -f mpegts -"
`
