### ISSUE TITLE
ffplayout can't use avi files?

### ISSUE THREAD

**Issue by jenny787** [ffplayout/ffplayout#318]
When I go to the frontend settings to add avi, I get the red box saying config error if i try to save it.  Can ffplayout read avi files?

**Comment by jb-alvarado** [comment]
Hello jenny,
this is a bug in the frontend. I will fix it and in the meantime you can edit the file `/etc/ffplayout/ffplayout.yml` and add avi to your extensions.

In general ffplayout can play every format, that is supported by ffmpeg, you only need to have in mind that not all formats are also supported by the browser. In browser you can only preview a file, that is supported by the browser.

**Comment by jenny787** [comment]
ah yes, thank you very much.  Yes I have tested avi files with the same paramters and it works.
When I add avi, i have to add it to both the extensions field, and also the regex matching field, right?

**Comment by jb-alvarado** [comment]
In v1.8.0 the frontend will be fixed.

The regex field you only need to adjust, when you want to use the file names for text overlay.
