### ISSUE TITLE
Player-frontend, "Media could not be loaded"

### ISSUE THREAD

**Issue by jenny787** [ffplayout/ffplayout#320]
The preview window is always showing "The media could not be loaded, either because the server or network failed or because the format is not supported."
The only parameters I have changed is to use folder mode instead of playlist.  I tried ffplayout a while ago, and I thought this was working then, I cannot figure it out.
![SNAG-0046](https://github.com/ffplayout/ffplayout/assets/66756955/e0e11c89-5e1f-4bd0-ae94-dbfaa07d84fc)

**Comment by jb-alvarado** [comment]
Can you show your output setting?

The preview needs a input, that you be a m3u8 playlist, or a http-flv stream.

**Comment by jenny787** [comment]
Here's my out configuration.  Maybe it doesn't work with "stream"?
![SNAG-0052](https://github.com/ffplayout/ffplayout/assets/66756955/bdc3c94f-3d98-4063-8676-dd5124a97659)

**Comment by jb-alvarado** [comment]
Ah ok, when you using the the streaming mode, you have to create a preview on the receiver side. When you can configure the rtmp server, you can create there a HLS stream, and feed them to your preview.

Maybe this helps a bit to: https://github.com/ffplayout/ffplayout/blob/master/docs/preview_stream.md

**Comment by jenny787** [comment]
I have my m3u8 hls url now, and it works on all other players, but when i place it in the Preview URL field, it still doesn't work.  Am I not understanding it?

**Comment by jb-alvarado** [comment]
So you have now a address like: `https://myexample.org/live/stream.m3u8` and this runs on players like vlc but when you put it in the preview url field, it doesn't play?

What does the browser console say? Can it be a [cors](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors) issue?
