### ISSUE TITLE
Cant stream copy audio even though correct type

### ISSUE THREAD

**Issue by sirus20x6** [ffplayout/ffplayout#324]
I'm using the storage play feature to play overtures before my stream starts.
I preconverted all the overtures to 264, aac, 44100hz.
when ffplayout starts I get the error

```
[2023-06-05 23:08:43.07969] [DEBUG] Decoder CMD: "ffmpeg -hide_banner -nostats -v level+error -i /opt/ffplayout/overtures/dances.with.wolves_converted.flv -filter_complex [0:v:0]fps=25,null[vout0];[0:a:0]anull[aout0] -map [vout0] -map [aout0] -pix_fmt yuv420p -r 25 -c:v mpeg2video -g 1 -b:v 129600k -minrate 129600k -maxrate 129600k -bufsize 64800k -c:a s302m -strict -2 -sample_fmt s16 -ar 48000 -ac 2 -f mpegts -"
[2023-06-05 23:08:43.47215] [ERROR] [Encoder] [flv @ 0x55e320400b80] FLV does not support sample rate 48000, choose from (44100, 22050, 11025)
[2023-06-05 23:08:43.47227] [ERROR] [Encoder] [flv @ 0x55e320400b80] Audio codec s302m not compatible with flv
[2023-06-05 23:08:43.47232] [ERROR] [Encoder] Could not write header for output file #0 (incorrect codec parameters ?): Function not implemented
[2023-06-05 23:08:43.47238] [ERROR] [Encoder] Error initializing output stream 0:0 -- 
[2023-06-05 23:08:43.47892] [ERROR] Encoder write error: broken pipe
[2023-06-05 23:08:43.47909] [ERROR] [Decoder] av_interleaved_write_frame(): Broken pipe
[2023-06-05 23:08:43.48107] [ERROR] [Decoder] Error writing trailer of pipe:: Broken pipe
```
my output param is:
```YAML
output_param: -c:v libx264 -x264-params keyint=25:min-keyint=15:scenecut=-1 -maxrate 6000k -bufsize 512k -preset faster -tune zerolatency -profile:v Main -level 3.1 -c:a copy -strict unofficial -f flv rtmp://localhost:1935/live/XXXXX
```
OS ubuntu 22
```
[DEBUG] Start ffplayout v0.18.0, status file path: /home/ffpu/.ffp_status
[2023-06-05 02:27:54.76947] [ INFO] Run JSON RPC server, listening on: http://127.0.0.1:7070
[2023-06-05 02:27:54.78090] [ INFO] Playout in folder mode
```
ffmpeg version 4.4.4-0ubuntu1~22.04.sav0 Copyright (c) 2000-2023 the FFmpeg developers

where does this part come from?
```
-filter_complex [0:v:0]fps=25,null[vout0];[0:a:0]anull[aout0] -map [vout0] -map [aout0] -pix_fmt yuv420p -r 25 -c:v mpeg2video -g 1 -b:v 129600k -minrate 129600k -maxrate 129600k -bufsize 64800k -c:a s302m -strict -2 -sample_fmt s16 -ar 48000 -ac 2 -f mpegts -"
```
and how do I change it? is this because of the format of the filler video?

**Comment by jb-alvarado** [comment]
Hello @sirus20x6,

> I preconverted all the overtures to 264, aac, 44100hz. when ffplayout starts I get the error
> 

For ffplayout this step is not necessary. Maybe it can make sense in output mode `hls` in combination with stream copy. But I have not test this.

> ```yaml
> output_param: -c:v libx264 -x264-params keyint=25:min-keyint=15:scenecut=-1 -maxrate 6000k -bufsize 512k -preset faster -tune zerolatency -profile:v Main -level 3.1 -c:a copy -strict unofficial -f flv rtmp://localhost:1935/live/XXXXX
> ```

ffplayout does not support this `-c:a copy` in streaming mode. You have to choice a audio codec.

> where does this part come from?

> ```
> -filter_complex [0:v:0]fps=25,null[vout0];[0:a:0]anull[aout0] -map [vout0] -map [aout0] -pix_fmt yuv420p -r 25 -c:v mpeg2video -g 1 -b:v 129600k -minrate 129600k -maxrate 129600k -bufsize 64800k -c:a s302m -strict -2 -sample_fmt s16 -ar 48000 -ac 2 -f mpegts -"
> ```
> and how do I change it? is this because of the format of the filler video?

This is a internal step and can not be changed. That is the way ffplayout works, it starts one ffmpeg process for prepare and convert all video files to the same format and pipe the output to a second ffmpeg instance for creating a endless stream with correct DTS, PTS etc.

Even when you pre-convert all you videos in the same format, it can happen that audio and video line can have different durations, and ffplayout takes care of that to.

To unify the video ffplayout apply this filters, if is needed:

-    yadif (deinterlacing)
-    pad (letterbox or pillarbox to fit aspect)
-    fps (change fps)
-    scale (fit target resolution)
-    aevalsrc (if video have no audio)
-    apad (add silence if audio duration is to short)
-    tpad (add black frames if video duration is to short)

**Comment by sirus20x6** [comment]
I'm curious as to why `-c:a copy` wouldn't be an option for preconverted streams for instance if I made sure the audio and video were the same duration and everything was the same resolution, codec, container, etc? 

The server I'm using has a really, really old xeon that has trouble keeping up with too many streams and I have a few other things on there like plex. I'd love to just have all my videos preconverted so as little processing as possible needs to be done when it comes time to stream. I'm building a new server now, but my while my download is 1.2gbps my upload is capped at 35mbps until comcast upgrades me to docsis 4.0 later this year. that makes streaming from home nonviable so I'm stuck renting a server until then.

**Comment by jb-alvarado** [comment]
I have doubts it would run with same stability. But we can test it and see how it works.

The next days I'm not able to do much, but if you want you can change the code and run some tests.

**Comment by jb-alvarado** [comment]
I added stream copy mode to my developer repo. If you still interested, would be nice if you test it and give me feedback.

**Comment by sirus20x6** [comment]
thanks a bunch! I'll try it out
