### ISSUE TITLE
Restar playout service in Docker

### ISSUE THREAD

**Issue by cooliobr** [ffplayout/ffplayout#329]
Have you ever encountered an issue like this... when I use it in Docker and click to restart the playout service, it doesn't restart, but when I'm outside Docker, it works fine.
i have try v0.17.0, v0.17.1 and v0.18.0

ffpapi log when click restart

```
[ INFO] 192.168.222.12 "POST /api/control/1/process/ HTTP/1.1" 200 7 "http://192.168.234.55:8087/player" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Safari/605.1.15" 0.000534
[ INFO] 192.168.222.12 "POST /api/control/1/process/ HTTP/1.1" 200 7 "http://192.168.234.55:8087/player" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Safari/605.1.15" 0.000457
[ INFO] 192.168.222.12 "POST /api/control/1/process/ HTTP/1.1" 200 6 "http://192.168.234.55:8087/player" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Safari/605.1.15" 0.014665
[ INFO] 192.168.222.12 "GET /api/control/1/media/current HTTP/1.1" 200 384 "http://192.168.234.55:8087/player" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Safari/605.1.15" 0.029245
[ INFO] 192.168.222.12 "POST /api/control/1/process/ HTTP/1.1" 200 6 "http://192.168.234.55:8087/player" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Safari/605.1.15" 0.037923
[ INFO] 192.168.222.12 "GET /api/control/1/media/current HTTP/1.1" 200 384 "http://192.168.234.55:8087/player" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Safari/605.1.15" 0.037440
```

**Comment by cooliobr** [comment]
> I will test tomorrow. Which docker file do you use?

I using your "from source"

**Comment by jb-alvarado** [comment]
I'm not able to reproduce this, because my docker host cannot run centos 7 with systemd enable. But I try the AlmaLinux Container and that works.

**Comment by cooliobr** [comment]
I will try Alma, if it work i will tell you


Att.

Rafael Machado
*HALLO! Midia Group.*




Em qua., 14 de jun. de 2023 às 04:10, jb-alvarado ***@***.***>
escreveu:

**Comment by cooliobr** [comment]
> I'm not able to reproduce this, because my docker host cannot run centos 7 with systemd enable. But I try the AlmaLinux Container and that works.

not working in Alma with v0.18.1, I will try older versions

**Comment by jb-alvarado** [comment]
Do you use a non Linux host system? Maybe that is the reason.

**Comment by cooliobr** [comment]
Host = Ubuntu 18.04
docker-compose file
###########################
version: '3'
services:
    alma_playout:
        privileged: true
        environment:
            - TZ=America/Sao_Paulo
            - container=docker
            - VIDEO_GID=44
        devices:
            - '/dev/dri/card0:/dev/dri/card0'
            - '/dev/dri/renderD128:/dev/dri/renderD128'
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
              #- /media/Data/hallo:/var/lib/ffplayout/tv-media/data:rw
            - /media/Data/logo:/var/lib/ffplayout/logo:rw
        ports:
            - '8787:8787'
              #image: dev6-centos:latest
        image: alma_playout
        stdin_open: true # docker run -i
        tty: true        # docker run -t

        networks:
          network:
            ipv4_address: 10.0.0.2
        deploy:
          resources:
            limits:
              cpus: "2"
              memory: '4096m'
        shm_size: '4gb'

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16
          gateway: 10.0.0.1
          #volumes:
          #/media/Data/hallo:
          #storage_opt:
          #size: '2048G'
####################

Att.

Rafael Machado
*HALLO! Midia Group.*




Em qui., 15 de jun. de 2023 às 00:33, jb-alvarado ***@***.***>
escreveu:

**Comment by cooliobr** [comment]
> Sorry @cooliobr, I have not the capacity to give support on custom compose and docker files. For me the provided examples are hard enough, because I don't use that much docker. Please try the exact way from [Readme](https://github.com/ffplayout/ffplayout/tree/master/docker).
> 
> If the provided Alma Container works, and ffmpeg from source is needed we can try to adapt to the new alma image.

yes, I follow this steps, may is version of my OS. but I will change service to run as root, it is not a problem

**Comment by jb-alvarado** [comment]
Maybe it is possible change the user when the package get installed. Depending on running inside a [container](https://unix.stackexchange.com/questions/607695/how-to-check-if-its-docker-or-host-machine-inside-bash-script) or not, it changes the user name.

**Comment by cooliobr** [comment]
If it's just for me, there's no problem. I've already set it up in the
Dockerfile.


Att.

Rafael Machado
*HALLO! Midia Group.*




Em ter., 20 de jun. de 2023 às 16:36, jb-alvarado ***@***.***>
escreveu:

**Comment by jb-alvarado** [comment]
Ah yes in the dockerfile is also a good option. Maybe other people have same problem, the is good to make a general fix.

**Comment by cooliobr** [comment]
Thanks
now I am working in scte35 to insert ad marks when playout
"play" advertisements with name BLACKOUT.
i using this https://github.com/futzu/x9k3
It is working fine, now i can integrate with google ad for video


Att.

Rafael Machado
*HALLO! Midia Group.*




Em ter., 20 de jun. de 2023 às 16:52, jb-alvarado ***@***.***>
escreveu:

**Comment by jb-alvarado** [comment]
Wow, nice that you found a solution!
