### ISSUE TITLE
0.18.2 displays "No clip is playing" while a clip is playing

### ISSUE THREAD

**Issue by ellijaymakerspace** [ffplayout/ffplayout#331]
**Describe the bug**

After upgrade from ffplayout_0.17.1_amd64.deb to ffplayout_0.18.2_amd64.deb on Ubuntu 22.04.2 LTS, webui displays "No clip is playing" at all times, even when clips are playing. The lower clock displays 00:00:00 at all times. 

**To Reproduce**

1. Upgrade from 0.17.1 to 0.18.2 
2. Start playout

**Expected behavior**

Clip name should appear in the webui under the clock. 

**Desktop/Server/Software (please complete the following information):**

- OS: Ubuntu 22.04.2 LTS
- ffplayout version: ffplayout_0.18.2_amd64
- ffmpeg version: ffmpeg version 4.4
- are you using the current master of ffplayout?: Last versioned release. 

**Config Settings:**

- No special command line arguments, just followed the installation instructions. 
- No special modifications to the config file other than updating my playout string (which is working) 

- **Logging:**
- No new log messages 

- **Note:**
-The files in question are stored on a remote fs mounted by sshfs. That didn't matter in the last version, but it might be relevant?

**Comment by jb-alvarado** [comment]
Thank you @ellijaymakerspace, looks like an package update (reqwest) broke function. I will create a new release.

**Comment by ellijaymakerspace** [comment]
Resolved. Thanks! Great software. Really appreciate your continued development. Hope my meager contributions help.

**Comment by jb-alvarado** [comment]
> Resolved. Thanks!

Good to hear!

> Hope my meager contributions help. 

Yes, that helps a lot! Thank you!
