### ISSUE TITLE
Change the background when the video is less than long.

### ISSUE THREAD

**Issue by 9rachata** [ffplayout/ffplayout#333]
If you want to fix the black image when the clip is less than Where do I need to fix it? For example, change from black to white or have text or insert another clip instead of black.

**Comment by jb-alvarado** [comment]
Do you mean, when the video line is shorter then the audio line? This has to be setted in the [tpad](https://ffmpeg.org/ffmpeg-filters.html#tpad) filter here: https://github.com/ffplayout/ffplayout/blob/d93180e04068ecac561bdd4e54798fdd8d5e462c/lib/src/filter/mod.rs#L329

**Comment by 9rachata** [comment]
> Do you mean, when the video line is shorter then the audio line? This has to be setted in the [tpad](https://ffmpeg.org/ffmpeg-filters.html#tpad) filter here:
> 
> https://github.com/ffplayout/ffplayout/blob/d93180e04068ecac561bdd4e54798fdd8d5e462c/lib/src/filter/mod.rs#L329

no
For example, I mean when the last video ends at 12:30, but the system continues to run. and will show a black screen. I want to change the black screen to something like a white screen or some other text showing or maybe another video.

**Comment by jb-alvarado** [comment]
Ah ok, for that you can set a filler clip in config: https://github.com/ffplayout/ffplayout/blob/d93180e04068ecac561bdd4e54798fdd8d5e462c/assets/ffplayout.yml#L102
