### ISSUE TITLE
how to Change port api installed via .deb

### ISSUE THREAD

**Issue by 9rachata** [ffplayout/ffplayout#334]
how to Change port api installed via .deb  ? 

 and 

has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource that calls remote api via localhost

**Comment by jb-alvarado** [comment]
Hello @9rachata, please give a bit more infos. Best is you follow this instructions: https://github.com/ffplayout/ffplayout/blob/master/CONTRIBUTING.md.
