### ISSUE TITLE
Playback controls don't work

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#339]
**Describe the bug**

Playback controls don't work

**To Reproduce**

1. Go to Frontend Player
2. Click on "next"
Note: during the installation I started the ffplayout.service daemon with the directories /var/lib/ffplayout/tv-media /var/lib/ffplayout/playlists still empty.

 - OS: Ubuntu 22.04 server
- ffplayout 18.3
- ffmpeg 4.4.2-0ubuntu0.22.04.1
- are you using the current master of ffplayout? No.

**Config Settings:**
- command line arguments: none
- config fie
[ffplayoutyml.txt](https://github.com/ffplayout/ffplayout/files/11846937/ffplayoutyml.txt)

**Logging:**

curl -X POST -H "Content-Type: application/json" -H "Authorization: xxxxxxx"     -d '{"jsonrpc": "2.0", "id":1, "method": "player", "params":{"control":"next"}}'     127.0.0.1:7070
{"jsonrpc":"2.0","result":"Move failed","id":1}

- content of: ffplayout.log
[ffplayoutlog.txt](https://github.com/ffplayout/ffplayout/files/11846927/ffplayoutlog.txt)
[ffplayout.log2023-06-22.txt](https://github.com/ffplayout/ffplayout/files/11846928/ffplayout.log2023-06-22.txt)

**Comment by jb-alvarado** [comment]
Can you try the same with this [test clips and playlist](https://github.com/ffplayout/test-clips)? Because I was not able to reproduce it. Maybe something is wrong with your playlist?

**Comment by JunioCalu** [comment]
> Can you try the same with this [test clips and playlist](https://github.com/ffplayout/test-clips)? Because I was not able to reproduce it. Maybe something is wrong with your playlist?

The playlist was generated by ffplayout itself, perhaps the only explanation is that ffplayout is not able to handle some filename in the playlist.

**Comment by JunioCalu** [comment]
> > Can you try the same with this [test clips and playlist](https://github.com/ffplayout/test-clips)? Because I was not able to reproduce it. Maybe something is wrong with your playlist?
> 
> The playlist was generated by ffplayout itself, perhaps the only explanation is that ffplayout is not able to handle some filename in the playlist. Or maybe the minimal installation of ubuntu server without graphical interface is missing some dependency, in my installation ffmpeg was not installed automatically after executing the command apt install ./ffplayout.deb

**Comment by JunioCalu** [comment]
>
>Can you try the same with this [test clips and playlist](https://github.com/ffplayout/test-clips)? Because I was not able to reproduce it. Maybe something is wrong with your playlist?
>
I tested that list you sent me, but the controls still didn't work:

![Screenshot_20230623_165737](https://github.com/ffplayout/ffplayout/assets/8952225/b1785d29-2d3b-4ba4-8bc1-7684f4c6d28f)

chrome web console debug info:

![Screenshot_20230623_165028](https://github.com/ffplayout/ffplayout/assets/8952225/7ec507d1-2344-4db8-a411-7aa8a8b76f27)

**Comment by jb-alvarado** [comment]
The console output look like a bug in the frontend. But beside this, the clips are not found by the playout, so I guess the path in the playlist are not right.
In your log file from first post was also many path issues, even with the playlist. I don't know why this is happen.

**Comment by JunioCalu** [comment]
I checked the file paths and they are now correct, the videos are displayed in the player but the "next and previous" buttons are simply stuck, and using "curl -X POST" to replace them doesn't work either. In addition, I already "turned my VPS inside out", manually installed ffplayout, opened firewall, built the latest docker version (which did not work on ubuntu), changed ubuntu for fedora and I am not managing to make this software functional for an environment of production. It's a shame, because it's probably the best opensource software of its kind right now.

**Comment by jb-alvarado** [comment]
Ok, i must apologize. Under my developer mode I can't reproduce the misbehavior, but when I install the deb package in an Ubuntu VM I can. 

In v0.19 I changed a few things, actually it's too early for a release, because not all new features are in there yet, and it's not extensively tested yet, but if the bug doesn't show up there I'll probably bring the release forward and integrate the rest in v0.20.

**Comment by JunioCalu** [comment]
> 
> Edit: looks like a general bug in HLS mode... I think I can fix it in 0.18.4

Thanks for the correction. Now it works perfectly. I have a new question to ask, I would like to know how to enable the reproduction of a playlist with less than 24 hours, doing so would make it easier to test the software. And I have an implementation suggestion, if a playlist has less than 24 hours, let it loop until it reaches the time of 24 hours, or play the playlist once and after that fill the rest of the time by playing the file filler.mp4 in a loop, until it reaches 24 hours.

Another issue out of the current context is that it is not possible to compile ffplayout using the "cargo" command in ubuntu 22.04 (it remains to test in version 23). I used the script contained in "ffplayout/scripts/build.sh" and it didn't work, maybe I'm missing some compilation dependency, I also couldn't compile the software on ubuntu 22.04 following the instructions contained in "ffplayout/ blob/master/docs/developer .md", several error messages are displayed. The manual installation documentation at "/ffplayout/blob/master/docs/install.md" also needs to be updated as it does not include the procedure (command to create the database), "ffpapi -i". And regarding the docker version of ffplayout, I don't understand the need to include systemd in the building of the container, this may be preventing the portability of a stable software installation method to other operating systems, in ubuntu 22.04 for example it is not possible to mount volumes (in the form "--volume /var/lib/ffplayout:/var/lib/ffplayout"), with this option active.

**Comment by jb-alvarado** [comment]
>  let it loop until it reaches the time of 24 hours, or play the playlist once and after that fill the rest of the time by playing the file filler.mp4 in a loop, until it reaches 24 hours.

There is a loop option, which loops a playlist infinitely, without this option the filler clip will be looped until the 24 hours are full. 

> Another issue out of the current context is that it is not possible to compile ffplayout using the "cargo" command in ubuntu 22.04 (it remains to test in version 23). I used the script contained in "ffplayout/scripts/build.sh" and it didn't work, maybe I'm missing some compilation dependency, I also couldn't compile the software on ubuntu 22.04 following the instructions contained in "ffplayout/ blob/master/docs/developer .md", several error messages are displayed.

Just install rust from https://rustup.rs/ , install `build-essential` and run `cargo build`

> And regarding the docker version of ffplayout, I don't understand the need to include systemd in the building of the container

The docker files are only examples for how to run everything in a container. The most tested and supported setup is to use ffplayout directly on a Linux system.

**Comment by JunioCalu** [comment]
> Basta instalar a ferrugem de https://rustup.rs/ , instalar `build-essential`e executar`cargo build`

I was able to compile on ubuntu 22.04 by following these steps:

Build requirements: 3GB of RAM memory

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

source "$HOME/.cargo/env"

cargo install cargo-deb

rustup target add x86_64-unknown-linux-musl

curl -sL https://deb.nodesource.com/setup_18.x -o nodesource_setup.sh

sudo apt update

sudo apt remove --purge --auto-remove -y nodejs yarn

sudo apt install -y nodejs yarn

sudo apt install musl musl-dev musl-tools build-essential pandoc

git clone "https://github.com/ffplayout/ffplayout"

cd ffplayout

rm -rv ffplayout-frontend

git clone "https://github.com/ffplayout/ffplayout-frontend"

./scripts/man_create.sh

cargo deb --target=x86_64-unknown-linux-musl -p ffplayout-api

cargo deb --target=x86_64-unknown-linux-musl -p ffplayout

**Comment by jb-alvarado** [comment]
Good that you get it!

Instead of `rm -rv ffplayout-frontend` you can also run: `git submodule update --init` and for updating the frontend: `git submodule update --remote --merge`
