### ISSUE TITLE
How to select a specific audio track

### ISSUE THREAD

**Issue by cooliobr** [ffplayout/ffplayout#348]
Is it possible to choose a specific audio track? For example, when I want to select the Portuguese track, I use`-map 0:a:m:language:por` and it will only map the audio track in Portuguese.

**Comment by jb-alvarado** [comment]
At the moment I don't think so, only if there is a filter which support this, but as long as I know there is no one.

**Comment by jb-alvarado** [comment]
Can you select the track also with an index, like `0:a:3`? If so, it should not be to difficult to integrate this feature.

**Comment by cooliobr** [comment]
yes it is possible using -map 0:m:language:spa to map spanish or -map
0:m:language:por for portuguese, it is in https://trac.ffmpeg.org/wiki/Map


Att.

Rafael Machado
*HALLO! Midia Group.*




Em qua., 26 de jul. de 2023 às 02:52, jb-alvarado ***@***.***>
escreveu:

**Comment by jb-alvarado** [comment]
It is integrated in my dev repo, if you want to give it a try, you have to set the correct [audio_track_index](https://github.com/jb-alvarado/ffplayout/blob/4b36813d053e7bbfb0acac54354a215ea2ca34c8/assets/ffplayout.yml#L72).

`-1` is for no change, `0-..` for a specific track.

**Comment by cooliobr** [comment]
I will try it.


Att.

Rafael Machado
*HALLO! Midia Group.*




Em qua., 26 de jul. de 2023 às 07:46, jb-alvarado ***@***.***>
escreveu:
