### ISSUE TITLE
Real configuration files to enable preview stream in stream mode using SRS server

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#349]
I would like to request real ffplayout and SRS config files to enable preview stream in stream mode or rtmp mode. I'd like to see a simpler setup that doesn't involve additional configuration like nginx server setup or creating virtual hosts (/etc/hosts) to make debugging easier in test environments.

For analysis purposes, I provide below the configuration files that I am using, these files are not working to activate the preview stream. For now I'm not using the ngnix server or naming hosts (/etc/hosts) . The public IP address used in the first file has been replaced with a fake IP.

OS: Ubuntu 22.04 server
ffplayout 18.4
ffmpeg 4.4.2-0ubuntu0.22.04.1
are you using the current master of ffplayout? No.

Config Settings:

ffplayout config file:

[ffplayoutyml2.txt](https://github.com/ffplayout/ffplayout/files/12017162/ffplayoutyml2.txt)

srs config file:

[srsconf.txt](https://github.com/ffplayout/ffplayout/files/12017190/srsconf.txt)

![image](https://github.com/ffplayout/ffplayout/assets/8952225/8d54e7bb-85a8-4b25-aa8c-41da844c7f52)

![image](https://github.com/ffplayout/ffplayout/assets/8952225/c344029e-8d7b-4044-8240-9613b2916689)

**Comment by jb-alvarado** [comment]
Currently the preview with a flv stream makes problem. Better use a HLS stream.

**Comment by JunioCalu** [comment]
I was able to enable HTTP-FLV (http://server:8080/live/stream.flv) using the default installation file at /opt/srs/trunk/conf/rtmp2rtc.conf. This file enables transcoding from rtmp to HTTP-FLV. But this is causing problems like you said yourself.

```
listen              1935;
max_connections     1000;
daemon              on;
pid                 /usr/local/srs/objs/srs.pid;
srs_log_tank        console; # file;
srs_log_file        /var/log/srs.log;
ff_log_dir          /tmp;
srs_log_level       error;

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

http_api {
    enabled         on;
    listen          1985;
}
stats {
    network         0;
}
rtc_server {
    enabled on;
    listen 8000; # UDP port
    # @see https://ossrs.net/lts/zh-cn/docs/v4/doc/webrtc#config-candidate
    candidate $CANDIDATE;
}

vhost __defaultVhost__ {
    rtc {
        enabled     on;
        # @see https://ossrs.net/lts/zh-cn/docs/v4/doc/webrtc#rtmp-to-rtc
        rtmp_to_rtc on;
        # @see https://ossrs.net/lts/zh-cn/docs/v4/doc/webrtc#rtc-to-rtmp
        rtc_to_rtmp on;
    }
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
}
```

**Comment by jb-alvarado** [comment]
Ok, I was able to fix the http-flv issue and I also update the **preview_stream.md**, now no hosts entry is needed any more. But I still think it is necessary to use nginx, because of cors issues.

In the next 0.19.0 release the fix will be apply.

**Comment by jb-alvarado** [comment]
Yes I agree, that WebRTC would be nice to have in preview. But until there was no easy way to integrate this. The other question is, is it really necessary?

**Comment by JunioCalu** [comment]
> Yes I agree, that WebRTC would be nice to have in preview. But until there was no easy way to integrate this. The other question is, is it really necessary?

On second thought it is not necessary, there is no justification, latency time is not something that affects the internal player.
