### ISSUE TITLE
Live stream overlay

### ISSUE THREAD

**Issue by gihan353** [ffplayout/ffplayout#352]
**Describe the bug**

*Expected Behavior:*
When starting a live stream, the currently playing schedule should overlay on the screen, and the live stream should start playing seamlessly.

*Actual Behavior:*
Currently, when starting a live stream, the currently playing schedule does not overlay, and the live stream does not start playing as expected.

Any assistance in resolving this issue would be greatly appreciated!

**Comment by JunioCalu** [comment]
> _Expected Behavior:_ When starting a live stream, the currently playing schedule should overlay on the screen, and the live stream should start playing seamlessly.

What is the difference between overlay and switching?

Maybe the tip below is useful or not in your case, it was in the ffplayout documentation but I didn't pay attention at first.

It does not work:
"-f live_flv -listen 1 -i rtmp://127.0.0.1:1936/live/stream"

It works:
"-f live_flv -listen 1 -i rtmp://0.0.0.0:1936/live/stream"
