### ISSUE TITLE
ffplayout's built-in player: HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://213.100.134.83:8787/live/stream.m3u8'. This request has been blocked; the content must be served over HTTPS.

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#355]
Describe the bug

ffplayout internal player is blocked by web browsers (chrome, firefox, edge) when served by an nginx reverse proxy.

To Reproduce

configure a reverse proxy like nginx.

Desktop/Server/Software (please complete the following information):

OS: Ubuntu 22.04 server
ffplayout 18.4
ffmpeg 4.4.2-0ubuntu0.22.04.1
are you using the current master of ffplayout? No.

Config Settings:
Default settings

command line arguments
Default arguments

Web Browser Logging:

media.96792ce1.js:10 Mixed Content: The page at 'https://xadfej.bntv.site/player' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://213.100.134.83:8787/live/stream.m3u8'. This request has been blocked; the content must be served over HTTPS.

media.96792ce1.js:34 VIDEOJS: WARN: videojs.mergeOptions is deprecated and will be removed in 9.0; please use videojs.obj.merge 

[media.96792ce1.js:34 VIDEOJS: ERROR: (CODE:2 MEDIA_ERR_NETWORK) HLS playlist request error at URL: http://213.100.134.83:8787/live/stream.m3u8. Re {code: 2, status: 0, message: 'HLS playlist request error at URL: http://213.100.134.83:8787/live/stream.m3u8.', responseText: ''}](media.96792ce1.js:34 VIDEOJS: ERROR: (CODE:2 MEDIA_ERR_NETWORK) HLS playlist request error at URL: http://213.100.134.83:8787/live/stream.m3u8.)

**Logging:**

![image](https://github.com/ffplayout/ffplayout/assets/8952225/ea9b49a4-8b4d-4f92-a009-35dc140fbe6d)

**Comment by jb-alvarado** [comment]
I will answer here both issues, because they are related.

First, the mixing of the protocols: that is not an error, and has to be fixed from user side. In this times the browsers are very strickt and you have to use a consistent setup. Use https everywhere and you will be fine.

About the cors issue, is a bit the same. In theory there is ways to fix this on ffplayout side with [cors](https://docs.rs/actix-cors/latest/actix_cors/) module. But in my opinion this makes not much sense.

I strongly recommend to use a proxy, like nginx. With that you can setup all your routes, use https and also serve your HLS stream to your audience.

**Comment by JunioCalu** [comment]
> I strongly recommend to use a proxy, like nginx. With that you can setup all your routes, use https and also serve your HLS stream to your audience.

yes, I described above that this problem is happening in nginx, because I configured a route to ffplayout, and it gave the error output described above. I think it's a problem related to ffplayout's web implementation logic, which follows the same logic as the "cors" problem, because I have other configured application routes that don't have this problem. Below I leave the configuration that I used in nginx and that generates the error described in this discussion.

```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name ffplayout.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {

        set $upstream_app 127.0.0.1;
        set $upstream_port 8787;
        set $upstream_proto http;
        proxy_http_version 1.1;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
        proxy_redirect off;
    }
}
```

**Comment by jb-alvarado** [comment]
When you setup nginx correctly the problem will disappear.

The best is to add the path to your HLS output folder too to the config, like:

```

location /live/ {
    alias /usr/share/ffplayout/public/live/;
}
```

And then use your url which are served by nginx everywhere, also as preview_url, without any port, like: **https://example.org/live/stream.m3u8**

**Comment by JunioCalu** [comment]
> ```
> 
> location /live/ {
>     alias /usr/share/ffplayout/public/live/;
> }
> ```

it works, but for some reason the internal player starts to crash, it stops working and the web page needs to be reloaded to get it working again.

**Comment by jb-alvarado** [comment]
Any error message?

**Comment by JunioCalu** [comment]
> Any error message?

I think it was a hardware performance problem, I changed hardware and the problem disappeared, I can't reproduce it now.
