### ISSUE TITLE
[Question] Advertisement marker

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#361]
What is the function of the advertisement marker? What does it change in the video image or playback?

**Comment by jb-alvarado** [comment]
Sorry, can you explain a bit your question? I don't understand it :-).

**Comment by JunioCalu** [comment]
I refer to this function below, what does it do?

![IMG-20230726-WA0003](https://github.com/ffplayout/ffplayout/assets/8952225/711f9a5f-34f7-4dcb-a046-e4bcf13ad0fc)

**Comment by jb-alvarado** [comment]
Ah ok, basically it marks only a video as an advertisement, and when this video plays the logo is faded out. When a normal video comes in then the logo fades in again.
