### ISSUE TITLE
Incorrect IP (127.0.0.1) parameter in default live stream ingest configuration

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#363]
For remote live stream ingest to work correctly, it is necessary to change the default IP (127.0.0.1:1936) parameter of the default configuration file to 0.0.0.0:1936.

`-f live_flv -listen 1 -i rtmp://0.0.0.0:1936/live/stream`

**Comment by cooliobr** [comment]
Acredito que o ip está correto, vocÊ que tem que mudar de acordo com as necessidades de sua rede

**Comment by JunioCalu** [comment]
> Acredito que o ip está correto, vocÊ que tem que mudar de acordo com as necessidades de sua rede

Você consegue acessar de fora da sua rede com o 127.0.0.1 configurado? Eu só consigo com o 0.0.0.0, mesmo com firewall desativado.

**Comment by cooliobr** [comment]
como falei, isso vai depender da tua forma de uso, não é um problema.


Att.

Rafael Machado
*HALLO! Midia Group.*




Em qui., 27 de jul. de 2023 às 15:03, Junio Calú ***@***.***>
escreveu:

**Comment by JunioCalu** [comment]
> como falei, isso vai depender da tua forma de uso, não é um problema.

É um ponto de vista.

**Comment by jb-alvarado** [comment]
I would prefer to leave it at 127.0.0.1. You can set it to 0.0.0.0 and I use that in our setup, but I want the user to know what he is doing and change it wisely. Using 0.0.0.0 can be a potential security hole, also you may not want to listen on all interfaces, but only on a specific one.

**Comment by JunioCalu** [comment]
> I would prefer to leave it at 127.0.0.1. You can set it to 0.0.0.0 and I use that in our setup, but I want the user to know what he is doing and change it wisely. Using 0.0.0.0 can be a potential security hole, also you may not want to listen on all interfaces, but only on a specific one.

Got it, could you add a warning on the configuration page?  such as "replace the local IP address parameter with the público IP of your host if you want to access externally" and a complement such as "create an access key strong enough to avoid security risks".

**Comment by JunioCalu** [comment]
> 

It might also be useful to add a button on the ingest configuration page to automatically generate a strong random access stream key.  And a checkbox to choose the IP to be used.
