### ISSUE TITLE
Add Json APi to Graphic messages

### ISSUE THREAD

**Issue by brixxnatt** [ffplayout/ffplayout#364]
Add Json Api feed to read feed from json api url direct , for messages , scrollers .  etc

**Comment by IVEN2022** [comment]
+1

**Comment by jb-alvarado** [comment]
Hi @brixxnatt, I would kindly ask you to read the [contributing](https://github.com/ffplayout/ffplayout/blob/master/CONTRIBUTING.md) rule again and adjust your issue. I don't know exactly what you want.

Please adjust your other issues as well.

**Comment by brixxnatt** [comment]
I am sorry for the mess , I didnt not wanted to report a bug

**Comment by IVEN2022** [comment]
I guess he meant the for example if the scroller can be looped all the time , the data text inside the scroller can be set to get json api data from URL  refresh data every 5000 ms to be set ,

**Comment by jb-alvarado** [comment]
When I understand this, this would be some how redundant, because the engine already supports controlling over http requests, see [json-rpc](https://github.com/ffplayout/ffplayout#json-rpc).

So it is very easy with a little bit of scripting and cronjob to send new messages to ffplayout.
