### ISSUE TITLE
Ability to add XAML graphic 

### ISSUE THREAD

**Issue by brixxnatt** [ffplayout/ffplayout#365]
Ability to use XAML graphics

**Comment by jb-alvarado** [comment]
Hello @brixxnatt, same goes here, what I wrote in the other issue :-). But if this XAML is something like an image format, ffplayout only supports [formats](https://ffmpeg.org/ffmpeg-formats.html) that are supported by ffmpeg.

**Comment by brixxnatt** [comment]
XAML is a script based graphics with Storyboard in and out

**Comment by IVEN2022** [comment]
i guess XAML graphic scripts might work with ffplayout , no idea , i hope so

**Comment by jb-alvarado** [comment]
So it is the same then svg? ffmpeg can support svg with extra lib: https://stackoverflow.com/questions/48216871/ffmpeg-support-for-svg-rasterization When you found the same for XAML and you compile your ffmpeg with that lib, then maybe you can use it in ffplayout. But this is not directly an ffplayout issue.

**Comment by IVEN2022** [comment]
Well i am not a dev , no idea to comply things , I hope you work more options on the graphics"message section" to include photos , lower third animation , API json data from url , overlay graphics maybe , etc.  enable RTL

**Comment by jb-alvarado** [comment]
No sorry, the chance goes almost to zero that I will work on that. The goal from ffplayout is to create a simple internet TV, not a mixer with many features.

You can read in the docs about custom filters, some things are possible with that. But changing graphics dynamically is technically not possible.

If you need this things caspercg or OBS is better in that.
