### ISSUE TITLE
Preview and streaming to facebook

### ISSUE THREAD

**Issue by IVEN2022** [ffplayout/ffplayout#370]
PLease add paypal donation  , thank you

**Comment by IVEN2022** [comment]
Hello , PLease not to the script , add paypal donation option to this project so we can contribute , thank you

**Comment by jb-alvarado** [comment]
Hello @IVEN2022, thank you for your willingness to support this project! I add a link, you should see it on the right side under github sponsor link.

**Comment by IVEN2022** [comment]
@jb-alvarado 
thank you my friend , already send via paypal , than you for the best solution ever , 3 quick questions if i may ask , as there is lot of installations invloved ,  1 - link to the page where i can follow installation to make the preview work please , 
2- I test streaming to facebook , it works but from time to time it jitter or fasten the video on facebook when i press anything in the payout web interface  -  3 - coud not find the settings regarding resolution 720 for facebook or youtube , this is my config

__________
        -c:v:0 libx264        -crf 23        -x264-params keyint=50:min-keyint=25:scenecut=-1        -maxrate:0 1300k        -bufsize:0 2600k        -preset faster        -tune zerolatency        -profile:v Main        -level 3.1        -c:a:0 aac        -ar:0 44100        -b:a:0 128k        -flags +global_header        -f flv   youtube or facebook rtmp ink

___________

if i want to stream to my website i try to use the  http://ip:8787/live/stream.m3u8 , but nothing is showing , please point me to the page of fix or setup


thank youuuu

**Comment by IVEN2022** [comment]
I hope you respond soon

**Comment by IVEN2022** [comment]
![image](https://github.com/ffplayout/ffplayout/assets/111779768/4a7ca65f-81d5-433f-b959-2f3be7960b84)

**Comment by jb-alvarado** [comment]
Looks good. Does this only happen when you click next, previous, or reset? On this functions it can happen, that the playing behaviour is a bit unsmooth. They should only be used when is really necessary ones a while, and not like by a normal music/video player.

**Comment by IVEN2022** [comment]
no its happening even if i dont press anything  , vps is 4 cpu 8 gb rams , i really cant fix the corner preview  , what is you solution as you are the developer of this , thanks

**Comment by jb-alvarado** [comment]
I stream to SRS, create there my HLS multi resolution for a web tv page. The lowest resolution I use for the preview. In the past I created in SRS also forward streams to YouTube, but that I do different now.

**Comment by IVEN2022** [comment]
i used this  https://github.com/ffplayout/ffplayout/blob/master/docs/preview_stream.md
but seams not to work

**Comment by jb-alvarado** [comment]
At which point do you hang?

When you have setup SRS correctly, you can configure it like:

```NGINX
listen              1935;
max_connections     200;
daemon              on;
pid                 /usr/local/srs/objs/srs.pid;
srs_log_tank        console; # file;
srs_log_file        /var/log/srs.log;
ff_log_dir          /dev/null;

# can be: verbose, info, trace, warn, error
srs_log_level       info;

stats {
    network         0;
    disk            sda vda xvda xvdb;
}

vhost __defaultVhost__ {
    enabled             on;

    play {
        time_jitter     full;
        mix_correct     on;
    }

    publish {
        normal_timeout      30000;
    }

    transcode live/stream {
        enabled     on;
        ffmpeg      /usr/local/bin/ffmpeg;

        # use what ever you want to here
        engine youtube {
            enabled         off;
            iformat         live_flv;
            vfilter {
                v           error;
            }

            vcodec          copy;
            acodec          copy;
            oformat         flv;
            output          rtmp://a.rtmp.youtube.com/live2/<your destination>;
        }
    }

    # use this for your preview
    hls {
        enabled         on;
        hls_path        /var/www/srs;
        hls_fragment    6;
        hls_window      1800;
        hls_cleanup     on;
        hls_dispose     0;
        hls_m3u8_file   live/stream.m3u8;
        hls_ts_file     live/stream-[seq].ts;
    }
}
```

Then set ffplayout stream output to something like:

```YAML
    -c:v libx264
    -crf 23
    -x264-params keyint=50:min-keyint=25:scenecut=-1
    -preset ultrafast
    -tune zerolatency
    -profile:v Main
    -level 3.1
    -c:a aac
    -ar 44100
    -b:a 128k
    -flags +global_header
    -f flv rtmp://127.0.0.1/live/stream
```

nginx should have then the location from the hls output:

```
location /live/ {
    alias /var/www/srs/live/;
}
```

And finally you can use set your path in Frontend: `http://[domain or IP]/live/stream.m3u8`

**Comment by IVEN2022** [comment]
PLease PLease can you do a simple video to demonstrate who you approch this , nothing is working for this solution
thanks

**Comment by jb-alvarado** [comment]
Sorry, at the moment I really have no time for that. Why you not trying step by step, and when you hang somewhere you tell it here and we see how to fix that step.

If you hang on installing SRS, use the [docker](https://ossrs.io/lts/en-us/docs/v4/doc/getting-started) version, but with your one config.

**Comment by IVEN2022** [comment]
I hang on the IPs here in this script , is it my server IP or it has to be 127.0.0.1 ?

**Comment by jb-alvarado** [comment]
All internal communication can go over 127.0.0.1. So when you have install nginx, srs and ffplayout on the same machine, they all can use 127.0.0.1. Only when you have to access from "outside" you need the server IP or domain name. If it is possible use an domain name for reaching the ffplayout frontend and use it also for the preview stream config.
