### ISSUE TITLE
PLease Please I need the Corner Preview screen to work , 

### ISSUE THREAD

**Issue by IVEN2022** [ffplayout/ffplayout#372]
PLease PLease I need the Corner preview to work , please need full instruction as step by step to make it work , 
I tied the https://github.com/ffplayout/ffplayout/blob/master/docs/preview_stream.md
not working

thanks

**Comment by jb-alvarado** [comment]
Please don't open multiple issues with the same topic and please also note the [contributing](https://github.com/ffplayout/ffplayout/blob/master/CONTRIBUTING.md) guide line.

Normally I do my best to answer, but I'm not 24/7 available ;-). And now by us starts also the vacation time, what means that I will spent more time with my family.
