### ISSUE TITLE
Configuration parameters are not applied when the configuration file of a second channel is changed

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#380]
Unable to change configuration parameters of video resolution (width and height), logo_opacity, rpc_server authorization, enable ingest server, and possibly other configuration fields when a new channel is created.

OS: ubuntu server 22.04.
ffplayout: 0.19.0.

No error log is displayed when configuration fields are modified, except for the "authorization:" field of the "rpc_server:" session:
[2023-08-05 06:05:52.40889] [ERROR] RPC: Unauthorized

**Comment by JunioCalu** [comment]
I have now noticed that the problem is resolved when the new systemd daemon created along with the new channel is restarted after making changes to the config file. Each new channel created is associated with a new systemd daemon, for example "ffplayout@channel002.service", but I was restarting the primary channel daemon "ffplayout.service".

**Comment by jb-alvarado** [comment]
That is good to know. Then with the new restart modal dialogue it should be ok. Also the authorization config field.

**Comment by JunioCalu** [comment]
> That is good to know. Then with the new restart modal dialogue it should be ok. Also the authorization config field.

Congratulations on the work the software is getting more and more robust
