### ISSUE TITLE
Video playback of a second channel freezes after certain time.

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#387]
Video playback of a second channel freezes after certain time.

OS: ubuntu server 22.04.
ffplayout: 0.19.0.

Log file (multi-day run merge):
[channel2.log](https://github.com/ffplayout/ffplayout/files/12287874/channel2.log)

**Comment by JunioCalu** [comment]
Apparently, the error is related to the lack of “parses” enabled in the ffmpeg package in the standard Ubuntu repositories. Rebuilding ffmepg by adding the options below to the "debian/rules" build file of the ffmpeg source package resolves the issue.

```
    --enable-parser=h264 \
    --enable-parser=aac \
```

sources:
https://trac.ffmpeg.org/ticket/5367
https://superuser.com/questions/1622300/ffmpeg-transcoding-failing-on-cur-dts-is-invalid

Rebuilding steps:
```
sudo apt-get update
sudo apt-get install dpkg-dev build-essential devscripts
sudo apt-get build-dep ffmpeg
sudo apt-get source ffmpeg
# add --enable-parser=h264 and --enable-parser=aac to debian/rules
vim /home/user/ffmpeg-0+git20230808~ubuntu22.04.1/debian/rules
dch -i
cd ..
dpkg-buildpackage -us -uc
```

**Comment by jb-alvarado** [comment]
Hello @JunioCalu, does this issue still exists?

**Comment by JunioCalu** [comment]
> Hello @JunioCalu, does this issue still exists?

I'll need some more time to check this. From now until the end of the month, I'll see if it's still happening.
