### ISSUE TITLE
ingest problem .  HELP

### ISSUE THREAD

**Issue by brixxnatt** [ffplayout/ffplayout#398]
Hello , when i try to use the ingest , i keep cutting , the server cpu is perfect  , the stream is stable , it keep switching between playlist and live as it is cutting , here is also a log

PLease Investigate 

```
[2023-10-05 11:33:46.13927] [DEBUG] Validation done...
[2023-10-05 11:34:00.12466] [ INFO] Switch from playlist to live ingest
[2023-10-05 11:34:18.03982] [ERROR] [Server] [hls muxer @ 0x55cb88de8bc0] failed to delete old segment /usr/share/ffplayout/public/live/stream-4308.ts: No such file or directory
[2023-10-05 11:34:26.29036] [ERROR] [Server] [hls muxer @ 0x55cb88de8bc0] failed to delete old segment /usr/share/ffplayout/public/live/stream-4309.ts: No such file or directory
[2023-10-05 11:34:37.09722] [ERROR] [Server] [hls muxer @ 0x55cb88de8bc0] failed to delete old segment /usr/share/ffplayout/public/live/stream-4310.ts: No such file or directory
[2023-10-05 11:34:45.14641] [ERROR] [Server] [hls muxer @ 0x55cb88de8bc0] failed to delete old segment /usr/share/ffplayout/public/live/stream-4311.ts: No such file or directory
[2023-10-05 11:34:54.78862] [ERROR] [Server] [hls muxer @ 0x55cb88de8bc0] failed to delete old segment /usr/share/ffplayout/public/live/stream-4312.ts: No such file or directory
[2023-10-05 11:35:03.42186] [ERROR] [Server] [hls muxer @ 0x55cb88de8bc0] failed to delete old segment /usr/share/ffplayout/public/live/stream-4313.ts: No such file or directory
[2023-10-05 11:35:11.73624] [ERROR] [Server] [hls muxer @ 0x55cb88de8bc0] failed to delete old segment /usr/share/ffplayout/public/live/stream-4314.ts: No such file or directory
[2023-10-05 11:35:20.88050] [ERROR] [Server] [hls muxer @ 0x55cb88de8bc0] failed to delete old segment /usr/share/ffplayout/public/live/stream-4315.ts: No such file or directory
```

**Comment by jb-alvarado** [comment]
Hello @brixxnatt, the log is not complete and the messages it show are not good, but should not case the error. I also don't have you output settings, that makes it more difficult to say what is happen here.

But it looks like, you are using the HLS mode, I would only recommend this mode, on low CPU/RAM machines. If you have enough from both, better use the streaming mode, this is more stable an better tested. In stream mode you can stream to a rtmp target and create there your HLS stream, or you can create it also with ffplayout, like:

```YAML
out:
    mode: stream
    output_param: >-
        -filter_complex [0:v]split=3[v1_out][v2][v3];[v2]scale=w=854:h=480[v2_out];[v3]scale=w=426:h=240[v3_out];[0:a]asplit=3[a1][a2][a3]
        -map [v1_out]
        -map [a1]
        -c:v libx264
        -crf:v 23
        -x264-params keyint=50:min-keyint=25:scenecut=-1
        -preset:v fast
        -tune:v zerolatency
        -c:a libfdk_aac
        -ar 44100
        -maxrate:v:0 2400k
        -bufsize:v:0 3200k
        -b:a:0 128k
        -map [v2_out]
        -map [a2]
        -maxrate:v:1 1200k
        -bufsize:v:1 2400k
        -b:a:1 128k
        -map [v3_out]
        -map [a3]
        -maxrate:v:2 400k
        -bufsize:v:2 800k
        -b:a:2 64k
        -f hls
        -hls_time 6
        -hls_list_size 600
        -hls_flags append_list+delete_segments+omit_endlist
        -hls_segment_filename /var/www/srs/live/%v-%d.ts -master_pl_name master.m3u8
        -var_stream_map "v:0,a:0,name:720p v:1,a:1,name:480p v:2,a:2,name:240p"
        /var/www/srs/live/%v.m3u8
``` 
This example is only for you go get an idea.

Personally, I would also recommend using a RAM disk to write to, but I would not argue about it.

**Comment by brixxnatt** [comment]
why you are so good , thank you so much , it worked  thank you

**Comment by JunioCalu** [comment]
> Hello , when i try to use the ingest , i keep cutting , the server cpu is perfect , the stream is stable , it keep switching between playlist and live as it is cutting , here is also a log
> 
> PLease Investigate
> 
> ```
> [2023-10-05 11:33:46.13927] [DEBUG] Validation done...
> [2023-10-05 11:34:00.12466] [ INFO] Switch from playlist to live ingest
> [2023-10-05 11:34:18.03982] [ERROR] [Server] [hls muxer @ 0x55cb88de8bc0] failed to delete old segment /usr/share/ffplayout/public/live/stream-4308.ts: No such file or directory
> [2023-10-05 11:34:26.29036] [ERROR] [Server] [hls muxer @ 0x55cb88de8bc0] failed to delete old segment /usr/share/ffplayout/public/live/stream-4309.ts: No such file or directory
> [2023-10-05 11:34:37.09722] [ERROR] [Server] [hls muxer @ 0x55cb88de8bc0] failed to delete old segment /usr/share/ffplayout/public/live/stream-4310.ts: No such file or directory
> [2023-10-05 11:34:45.14641] [ERROR] [Server] [hls muxer @ 0x55cb88de8bc0] failed to delete old segment /usr/share/ffplayout/public/live/stream-4311.ts: No such file or directory
> [2023-10-05 11:34:54.78862] [ERROR] [Server] [hls muxer @ 0x55cb88de8bc0] failed to delete old segment /usr/share/ffplayout/public/live/stream-4312.ts: No such file or directory
> [2023-10-05 11:35:03.42186] [ERROR] [Server] [hls muxer @ 0x55cb88de8bc0] failed to delete old segment /usr/share/ffplayout/public/live/stream-4313.ts: No such file or directory
> [2023-10-05 11:35:11.73624] [ERROR] [Server] [hls muxer @ 0x55cb88de8bc0] failed to delete old segment /usr/share/ffplayout/public/live/stream-4314.ts: No such file or directory
> [2023-10-05 11:35:20.88050] [ERROR] [Server] [hls muxer @ 0x55cb88de8bc0] failed to delete old segment /usr/share/ffplayout/public/live/stream-4315.ts: No such file or directory
> ```

In my case the error Apparently is related to the lack of “parses” enabled in the ffmpeg package in the standard Ubuntu repositories. Rebuilding ffmepg by adding the options below to the "debian/rules" build file of the ffmpeg source package resolves the issue.

```
    --enable-parser=h264 \
    --enable-parser=aac \
```

sources:
https://trac.ffmpeg.org/ticket/5367
https://superuser.com/questions/1622300/ffmpeg-transcoding-failing-on-cur-dts-is-invalid

Rebuilding steps:
```
#For Ubuntu 22.04. In /etc/apt/sources.list insert the text below
deb-src http://archive.ubuntu.com/ubuntu jammy main restricted universe multiverse

sudo apt-get update
sudo apt-get install dpkg-dev build-essential devscripts
sudo apt-get build-dep ffmpeg
sudo apt-get source ffmpeg
# add --enable-parser=h264 and --enable-parser=aac to debian/rules
vim /home/user/ffmpeg-0+git20230808~ubuntu22.04.1/debian/rules
dch -i
cd ..
dpkg-buildpackage -us -uc
```
