### ISSUE TITLE
Creation of a dashboard for monitoring CPU resources and HD space

### ISSUE THREAD

**Issue by jb-alvarado** [ffplayout/ffplayout#415]
### Discussed in https://github.com/ffplayout/ffplayout/discussions/385

<div type='discussions-op-text'>

<sup>Originally posted by **JunioCalu** August  8, 2023</sup>
For large volumes of work, monitoring these resources is essential.</div>

[Rust sysinfo](https://github.com/GuillaumeGomez/sysinfo) could be an option.

**Comment by brixxnatt** [comment]
i am using Htop , but to this to be in the player page on the top header will be amazing

**Comment by brixxnatt** [comment]
I hope this is coming after beta  , and i hope it will be on top of player page , CPU  , RAM , Storage Etc.  with percentage %
