### ISSUE TITLE
How to send RTMP to SAT (Satellite TV)

### ISSUE THREAD

**Issue by nscpro** [ffplayout/ffplayout#426]
Anyone know how to send FFplayout stream to satellite?

**Comment by jb-alvarado** [comment]
Sorry I have now idea. If you found a solution based on ffmpeg, you could apply that same settings to ffplayout.

**Comment by cooliobr** [comment]
you need to sent stream to mux, and mux send it to satellite.
i don't know if any mux support RTMP, only SRT or UDP(multicast)

**Comment by ruelmateo** [comment]
You need to contact a Satellite TV provider if they support to receive SRT/RTMP/UDP. Then customize the output settings on it.
