### ISSUE TITLE
Bugs in ffplayout version 0.20.0-beta4

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#439]
**Describe the bug**

- The directories "public" and "live," located in the path "/usr/share/ffplayout/public/live/," are not created during the Debian package installation.

> ```
> [2023-11-06 17:56:13.04038] [ERROR] [Decoder] [hls @ 0x561b12813a80] Failed to open file '/usr/share/ffplayout/public/live/stream-0.ts'
> [2023-11-06 17:56:13.04054] [ERROR] [Decoder] [hls @ 0x561b12813a80] failed to rename file /usr/share/ffplayout/public/live/stream.m3u8.tmp to /usr/share/ffplayout/public/live/stream.m3u8: No such file or directory
> ```

- I theorize that the integration of static pages into ffpapi has led to instability in the ffplayout's embedded HTTP server. It appears that if ffpapi is interrupted for any reason, the ffplayout HTML pages cease to function. Additionally, even when ffpapi seems to be operating without interruptions, the ffplayout HTML pages are taken down when they are reloaded, either voluntarily or involuntarily, in the web browser. As shown in the image below:

- ![Screenshot_20231106_175845](https://github.com/ffplayout/ffplayout/assets/8952225/db205d99-3a30-494c-952a-bd4d86b332f0)

**Desktop/Server/Software (please complete the following information):**

OS: ubuntu server 22.04
ffplayout: 0.20.0-beta4
ffmpeg: 6.0

- are you using the current master of ffplayout? Yes

**Config Settings:**

- command line arguments: default
- config fie: [ffplayout.yml.txt](https://github.com/ffplayout/ffplayout/files/13272639/ffplayout.yml.txt)

**Logging:**

- content of: [ffplayout.log](https://github.com/ffplayout/ffplayout/files/13272455/ffplayout.log)

**Comment by JunioCalu** [comment]
- The built-in player does not work in version 0.20.0-beta4. Unable to load http://localhost:8787/live/stream.m3u8:

![image](https://github.com/ffplayout/ffplayout/assets/8952225/d2b2205e-5855-4c1e-b8a8-95c88fa96991)

**Comment by jb-alvarado** [comment]
Thanks for the hint! Yes this issues are related to the embedding of static files. Will be fixed soon.
