### ISSUE TITLE
[Enhancement] Drag-and-Drop Function for Moving Files (or Folders) Between Directories

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#440]
- Bringing the "player" and "media" pages closer to the functionality of a file manager would ease the organization of large volumes of files, as is typical in extensive programming that undergoes multiple changes over the course of weeks and months.

https://github.com/ffplayout/ffplayout/assets/8952225/56dc2ea6-6924-423b-90cc-e33cd5d66e6c

OS: ubuntu server 22.04
ffplayout: 0.20.0-beta4
ffmpeg: 6.0

- are you using the current master of ffplayout? Yes

**Comment by JunioCalu** [comment]
Hi @jb-alvarado, is there any estimate for this implementation?

**Comment by jb-alvarado** [comment]
I can imaging to integrate this on media page, but not on player page. But at the moment I have no time range. Pull requests are welcome. Most work is here in frontend side, so should not be to difficult.

**Comment by JunioCalu** [comment]
It really shouldn't be too difficult; I would take a look, even though my web programming skills are not the best.

**Comment by JunioCalu** [comment]
Thank you very much @jb-alvarado!
