### ISSUE TITLE
Uploading files causes the transmission to drop

### ISSUE THREAD

**Issue by LuizStSantos** [ffplayout/ffplayout#444]
Uploading files is causing the transmission to drop, I upload a file and it normally starts in the second, causing the transmission to drop I uploaded 4 files together each measuring 1 GB

OS: Ubuntu Server 22.04.3 LTS
ffplayout version 0.20.0-beta5
ffmpeg version 6.0

=================================================
```
[2023-11-08 10:00:45.74942] [ INFO] Playout done...
[2023-11-08 10:00:50.25638] [DEBUG] Start ffplayout v0.20.0-beta5, status file path: /home/ffpu/.ffp_status
[2023-11-08 10:00:50.25686] [DEBUG] Use config: /etc/ffplayout/ffplayout.yml
[2023-11-08 10:00:50.25690] [ INFO] RPC server listening on 127.0.0.1:7070
[2023-11-08 10:00:50.25901] [ INFO] Playout in playlist mode
[2023-11-08 10:00:50.26993] [ INFO] Read Playlist: /var/lib/ffplayout/playlists/2023/11/2023-11-08.json
[2023-11-08 10:00:50.27014] [DEBUG] Validate playlist from: 2023-11-08
[2023-11-08 10:00:50.27393] [DEBUG] Encoder CMD: "ffmpeg -hide_banner -nostats -v level+error -re -i pipe:0 -filter_complex [0:v:0]zmq=b=tcp\\://'127.0.0.1\:46625',drawtext@dyntext=text='':fontfile='/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'[vout0] -map [vout0] -map 0:a:0 -c:v:0 libx264 -crf 23 -x264-params keyint=50:min-keyint=25:scenecut=-1 -maxrate:0 1300k -bufsize:0 2600k -preset faster -tune zerolatency -profile:v Main -level 3.1 -c:a:0 aac -ar:0 44100 -b:a:0 128k -flags +global_header -f flv rtmp://192.168.1.12:1935/stream/23b3b3b7-2a78-4269-afdd-8dbffc38c574.stream?token=canalsolofertil"
[2023-11-08 10:00:50.27560] [DEBUG] Playlist init
```
==================================================

![Captura de tela 2023-11-08 095113](https://github.com/ffplayout/ffplayout/assets/73047610/cf8ee6bd-ee30-4cdb-84af-78393d047bf2)
![Captura de tela 2023-11-08 095126](https://github.com/ffplayout/ffplayout/assets/73047610/3746a524-0273-4c51-9d65-eaa90e70f9a5)

**Comment by JunioCalu** [comment]
Do your hardware configurations meet the system requirements?

**Comment by JunioCalu** [comment]
> Uploading files is causing the transmission to drop, I upload a file and it normally starts in the second, causing the transmission to drop I uploaded 4 files together each measuring 1 GB

Do your hardware configurations meet the system requirements?

**Comment by LuizStSantos** [comment]
> > Uploading files is causing the transmission to drop, I upload a file and it normally starts in the second, causing the transmission to drop I uploaded 4 files together each measuring 1 GB
> 
> Do your hardware configurations meet the system requirements?

The ffplayout is on an i7 8700, 32GB RAM and a GTX 1660 TI, while the stream server is on a DELL PowerEdge T110 II, both with Ubuntu Server

**Comment by JunioCalu** [comment]
> The ffplayout is on an i7 8700, 32GB RAM and a GTX 1660 TI, while the stream server is on a DELL PowerEdge T110 II, both with Ubuntu Server

You will need to perform more detailed debugging. Check the web console, journalctl, and the complete ffplayout log. If necessary, use tools like rust-gdb, rr, strace, and ltrace to diagnose issues.

**Comment by JunioCalu** [comment]
> The ffplayout is on an i7 8700, 32GB RAM and a GTX 1660 TI, while the stream server is on a DELL PowerEdge T110 II, both with Ubuntu Server

You will need to perform more detailed debugging. Check the web console, journalctl, and the complete ffplayout log. If necessary, use tools like rust-gdb, rr, strace, and ltrace to diagnose issues.


tutorials:
https://blog.logrocket.com/debugging-rust-apps-with-gdb/
https://bitshifter.github.io/rr+rust/index.html#1

**Comment by JunioCalu** [comment]
> > >  

No relevant information, you'll have to delve deeper.

**Comment by jb-alvarado** [comment]
Do you mean that the upload affects the transmission of the HLS stream? That is interesting because both processes run independently of each other. 
I suspect that it is a network problem. You could find out by limiting the bandwidth for the upload. You can do this in Firefox in the [Dev Tools](https://firefox-source-docs.mozilla.org/devtools-user/network_monitor/throttling/index.html), for example.

**Comment by LuizStSantos** [comment]
> Do you mean that the upload affects the transmission of the HLS stream? That is interesting because both processes run independently of each other. I suspect that it is a network problem. You could find out by limiting the bandwidth for the upload. You can do this in Firefox in the [Dev Tools](https://firefox-source-docs.mozilla.org/devtools-user/network_monitor/throttling/index.html), for example.

I tested it on Firefox with the WiFi connection and the transmission still dropped

**Comment by JunioCalu** [comment]
> I tested it on Firefox with the WiFi connection and the transmission still dropped

I think you should test using 2G or GPRS in the ffplayout tab and in another tab open the Restreamer application without limiting bandwidth. If the restreamer has no problem, then it is a network problem.

**Comment by LuizStSantos** [comment]
I will be making a change to the network on Sunday to see if this problem can be resolved.

**Comment by LuizStSantos** [comment]
I made some adjustments and it seems that the problem was solved, I changed from Ubuntu to Debian 12, I changed my network and put a Microtik to make a firewall, and I reformatted my stream server and it seems that the problem stopped, I'll do some more tests and if everything goes well, I'm closing this article
