### ISSUE TITLE
in v 20 I cant find how to  relink tv-media

### ISSUE THREAD

**Issue by brixxnatt** [ffplayout/ffplayout#450]
in V20 latest , i cant find how to relink  tv-media to the new location , in the ffplayout folder there is nothing , no links ?
what to do please ?

**Comment by jb-alvarado** [comment]
When everything works like it should now, there is no need any more to relink the storage location.

**Comment by brixxnatt** [comment]
id we chnage the tv-media folder location in config , any video in the playlist cant be preview , it gives error

**Comment by jb-alvarado** [comment]
What does the browser console says, and the logging from ffpapi (journalctl -u ffpapi)?

**Comment by brixxnatt** [comment]
Console whe previewing a video
media.e9bbec14.js:34 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. Me
(anonymous) @ media.e9bbec14.js:34
media.e9bbec14.js:34 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. Me {code: 4, message: 'No compatible source was found for this media.'}code: 4message: "No compatible source was found for this media."[[Prototype]]: ObjectMEDIA_ERR_ABORTED: 1MEDIA_ERR_CUSTOM: 0MEDIA_ERR_DECODE: 3MEDIA_ERR_ENCRYPTED: 5MEDIA_ERR_NETWORK: 2MEDIA_ERR_SRC_NOT_SUPPORTED: 4code: 0message: ""status: nullconstructor: ƒ Me(i)MEDIA_ERR_ABORTED: 1MEDIA_ERR_CUSTOM: 0MEDIA_ERR_DECODE: 3MEDIA_ERR_ENCRYPTED: 5MEDIA_ERR_NETWORK: 2MEDIA_ERR_SRC_NOT_SUPPORTED: 4defaultMessages: 1: "You aborted the media playback"2: "A network error caused the media download to fail part-way."3: "The media playback was aborted due to a corruption problem or because the media used features your browser did not support."4: "The media could not be loaded, either because the server or network failed or because the format is not supported."5: "The media is encrypted and we do not have the keys to decrypt it."[[Prototype]]: ObjecterrorTypes: Array(6)0: "MEDIA_ERR_CUSTOM"1: "MEDIA_ERR_ABORTED"2: "MEDIA_ERR_NETWORK"3: "MEDIA_ERR_DECODE"4: "MEDIA_ERR_SRC_NOT_SUPPORTED"5: "MEDIA_ERR_ENCRYPTED"length: 6[[Prototype]]: Array(0)length: 1name: "Me"prototype: {code: 0, message: '', status: null, MEDIA_ERR_CUSTOM: 0, MEDIA_ERR_ABORTED: 1, …}MEDIA_ERR_ABORTED: 1MEDIA_ERR_CUSTOM: 0MEDIA_ERR_DECODE: 3MEDIA_ERR_ENCRYPTED: 5MEDIA_ERR_NETWORK: 2MEDIA_ERR_SRC_NOT_SUPPORTED: 4code: 0message: ""status: nullconstructor: ƒ Me(i)[[Prototype]]: Objectarguments: (...)caller: (...)[[FunctionLocation]]: media.e9bbec14.js:34[[Prototype]]: ƒ ()apply: ƒ apply()arguments: (...)bind: ƒ bind()call: ƒ call()caller: (...)constructor: ƒ Function()length: 0name: ""toString: ƒ toString()Symbol(Symbol.hasInstance): ƒ [Symbol.hasInstance]()get arguments: ƒ ()set arguments: ƒ ()get caller: ƒ ()set caller: ƒ ()[[FunctionLocation]]: [[Prototype]]: Object[[Scopes]]: Scopes[0][[Scopes]]: Scopes[2]0: Module {S: Window, ey: ƒ, b0: ƒ, Zv: ƒ, es: ƒ, …}1: Global {window: Window, self: Window, document: document, name: '', location: Location, …}[[Prototype]]: Object
(anonymous) @ media.e9bbec14.js:34
La.n.error @ media.e9bbec14.js:34
error @ media.e9bbec14.js:188
t @ media.e9bbec14.js:188
s @ media.e9bbec14.js:34
Qe.s.dispatcher.s.dispatcher @ media.e9bbec14.js:34
and i know 100% its a link issue

**Comment by jb-alvarado** [comment]
Please run `systemctl -f -u ffpapi` on the server and after try again to preview the file in Browser. Then post the output from the server terminal.

**Comment by brixxnatt** [comment]
> Please run `systemctl -f -u ffpapi` on the server and after try again to preview the file in Browser. Then post the output from the server terminal.

invaild command , please re-check

**Comment by jb-alvarado** [comment]
Ah..., I mean `journalctl -f -u ffpapi`

**Comment by brixxnatt** [comment]
> Ah..., I mean `journalctl -f -u ffpapi`

My bad , the files was in .mkv those are not playiing , the .mp4 files play correct
