### ISSUE TITLE
ffplayout Software Player is not working

### ISSUE THREAD

**Issue by gihan353** [ffplayout/ffplayout#451]
I am using Latest playout version (v0.20.0) and using ubuntu 22.04 operating system 
Problem is when I am creating a playlist and try to play the videos but the player not working and come errors (attached the photo with log files)
![log file](https://github.com/ffplayout/ffplayout/assets/44135989/9e5775e6-760e-40f8-beec-eb09b1b5b97d)
![player issue](https://github.com/ffplayout/ffplayout/assets/44135989/ba56132b-096a-4492-be5b-23ad36879699)

**Comment by catalinx3006** [comment]
Install ffmpeg 5+
