### ISSUE TITLE
stream playlist enhancement

### ISSUE THREAD

**Issue by LuizStSantos** [ffplayout/ffplayout#452]
Possibility of setting a name for the stream in the playlist, and also the possibility of placing RTMP and SRT streams directly in the playlist

![arq 1](https://github.com/ffplayout/ffplayout/assets/73047610/745e00d2-13ba-4576-8bed-e3fe149f85a7)

**Comment by LuizStSantos** [comment]
> Somewhere here in the issue I have described why is not very stable to use rtmp or other streamings playlist.

But is it at least possible to put a name to define what is going on?

**Comment by jb-alvarado** [comment]
I you want, and if you willing to maintain that part, you could create a pull request. I think this can be done in [frontend](https://github.com/ffplayout/ffplayout-frontend) only, so is only html and javascript. It's only important that the current functionality doesn't break.

**Comment by matbrgz** [comment]
I can help, but I didn't get exactly what you want. Did you want to create a playlist from the items in media, this playlist must be a json file, or you want to setup the entire channel for a new stream?  BTW I'm totally available to talk since we live in the same country, you can find my contacts in my GitHub profile.

**Comment by LuizStSantos** [comment]
> I can help, but I didn't get exactly what you want. Did you want to create a playlist from the items in media, this playlist must be a json file, or you want to setup the entire channel for a new stream? BTW I'm totally available to talk since we live in the same country, you can find my contacts in my GitHub profile.

@matbrgz And my problem is that my https urls on my Restreamer server follow a parameter of using a code to define the transmission, what I wanted in my case would be,

Name: CSf Transmission
source: https://Transmission.live/memfs/a338bfab-1992-4a2b-816e-e7758b30c90c.m3u8

but only the name appears in the playlist instead of the url because I have 3 live broadcasts one after the other so it sometimes gets confusing when to organize them in the playlist
