### ISSUE TITLE
preview m3u8

### ISSUE THREAD

**Issue by LuizStSantos** [ffplayout/ffplayout#461]
Possibility to press play to view m3u8 content
![PREVIWE](https://github.com/ffplayout/ffplayout/assets/73047610/4e4f4dcf-294e-4b06-964e-8c32a1a780e3)

**Comment by JunioCalu** [comment]
> Possibility to press play to view m3u8 content ![PREVIWE]()

In which TV programming scenario are you using M3U8 playlists? What is the logic behind it?

**Comment by LuizStSantos** [comment]
@JunioCalu I'm using it to insert live broadcasts directly into the Playlist

**Comment by JunioCalu** [comment]
> @JunioCalu I'm using it to insert live broadcasts directly into the Playlist

Can you explain the process for generating this type of playlist? It might be useful in my case.

**Comment by LuizStSantos** [comment]
> > @JunioCalu I'm using it to insert live broadcasts directly into the Playlist
> 
> Can you explain the process for generating this type of playlist? It might be useful in my case.

I am using a server with [Datarhei Restreamer](https://datarhei.com/) and I use it both to receive broadcasts and to send, in my case it receives 2 live broadcasts, one at 12:00 AM and the other at 12:30 PM, the server provides me with the links for both such as RTMP, SRT and HLS, in this case I use HLS directly in the Playlist, always at the same time.

![Captura de tela 2023-12-11 090051](https://github.com/ffplayout/ffplayout/assets/73047610/5522ae5e-5b26-4ce3-bd0b-2702acc2d913)

**Comment by JunioCalu** [comment]
> I am using a server with [Datarhei Restreamer](https://datarhei.com/) and I use it both to receive broadcasts and to send, in my case it receives 2 live broadcasts, one at 12:00 AM and the other at 12:30 PM, the server provides me with the links for both such as RTMP, SRT and HLS, in this case I use HLS directly in the Playlist, always at the same time.

Are you conducting any live stream directly from YouTube?

**Comment by LuizStSantos** [comment]
> > I am using a server with [Datarhei Restreamer](https://datarhei.com/) and I use it both to receive broadcasts and to send, in my case it receives 2 live broadcasts, one at 12:00 AM and the other at 12:30 PM, the server provides me with the links for both such as RTMP, SRT and HLS, in this case I use HLS directly in the Playlist, always at the same time.
> 
> Are you conducting any live stream directly from YouTube?

No, in the past I would get the YouTube link and put it in OBS and then it would go to the broadcast, but I managed to get people to deliver it to me directly on my server
