### ISSUE TITLE
UDP stream

### ISSUE THREAD

**Issue by baruchfer** [ffplayout/ffplayout#466]
Hi, I'm testing a .ts file with MPEGTS format, on the out config I configured:

mode: stream
output_param: -c copy -f mpegts udp://225.10.11.12:3000?localaddr=192.168.10.208

But is not UDP traffic.

Is possible loop the file 7x24?

Thanks

**Comment by cooliobr** [comment]
try this

-c:v h264_nvenc -aspect 16:9 -r:v 30 -b:v 2000k -maxrate 2000k -bufsize 2000k -profile:v main -preset p4 -level 41 -delay 0 -ar 48000 -b:a 128k -c:a aac -muxdelay 0 -g 30 -keyint_min 30 -f mpegts "udp://eth{0,1...}@225.10.11.12:3000?pkt_size=1316"

**Comment by jb-alvarado** [comment]
> Hi, I'm testing a .ts file with MPEGTS format, on the out config I configured:

For UDP output you should use the same command you would use in ffmpeg. I only don't recommend ` -c copy`, you can test copy mode and if it works for you, is fine, but then you have to set:

```YAML
    copy_audio: true
    copy_video: true
```
too.

> Is possible loop the file 7x24?

For that the easiest would be, to just copy that file in a folder, an run the playout in folder mode.
