### ISSUE TITLE
Improved Configuration Menu

### ISSUE THREAD

**Issue by matbrgz** [ffplayout/ffplayout#470]
**Overview:**
Implement several enhancements to the configuration menu, focusing on simplifying user configuration, enabling greater customization, and providing a more interactive and user-friendly experience.

**Proposed Improvements:**

1. **User-Friendly Logo Configuration:**
   - Allow users to upload a new logo directly from the configuration menu.
   - Provide options for users to choose where the logo should appear.
   - Enable customization of logo appearance through filters.

2. **Menu Tab Organization:**
   - Divide the configuration menu into multiple tabs for better organization and navigation.
   - Categorize settings logically to improve user experience and reduce clutter.

3. **Interactive User Inputs:**
   - Enable users to interact with configuration settings using arguments.
   - For example, when choosing a logo, provide a file upload option, and allow users to specify display locations and customize filters using input fields.

4. **Enhanced Inclusion of External Configurations:**
   - Facilitate the inclusion of configurations from external sources in a more streamlined manner.
   - Provide an option for users to add multiple configurations seamlessly.

**Benefits of Enhanced Configuration:**
1. **User Empowerment:** Users can easily customize their experience, including logo appearance and other settings, without the need for complex configurations.

2. **Improved Navigation:** The introduction of tabs enhances menu organization, making it easier for users to locate and adjust specific settings.

3. **Interactive Configuration:** Allowing users to interact with settings through input fields makes the configuration process more dynamic and user-friendly.

**Proposed Action:**
1. **Design Mockups:** Collaborate with the design team to create detailed design mockups for the improved configuration menu.

2. **Development Plan:** Outline a development plan for implementing the proposed enhancements, including frontend and backend adjustments.

3. **User Testing:** Conduct user testing to gather feedback on the enhanced configuration menu's usability and effectiveness.

4. **Documentation:** Update documentation to guide users on utilizing the new configuration features effectively.

**Comment by jb-alvarado** [comment]
Sounds not bad in general, to be honest until now I was to lazy to put much effort in the configuration section. At the moment it creates its input fields automatically and I don't have to update it, when I add a new feature to the engine. Which I found very useful.
