### ISSUE TITLE
Getting a 404 on /api/control/1/media/next/

### ISSUE THREAD

**Issue by Raketemensch** [ffplayout/ffplayout#476]
Hitting /api/control/1/media/next/ with a valid token returns a 404 error.

This may be because the system is in `folder` mode and not `playlist` mode, but I'm not certain.

**To Reproduce**

1. Run `curl -v -X GET http://192.168.1.6:8787/api/control/1/media/next/ -H 'Content-Type: application/json' -H 'Authorization: Bearer <token>'`
2. View the 404 error

I definitely have a valid token, and can pull the current clip, just not the next one.

**Expected behavior**

I expected to be told what the next clip will be. Perhaps in Folder mode this is the expected behavior? If so, I will update the doc and put in a PR.

**Desktop/Server/Software (please complete the following information):**

 - OS: Sonoma 14.1
- ffplayout version 0.20.2
- ffmpeg version 4.4.2-0ubuntu0.22.04.1
- are you using the current master of ffplayout? yes

**Config Settings:**

- curl -v -X GET 

**Logging:**

- This API call does not seem to log to ffplayout.log

**Comment by LuizStSantos** [comment]
> Hitting /api/control/1/media/next/ with a valid token returns a 404 error.
> 
> This may be because the system is in `folder` mode and not `playlist` mode, but I'm not certain.
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> 
> 1. Run `curl -v -X GET http://192.168.1.6:8787/api/control/1/media/next/ -H 'Content-Type: application/json' -H 'Authorization: Bearer <token>'`
> 2. View the 404 error
> 
> I definitely have a valid token, and can pull the current clip, just not the next one.
> 
> **Expected behavior**
> 
> I expected to be told what the next clip will be. Perhaps in Folder mode this is the expected behavior? If so, I will update the doc and put in a PR.
> 
> **Desktop/Server/Software (please complete the following information):**
> 
> * OS: Sonoma 14.1
> * ffplayout version 0.20.2
> * ffmpeg version 4.4.2-0ubuntu0.22.04.1
> * are you using the current master of ffplayout? yes
> 
> **Config Settings:**
> 
> * curl -v -X GET
> 
> **Logging:**
> 
> * This API call does not seem to log to ffplayout.log

ffmpeg version needs to be 5+

**Comment by jb-alvarado** [comment]
Hello @Raketemensch, I have not test it but I think there is only a wrong command in the documentation. At the end is a slash to much.

The correct address should be `/api/control/1/media/next`.

Sorry for the inconvenience.
