### ISSUE TITLE
Possibility to execute command in the playlist to use x9k3

### ISSUE THREAD

**Issue by LuizStSantos** [ffplayout/ffplayout#483]
The possibility of executing commands directly in the playlist for command execution specifically being able to use [x9k3](https://github.com/futzu/x9k3) to make an SCTE35 stream as if it were a video on the playlist

**Comment by jb-alvarado** [comment]
Is almost the same then: https://github.com/ffplayout/ffplayout/blob/67b98694c3d7ca4639eac59d06a4b537a7cf7c71/assets/ffplayout.yml#L127

**Comment by LuizStSantos** [comment]
> Is almost the same then:
> 
> https://github.com/ffplayout/ffplayout/blob/67b98694c3d7ca4639eac59d06a4b537a7cf7c71/assets/ffplayout.yml#L127

I don't want to link a commercial break to it the z9k3 command to do would be this x9k3 -i https://slow.golf/longb.m3u8 --output_dir /home/a/variant0 -continue_m3u8 -s sidecar.txt Would you be able to link it?

**Comment by LuizStSantos** [comment]
> Is almost the same then:
> 
> https://github.com/ffplayout/ffplayout/blob/67b98694c3d7ca4639eac59d06a4b537a7cf7c71/assets/ffplayout.yml#L127
would it be something like that?
{
  "media_object": {
    "file_path": "/caminho/do/seu/diretorio/break*"
  },
  "external_program_command": "x9k3 -i https://slow.golf/longb.m3u8 --output_dir /home/a/variant0 -continue_m3u8 -s sidecar.txt"
}

**Comment by jb-alvarado** [comment]
The task runs on every new clip at the beginning. You can run any program or executable script you want, as stdin it gets a json object:

```JSON
"play_mode": ...,
"ingest_runs": ...,
"index": ...,
"start_sec": ...,
"start_time": ...,
"played_sec": ...,
"remaining_sec": ...,
"current_media": {
    "seek": ...,
    "out": ...,
    "duration": ...,
    "category": ...,
    "source": ...
}

```

Here is they discuss another solution: https://github.com/ffplayout/ffplayout/issues/276

**Comment by LuizStSantos** [comment]
> The task runs on every new clip at the beginning. You can run any program or executable script you want, as stdin it gets a json object:
> 
> ```json
> "play_mode": ...,
> "ingest_runs": ...,
> "index": ...,
> "start_sec": ...,
> "start_time": ...,
> "played_sec": ...,
> "remaining_sec": ...,
> "current_media": {
>     "seek": ...,
>     "out": ...,
>     "duration": ...,
>     "category": ...,
>     "source": ...
> }
> ```
> 
> Here is they discuss another solution: #276

In this case I made this script#
```python
import requests

# Login information
username = "your_username"
password = "your_password"

# API URLs
login_url = "http://127.0.0.1:8787/auth/login/"
info_url = "http://127.0.0.1:8787/api/control/1/media/current"

# Login to the API
login_payload = {"username": username, "password": password}
login_response = requests.post(login_url, json=login_payload, headers={"Content-Type": "application/json"})

if login_response.status_code == 200:
    # Get authentication token
    token = login_response.json().get("token")

    # Get information about the current clip using the authentication token
    info_response = requests.get(info_url, headers={"Content-Type": "application/json", "Authorization": f"Bearer {token}"})

    if info_response.status_code == 200:
        # Process information about the current clip
        current_clip_info = info_response.json()
        clip_name = current_clip_info.get("name", "").lower()

        # Check if the clip name contains "break"
        if "break" in clip_name:
            # Execute the desired command
            command = 'x9k3 -i https://slow.golf/longb.m3u8 --output_dir /home/a/variant0 -continue_m3u8 -s sidecar.txt'
            # Execute the command
            import subprocess
            subprocess.run(command, shell=True)
        else:
            print("The clip name does not contain 'break'.")
    else:
        print(f"Failed to get information about the clip. Status Code: {info_response.status_code}")
else:
    print(f"Login failed. Status Code: {login_response.status_code}")
``` 
to execute the command would it work?

**Comment by jb-alvarado** [comment]
When you are using the task option from config, you don't have to use the requests, you can work directly with the object you get from STDIN like here: https://stackoverflow.com/questions/34590412/pythons-json-loadsys-stdin-gets-me-u-instead-of-double-quotes-around-str
