### ISSUE TITLE
why we cant stream to instagram

### ISSUE THREAD

**Issue by brixxnatt** [ffplayout/ffplayout#484]
hello , why we cant stream to instagram even it we added -flv  rtmps://edgetee-upload-mrs2-2.xx.fbcdn.net:443/rtmp/  then key at the parameters it wont work
any issue please

regards

**Comment by jb-alvarado** [comment]
Sorry I don't have any idea why this is not working and I don't think this is an issue with ffplayout. Try you commend with ffmpeg, and when it works there apply that settings to ffplayout. If it doesn't work with ffmpeg you have to make a research why not.
