### ISSUE TITLE
What ports are needed for ffplayout?

### ISSUE THREAD

**Issue by C0la149** [ffplayout/ffplayout#487]
Hi all. I'm sorry to bother you. I currently have a firewall on the server. and it is currently blocking all possible ports. What ports are needed for ffplayout to work properly? Thank you in advance for your response!

**Comment by jb-alvarado** [comment]
In a default setup ffpapi needs port 8787 and for live ingest ffplayout needs port 1936.

But because ffpapi don't uses SSL, the recommend way is to use a proxy for https connections. So you could leave 8787 closed install nginx and let's encrypt and forward 443 to 8787.

**Comment by C0la149** [comment]
@jb-alvarado Got it, I'll try it! Thank you)
