### ISSUE TITLE
Task script

### ISSUE THREAD

**Issue by LuizStSantos** [ffplayout/ffplayout#493]
I have a problem, I activated the task to execute a Python script that I made but it doesn't execute, I tried to put it in the field in these 2 formats and it didn't work

```shell
 python3 /home/luiz/script.py
``` 
```shell
/home/luiz/script.py
``` 
```shell
import requests
import subprocess
import json

# JSON-RPC server settings
rpc_url = "http://127.0.0.1:7070"
auth_key = "---auth-key---"

# Function to check the next clip and execute the command if the name contains "break"
def check_and_execute_command():
    try:
        # Send a request to get information about the next clip
        response = requests.post(
            rpc_url,
            headers={"Content-Type": "application/json", "Authorization": auth_key},
            data='{"media":"next"}'
        )

        # Check if the response is successful
        if response.status_code == 200:
            # Parse the returned JSON
            data = response.json()

            # Get the file name of the next clip
            clip_name = data["current_media"]["source"]
            # Get the duration of the clip
            duration = data["current_media"]["duration"]

            # Check if the file name contains "break"
            if "break" in clip_name:
                # Build the command with dynamic duration
                command = f'adbreak --pts 9.6233 --duration {duration} --sidecar sidecar.txt'
                # Execute the command using subprocess
                subprocess.run(command, shell=True)
                print(f"Command executed for clip '{clip_name}' with 'break' in the name and dynamic duration {duration}.")
            else:
                print(f"The next clip '{clip_name}' does not contain 'break' in the name.")
        else:
            print(f"Error in the request: {response.status_code}")
    except Exception as e:
        print(f"Error processing the request: {str(e)}")

# Call the function to check and execute the command
check_and_execute_command()

``` 
![1](https://github.com/ffplayout/ffplayout/assets/73047610/deecf971-e690-411a-8a77-7a0358c659e8)
![2](https://github.com/ffplayout/ffplayout/assets/73047610/59556f2c-46ec-4f50-af3c-6b653cb5b956)

**Comment by jb-alvarado** [comment]
Use a [shebang](https://realpython.com/python-shebang/) in first line of the script, like `#!/usr/bin/env python3`. Then make the script executable und put only the script path in task config, without `python3`.

If you want to work with current clip, you also don't need to use request, just get [**STDIN**](https://stackoverflow.com/a/34590531/3678295).

**Comment by LuizStSantos** [comment]
> Use a [shebang](https://realpython.com/python-shebang/) in first line of the script, like `#!/usr/bin/env python3`. Then make the script executable und put only the script path in task config, without `python3`.
> 
> If you want to work with current clip, you also don't need to use request, just get [**STDIN**](https://stackoverflow.com/a/34590531/3678295).

I didn't quite understand how to use stdin, could you give me an example, in my case it would be to make a command shell

**Comment by jb-alvarado** [comment]
Sorry sdtin was wrong, the object get passed as an argument...

You can use something like:

```Python
#!/usr/bin/env python3

import json
import sys

# install plyer: pip install plyer
from plyer import notification


def send_notification(title, message):
    notification.notify(
        title=title,
        message=message,
        timeout=10
    )


if __name__ == "__main__":
    title = "ffplayout - current clip:"
    input_data = json.loads(sys.argv[1]).get('current_media')

    if input_data is not None:
        # print(input_data['source'])

        send_notification(title, f"Play: \"{input_data['source']}\"")

```

**Comment by JunioCalu** [comment]
>     input_data = json.loads(sys.argv[1]).get('current_media')

I became interested in the topic as well. What argument should be passed to sys.argv[1]?

**Comment by LuizStSantos** [comment]
> > ```
> > input_data = json.loads(sys.argv[1]).get('current_media')
> > ```
> 
> Também me interessei pelo tema. Qual argumento deve ser passado para sys.argv[1]?

So far I've written a script to run x9k3 to do the scte-35 that I needed, I'm still doing the variation so that it takes the time of the current clip to execute the command
```
https://github.com/LuizStSantos/scripts-cuda-ffmpeg-x9k3/blob/main/task-ffplayout-x9k3.py
```

**Comment by LuizStSantos** [comment]
@jb-alvarado Thanks for the help, I managed to make a script that analyzes the current clip, checks its name and if the name contains break* it executes a command using the duration of the break file and executes the command by sending the x9k3 sidecar.txt to do the scte- 35 I needed

```
https://github.com/LuizStSantos/scripts-cuda-ffmpeg-x9k3/blob/main/task-ffplayout-x9k3.py
```

**Comment by JunioCalu** [comment]
> ```
> https://github.com/LuizStSantos/scripts-cuda-ffmpeg-x9k3/blob/main/task-ffplayout-x9k3.py
> ```

Could you provide a detailed explanation of the scenario where this is useful in practice? Please elaborate on how the command you use works and how the interaction protocol between the playout and the TV distributor functions. Also, could you outline the necessary sub-steps required to ensure a successful transmission between the playout and the TV distributor?

**Comment by LuizStSantos** [comment]
> > ```
> > https://github.com/LuizStSantos/scripts-cuda-ffmpeg-x9k3/blob/main/task-ffplayout-x9k3.py
> > ```
> 
> Could you provide a detailed explanation of the scenario where this is useful in practice? Please elaborate on how the command you use works and how the interaction protocol between the playout and the TV distributor functions. Also, could you outline the necessary sub-steps required to ensure a successful transmission between the playout and the TV distributor?

Hello, so currently I have a Channel for rural producers, and I have 2 places to enter at the moment, many things they ask for like the scte-35 system and a compatible transmission with their systems, the SCTE-35 will be for the commercial overlay of some breaks, defined by the region the user is in, my transmission is defined with recorded programs and the live one where I am using a Restreamer Datarhei server to generate an m3u8 url compatible with ffplayout where I receive both the live programs, and also use it for to give back to the operators, and I have a server with proxmox where ffplayout is currently located, using a video card to process the nvenc codec that I use in it, and also because it has stability where I can clone the system ready to update and replace the connection with minimal interruptions In my schedules, I'm going to send 2 pdfs of some operators that I'm adjusting to be able to join them, currently I'm already on one, but using another playout software "Pirate that I don't like" so I'm migrating to ffplayout.
[SamsungTVPlus_LinearChannelSpec_v1.8.1 (2).pdf](https://github.com/ffplayout/ffplayout/files/13988128/SamsungTVPlus_LinearChannelSpec_v1.8.1.2.pdf)
[Pluto.TV.Technical.Requirements.for.Live.Streaming.Channels.and.Events.v1.9.draft (2).pdf](https://github.com/ffplayout/ffplayout/files/13988129/Pluto.TV.Technical.Requirements.for.Live.Streaming.Channels.and.Events.v1.9.draft.2.pdf)
Some links that can help you with software I use
Proxmox
```
https://www.proxmox.com/en/
``` 
ffplayout
```
https://ffplayout.github.io/
``` 
x9k3 - SCTE-35
```
https://github.com/futzu/x9k3
``` 
Datarhei Restreamer

```
https://datarhei.com/
``` 
OS and Script I use

Debian 12
```
https://www.debian.org/
``` 
CUDA Nvidia "nvenc"

```
https://github.com/LuizStSantos/scripts-cuda-ffmpeg-x9k3/blob/main/cuda-nvidia.sh
``` 
ffmpeg-python3-pip-x9k3

```
https://github.com/LuizStSantos/scripts-cuda-ffmpeg-x9k3/blob/main/ffmpeg-python3-pip-x9k3.sh
``` 
task-ffplayout-x9k3

```
https://github.com/LuizStSantos/scripts-cuda-ffmpeg-x9k3/blob/main/task-ffplayout-x9k3.py
``` 

Note the task has to be run once before using x9k3 and the sidecar folder has to be located in the /usr/share/ffplayout folder then yes you can run x9k3 to read the ffplayout stream, all the material that is in ffplayout in current playing and contain the name break the task will read the time play play in the sidecar and execute the command sending the SCTE-35 signal, you have to adjust the initiation time so that the break time of the x9k3 is in accordance with the command x9k3 adbreak "--pts"

**Comment by JunioCalu** [comment]
> Note the task has to be run once before using x9k3 and the sidecar folder has to be located in the /usr/share/ffplayout folder then yes you can run x9k3 to read the ffplayout stream, all the material that is in ffplayout in current playing and contain the name break the task will read the time play play in the sidecar and execute the command sending the SCTE-35 signal, you have to adjust the initiation time so that the break time of the x9k3 is in accordance with the command x9k3 adbreak "--pts"

Very interesting, I didn't quite understand some details of your explanation. Could you tell me more about this "time play in the sidecar" part? What exactly are you marking in your ".m3u8" file to be communicated to the TV operator through the x9k3 command? Is it the total duration of each commercial at the moment it starts playing in the playout, or the total duration of each video clip in the programming itself? Could you please give an example?

**Comment by LuizStSantos** [comment]
> > Note the task has to be run once before using x9k3 and the sidecar folder has to be located in the /usr/share/ffplayout folder then yes you can run x9k3 to read the ffplayout stream, all the material that is in ffplayout in current playing and contain the name break the task will read the time play play in the sidecar and execute the command sending the SCTE-35 signal, you have to adjust the initiation time so that the break time of the x9k3 is in accordance with the command x9k3 adbreak "--pts"
> 
> Very interesting, I didn't quite understand some details of your explanation. Could you tell me more about this "time play in the sidecar" part? What exactly are you marking in your ".m3u8" file to be communicated to the TV operator through the x9k3 command? Is it the total duration of each commercial at the moment it starts playing in the playout, or the total duration of each video clip in the programming itself? Could you please give an example?

Regarding this, the operator asks me to insert the size of my ads into m3u8 along with the time it will start to be overlapped to use regional ads, about the sidecar time, the --pts part and for You have to calculate when it starts because x9k3 has a delay to be able to translate the conventional m3u8 from ffplayout to x9k3, so the trigger that ffplayout triggers earlier than x9k3, thus leaving it without the exact time of it "The ffplayout activates the command within the ads at the moment, but in x9k3 this ads hasn't happened yet" so you have to do the delay calculation which would be to get ffplayout together with x9k3 to put a video with time seconds and put it side by side and record the screen later calculate the time to arrive at the exact moment, do it more than once to take the test and average the time.
