### ISSUE TITLE
Possibility to see preview

### ISSUE THREAD

**Issue by LuizStSantos** [ffplayout/ffplayout#495]
The possibility of viewing the preview directly, without having to change the URL
Because in my case I access from 2 places and I have to keep changing URLs to see the transmission to one internal and one external.
![pre](https://github.com/ffplayout/ffplayout/assets/73047610/85a65753-dc3f-47ed-b687-bf64f8cd5efb)

**Comment by jb-alvarado** [comment]
Have you try `/live/index.m3u8`?

**Comment by LuizStSantos** [comment]
> Have you try `/live/index.m3u8`?

I just tried this and it worked thanks, sorry to bother you with this
