### ISSUE TITLE
loudnorm

### ISSUE THREAD

**Issue by LuizStSantos** [ffplayout/ffplayout#500]
I'm trying to use the loudnorm filter but I can't apply it

[c_a_out]loudnorm=I=-6:TP=-1.5:LRA=11[a_out]
```
[ERROR] [Validator] ffmpeg error on position 1 - 08:00:00.000: /var/lib/ffplayout/tv-media/Vinhetas/vinheta-Canalsolofertil-Pass00.mp4: [AVFilterGraph @ 0x56321c818380] Unable to parse graph description substring: "loudnorm=I=-6:TP=-1.5:LRA=11,silencedetect=n=-30dB[aout0]"
Error initializing complex filters.
``` 
![Captura de tela 2024-01-27 093159](https://github.com/ffplayout/ffplayout/assets/73047610/1d48caa7-758b-4a26-8316-bf360641f8bb)

**Comment by JunioCalu** [comment]
> [c_a_out]loudnorm=I=-6:TP=-1.5:LRA=11[a_out]

It works for me:

loudnorm=I=-6:TP=-1.5:LRA=11[c_a_out]

**Comment by jb-alvarado** [comment]
In the past I had the loudnorm filter directly integrated, but I removed it. The problem is, that you can only use the one pass mode and with that you get really pour quality. I would not recommend to use it.

**Comment by JunioCalu** [comment]
I'm testing the following combination of filters below. Where dynaudnorm is used for dynamic normalization, acompressor to control the dynamic range, and alimiter to avoid unwanted volume peaks:

    dynaudnorm=f=200:g=15[audio_normalized];[audio_normalized]acompressor=threshold=0.2:ratio=4:attack=20:release=250:knee=2.5[audio_compressed];[audio_compressed]alimiter=level_in=1.0:limit=0.9:level_out=0.95:release=50[c_a_out]

### Breaking down the explanation of each filter.
    
### dynaudnorm Filter

    [0:a]dynaudnorm=f=200:g=15[audio_normalized];

- dynaudnorm: This is the dynamic audio normalization filter. It automatically adjusts the gain to maintain a consistent loudness level.
- f=200: Frame length. This is the size of the window in terms of the number of frames used for audio analysis. A larger value provides a smoother change in gain.
- g=15: Max gain. This is the maximum gain applied to the audio. It limits how much the gain can be increased.
- [audio_normalized]: This is the name of the audio track after applying the dynaudnorm filter. It will be used as input for the next filter.

### acompressor Filter

    [audio_normalized]acompressor=threshold=0.2:ratio=4:attack=20:release=250:knee=2.5[audio_compressed];

- [audio_normalized]: This is the input for the filter, coming from dynaudnorm.
- acompressor: This is the audio compression filter.
- threshold=0.2: Compression threshold. When the audio level exceeds this value (in linear terms), compression begins to be applied.
- ratio=4: Compression ratio. For example, a 4:1 ratio means if the audio is 4 dB above the threshold, it will be reduced to 1 dB above the threshold.
- attack=20: Attack time. It’s the time in milliseconds for the compressor to start acting after the signal exceeds the threshold.
- release=250: Release time. It’s the time in milliseconds for the compressor to stop acting after the signal falls below the threshold.
- knee=2.5: Knee curve. A larger value smooths the transition between uncompressed and compressed, making it less noticeable.
- [audio_compressed]: This is the name of the audio track after compression.

### alimiter Filter

    [audio_compressed]alimiter=level_in=1.0:limit=0.9:level_out=0.95:release=50[audio_output]

- [audio_compressed]: This is the input for the filter, coming from acompressor.
- alimiter: This is an audio limiter filter.
- level_in=1.0: Input level. Sets the entry level for the limiter.
- limit=0.9: Peak limit. Sets the maximum level that the processed audio can reach.
- level_out=0.95: Output level. Sets the output level after limiter processing.
- release=50: Release time. Similar to the compressor, it’s the time for the limiter to "release" the signal after it falls below the threshold.
- [c_a_out]: This is the name of the audio track after the limiter processing.

Note: With the courtesies of ChatGPT.

**Comment by jb-alvarado** [comment]
Thank you @JunioCalu for you effort! In the past we used the normal one pass loudnorm filter in live events, and this was messing up our sound. For example when there was silence the noise become very loud.

I will test your example too, then we can add it in the documentation.

**Comment by LuizStSantos** [comment]
> I'm testing the following combination of filters below. Where dynaudnorm is used for dynamic normalization, acompressor to control the dynamic range, and alimiter to avoid unwanted volume peaks:
> 
> ```
> dynaudnorm=f=200:g=15[audio_normalized];[audio_normalized]acompressor=threshold=0.2:ratio=4:attack=20:release=250:knee=2.5[audio_compressed];[audio_compressed]alimiter=level_in=1.0:limit=0.9:level_out=0.95:release=50[c_a_out]
> ```
> 
> ### Breaking down the explanation of each filter.
> ### dynaudnorm Filter
> ```
> dynaudnorm=f=200:g=15[audio_normalized];
> ```
> 
> * dynaudnorm: This is the dynamic audio normalization filter. It automatically adjusts the gain to maintain a consistent loudness level.
> * f=200: Frame length. This is the size of the window in terms of the number of frames used for audio analysis. A larger value provides a smoother change in gain.
> * g=15: Max gain. This is the maximum gain applied to the audio. It limits how much the gain can be increased.
> * [audio_normalized]: This is the name of the audio track after applying the dynaudnorm filter. It will be used as input for the next filter.
> 
> ### acompressor Filter
> ```
> [audio_normalized]acompressor=threshold=0.2:ratio=4:attack=20:release=250:knee=2.5[audio_compressed];
> ```
> 
> * [audio_normalized]: This is the input for the filter, coming from dynaudnorm.
> * acompressor: This is the audio compression filter.
> * threshold=0.2: Compression threshold. When the audio level exceeds this value (in linear terms), compression begins to be applied.
> * ratio=4: Compression ratio. For example, a 4:1 ratio means if the audio is 4 dB above the threshold, it will be reduced to 1 dB above the threshold.
> * attack=20: Attack time. It’s the time in milliseconds for the compressor to start acting after the signal exceeds the threshold.
> * release=250: Release time. It’s the time in milliseconds for the compressor to stop acting after the signal falls below the threshold.
> * knee=2.5: Knee curve. A larger value smooths the transition between uncompressed and compressed, making it less noticeable.
> * [audio_compressed]: This is the name of the audio track after compression.
> 
> ### alimiter Filter
> ```
> [audio_compressed]alimiter=level_in=1.0:limit=0.9:level_out=0.95:release=50[audio_output]
> ```
> 
> * [audio_compressed]: This is the input for the filter, coming from acompressor.
> * alimiter: This is an audio limiter filter.
> * level_in=1.0: Input level. Sets the entry level for the limiter.
> * limit=0.9: Peak limit. Sets the maximum level that the processed audio can reach.
> * level_out=0.95: Output level. Sets the output level after limiter processing.
> * release=50: Release time. Similar to the compressor, it’s the time for the limiter to "release" the signal after it falls below the threshold.
> * [c_a_out]: This is the name of the audio track after the limiter processing.
> 
> Note: With the courtesies of ChatGPT.

Thanks for the help, I applied it to my settings
