### ISSUE TITLE
Network interface monitoring not correctly detected.

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#506]
**Describe the bug**

I installed ffplayout on physical hardware, but ffplayout is recognizing the `docker0` interface as the main one, as if it were installed in a Docker container. The correct behavior would be to consider the actual physical interface as the main interface, in this case, the `enp0s20u2` interface.

**Desktop/Server/Software (please complete the following information):**

 - OS: Manjaro Linux 23.1.3
- ffplayout 20.3
- ffmpeg 6.1
- are you using the current master of ffplayout? No.

**Config Settings:**

- command line arguments
- config fie
[ffplayout-20.3.yml.txt](https://github.com/ffplayout/ffplayout/files/14085390/ffplayout-20.3.yml.txt)

**Logging:**
![Screenshot_20240129_103342](https://github.com/ffplayout/ffplayout/assets/8952225/6344e18c-15f0-43b1-b32d-6b2006937f3d)

    $ ip a                                           ✔ 

    1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
        link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
        inet 127.0.0.1/8 scope host lo
           valid_lft forever preferred_lft forever
        inet6 ::1/128 scope host noprefixroute 
           valid_lft forever preferred_lft forever
    2: enp7s0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN group default qlen 1000
        link/ether 78:2b:cb:ee:c1:29 brd ff:ff:ff:ff:ff:ff
    3: wlp6s0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
        link/ether 6a:3a:65:1c:a4:c5 brd ff:ff:ff:ff:ff:ff permaddr 90:48:9a:ee:dc:0f
    27: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
        link/ether 02:42:cb:e9:cb:43 brd ff:ff:ff:ff:ff:ff
        inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
           valid_lft forever preferred_lft forever
        inet6 fe80::42:cbff:fee9:cb43/64 scope link proto kernel_ll 
           valid_lft forever preferred_lft forever
    65: enp0s20u2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 1000
        link/ether 02:55:34:33:30:37 brd ff:ff:ff:ff:ff:ff
        inet 192.168.42.16/24 brd 192.168.42.255 scope global dynamic noprefixroute enp0s20u2
           valid_lft 1859sec preferred_lft 1859sec
        inet6 fe80::6084:7e74:dd8f:5253/64 scope link noprefixroute 
           valid_lft forever preferred_lft forever

- content of: ffplayout.log
[ffplayout-20.3.log.txt](https://github.com/ffplayout/ffplayout/files/14085458/ffplayout-20.3.log.txt)

**Comment by jb-alvarado** [comment]
Thanks for report! I added some typical interface names in a ignore [list](https://github.com/ffplayout/ffplayout/pull/512/commits/69bb639b7657a17417d28ef5e59eb8442318bebb). Hopefully that works.

**Comment by JunioCalu** [comment]
Thank you for the fix. On the first load of the monitoring page, I also thought that the Swap device monitoring data was not being displayed properly. As can be seen in the screenshot, the monitoring shows that the Swap device is being used at its maximum capacity, which is a bit unusual, but at first, I didn't try to verify if the data was valid. Days later, on a second load of the page, I confirmed that the monitoring was correctly displaying the Swap usage data.
