### ISSUE TITLE
increase CPU filter

### ISSUE THREAD

**Issue by LuizStSantos** [ffplayout/ffplayout#509]
I discovered that when placing a filter to override the processes for ffplayout, it increases by 30%.
```
[v_in];movie=/usr/share/ffplayout/logo-CanalSoloFertil-Negativa-AoVivo.png:loop=0,setpts=N/(30*TB),scale=120:120[logo];[v_in][logo]overlay=40:30:shortest=1[c_v_out]
``` 
logo filter
![com logo](https://github.com/ffplayout/ffplayout/assets/73047610/015ffb13-0ec4-4b10-be6e-9f41258f1855)
![logo](https://github.com/ffplayout/ffplayout/assets/73047610/ed948801-5ef0-4f59-87d6-4c91e92ce498)
 no filter
![sem logo](https://github.com/ffplayout/ffplayout/assets/73047610/44c37566-0207-4b06-b76b-9e4545a0cd50)
![sem logo 1](https://github.com/ffplayout/ffplayout/assets/73047610/8209b48b-2338-4be2-a26a-977fc5b55132)

**Comment by jb-alvarado** [comment]
When only ffmpeg uses more CPU and not ffplayout, then is not an ffplayout issue.

Some filters can use more, I would not say that is unnormal.

**Comment by JunioCalu** [comment]
Shouldn't hardware acceleration lower CPU usage? Is there a way to check if your hardware acceleration is working?
