### ISSUE TITLE
[Enhancement] Acess ip

### ISSUE THREAD

**Issue by LuizStSantos** [ffplayout/ffplayout#527]
Add the possibility of accessing the https://ip.com/ffplayout layout via your own port normally

And also the possibility of changing ffplayout port through the web UI itself

**Comment by jb-alvarado** [comment]
You can [override](https://askubuntu.com/questions/659267/how-do-i-override-or-configure-systemd-services) ffpapi service and add new port. Or setup a [proxy](https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/).

**Comment by JunioCalu** [comment]
A good dockerized proxy option is Linux server [SWAG](https://github.com/linuxserver/docker-swag/); it contains hundreds of configuration files for popular services like Grafana, Nextcloud, Mastodon, etc., pre-configured and ready to work with the Nginx proxy.

SWAG - Secure Web Application Gateway (formerly known as letsencrypt, no relation to Let's Encrypt™) sets up an Nginx webserver and reverse proxy with php support and a built-in certbot client that automates free SSL server certificate generation and renewal processes (Let's Encrypt and ZeroSSL). It also contains fail2ban for intrusion prevention.

https://docs.linuxserver.io/general/swag/

**Comment by LuizStSantos** [comment]
> Você pode [substituir](https://askubuntu.com/questions/659267/how-do-i-override-or-configure-systemd-services) o serviço ffpapi e adicionar uma nova porta. Ou configure um [proxy](https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/) .
