### ISSUE TITLE
Frontend Build Issue: Git Submodule Commands Not Applicable on Tarballs from Releases

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#538]
The project source code provided in the form of tarballs (tar.gz) in the releases section (https://github.com/ffplayout/ffplayout/releases) does not include the files for building the frontend. During the build process, Git commands such as` 'git submodule update --init'` and `'git submodule update --remote --merge'` cannot be applied to the extracted tarballs.

**Comment by jb-alvarado** [comment]
The source code files (Source code (tar.gz)) comes automatically from github, I don't think I can do something about it.

But the compiled version, link ffplayout-v0.20.4_aarch64-unknown-linux-gnu.tar.gz have the frontend included.
