### ISSUE TITLE
[Enhancement] Playlist

### ISSUE THREAD

**Issue by LuizStSantos** [ffplayout/ffplayout#545]
The possibility of making a subplaylist where I can place it within the playlist scheduler example

Name 
```
rural program
``` 
within this playlist

``` 
opening.mp4
program.mp4
break.mp4
program.mp4
opening.mp4
``` 

within the ffplayout schedule it will only be recognized as rural program [PLAYLIST]

![exemplo 2](https://github.com/ffplayout/ffplayout/assets/73047610/66413e32-1609-4ed0-a548-b0bd90104e9f)
![EXEMPLO](https://github.com/ffplayout/ffplayout/assets/73047610/39ed345c-64f6-4389-b110-08c1edfa951b)

The playlist workspace can only be the scheduler assembly part with file folder and save and copy button

**Comment by jb-alvarado** [comment]
I will not be working on new functions for an indefinite period of time, only on bug fixes. However, pull requests are always welcome if there is a willingness to maintain them.
