### ISSUE TITLE
Animated logo

### ISSUE THREAD

**Issue by C0la149** [ffplayout/ffplayout#547]
Hello everyone, does anyone know how to add a logo with animation? I have it in MP4 format. Is it possible to do this? Or do you need a GIF? Is it also possible to move this logo and make it smaller?

**Comment by tommygothamwest** [comment]
Sure, but fair warning it takes a toll on processing and I haven't been able to manage the required resourced properly myself.

Render your animation logo wherever you want it on the screen. For instance, [I'm using After Effects] set your comp to whatever your video output is in ffplayout (mine is 1920x1080). Place your animated logo in the spot you want it. For instance, I have mine at the top-right corner with a little padding and safe space from the edges. Make sure your animation is loopable (the end and the beginning match up). Render it out and make sure your output has an alpha channel.

Upload that to ffplayout and reference the location in the Processing > Logo field  in settings.

**Comment by C0la149** [comment]
> Sure, but fair warning it takes a toll on processing and I haven't been able to manage the required resourced properly myself.
> 
> Render your animation logo wherever you want it on the screen. For instance, [I'm using After Effects] set your comp to whatever your video output is in ffplayout (mine is 1920x1080). Place your animated logo in the spot you want it. For instance, I have mine at the top-right corner with a little padding and safe space from the edges. Make sure your animation is loopable (the end and the beginning match up). Render it out and make sure your output has an alpha channel.
> 
> Upload that to ffplayout and reference the location in the Processing > Logo field in settings.

@tommygothamwest In what format should I download it? And is it possible to remove the green background? Or should the video be made opaque?  Or do I even need to make a logo with animation in GIF format?

**Comment by C0la149** [comment]
> > @tommygothamwest In what format should I download it? And is it possible to remove the green background? Or should the video be made opaque? Or do I even need to make a logo with animation in GIF format?
> 
> There shouldn't be a green background (I think you're thinking chromakey). This is alpha. Where are you making the animation?

@tommygothamwest Yes, I mean about the chromakey. And so, the Vegas logo was made.

**Comment by tommygothamwest** [comment]
You're going to need to use an application that can render video out using an application that supports alpha channel.

**Comment by C0la149** [comment]
> You're going to need to use an application that can render video out that supports alpha channel.

@tommygothamwest попробую!

**Comment by C0la149** [comment]
> You're going to need to use an application that can render video out that supports alpha channel.

Yes, it works. I saved the video with a transparent background. And everything works! There is animation of the logo. But as you said, I had to put the logo under broadcast permission.
@tommygothamwest
