### ISSUE TITLE
Live broadcast is slow.

### ISSUE THREAD

**Issue by C0la149** [ffplayout/ffplayout#548]
![Снимок экрана 2024-02-24 234740](https://github.com/ffplayout/ffplayout/assets/64633686/802b1e37-5e07-4c04-aa28-c63428d6e0f2)
I have 3 channels there, and 1 of them lags. What to do?

**Comment by C0la149** [comment]
https://github.com/ffplayout/ffplayout/assets/64633686/05841018-17ab-42b6-964c-3227e4cadcb7

No matter how I change the way of broadcasting. Through the restream panel, or ffplayout, the lags do not disappear anyway.

**Comment by LuizStSantos** [comment]
What delays are you talking about?

**Comment by LuizStSantos** [comment]
If it is transmission, the hls_list is very high, only put 10

**Comment by LuizStSantos** [comment]
If it is drop framerate you have to look at which processor you are using to do this I recommend using a video card for this "h264_nvenc"

**Comment by C0la149** [comment]
> If it is transmission, the hls_list is very high, only put 10

I don't think this will help in any way.
I provide you with a screen recording.

https://github.com/ffplayout/ffplayout/assets/64633686/40c858c4-2700-499b-991c-bcfde781571c

**Comment by LuizStSantos** [comment]
> > Se for transmissão, o hls_list é muito alto, coloque apenas 10
> 
> Eu não acho que isso vai ajudar de alguma forma. Eu forneço a você uma gravação de tela.
> 
>  bandicam.2024-02-25.00-39-46-696.mp4

change mode to hls
and try this setting

```

``` 
        -c:v libx264
        -b:v 3250k 
	-maxrate 3250k 
	-bufsize 3250k 
        -preset faster
        -tune zerolatency
        -profile:v Main
        -level 3.1
        -c:a aac
        -ar 44100
        -b:a 128k
        -flags +cgop
        -f hls
        -hls_time 6
        -hls_list_size 10
        -hls_flags append_list+delete_segments+omit_endlist
        -hls_segment_filename /usr/share/ffplayout/public/live/stream-%d.ts
        /usr/share/ffplayout/public/live/stream.m3u8
```

**Comment by LuizStSantos** [comment]
And another if the delay you are talking about is transmission, not fps, the data delay that is transmitting to the other operators is around 30 to 60 seconds

**Comment by LuizStSantos** [comment]
![image](https://github.com/ffplayout/ffplayout/assets/73047610/95530181-35a2-48f1-a8e9-f82232b57911)
I do the same thing as you

**Comment by C0la149** [comment]
> > > Se for transmissão, o hls_list é muito alto, coloque apenas 10
> > 
> > 
> > Eu não acho que isso vai ajudar de alguma forma. Eu forneço a você uma gravação de tela.
> > bandicam.2024-02-25.00-39-46-696.mp4
> 
> change mode to hls and try this setting
> 
> ```
>         -c:v libx264
>         -b:v 3250k 
> 	-maxrate 3250k 
> 	-bufsize 3250k 
>         -preset faster
>         -tune zerolatency
>         -profile:v Main
>         -level 3.1
>         -c:a aac
>         -ar 44100
>         -b:a 128k
>         -flags +cgop
>         -f hls
>         -hls_time 6
>         -hls_list_size 10
>         -hls_flags append_list+delete_segments+omit_endlist
>         -hls_segment_filename /usr/share/ffplayout/public/live/stream-%d.ts
>         /usr/share/ffplayout/public/live/stream.m3u8
> ```

Like this?
![изображение](https://github.com/ffplayout/ffplayout/assets/64633686/a31088be-4c31-48e1-824f-4c0919f6468e)

**Comment by LuizStSantos** [comment]
> > > > Se para transmissão, o hls_list é muito alto, coloque apenas 10
> > > 
> > > 
> > > Eu não acho que isso vai ajudar de alguma forma. Eu forneço a você uma gravação de tela. 
> > > bandicam.2024-02-25.00-39-46-696.mp4
> > 
> > 
> > mude o modo para hls e tente esta configuração
> > ```
> >         -c:v libx264
> >         -b:v 3250k 
> > 	-maxrate 3250k 
> > 	-bufsize 3250k 
> >         -preset faster
> >         -tune zerolatency
> >         -profile:v Main
> >         -level 3.1
> >         -c:a aac
> >         -ar 44100
> >         -b:a 128k
> >         -flags +cgop
> >         -f hls
> >         -hls_time 6
> >         -hls_list_size 10
> >         -hls_flags append_list+delete_segments+omit_endlist
> >         -hls_segment_filename /usr/share/ffplayout/public/live/stream-%d.ts
> >         /usr/share/ffplayout/public/live/stream.m3u8
> > ```
> 
> Assim? ![isolamento](https://private-user-images.githubusercontent.com/64633686/307553373-a31088be-4c31-48e1-824f-4c0919f6468e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4MTE3NTQsIm5iZiI6MTcwODgxMTQ1NCwicGF0aCI6Ii82NDYzMzY4Ni8zMDc1NTMzNzMtYTMxMDg4YmUtNGMzMS00OGUxLTgyNGYtNGMwOTE5ZjY0NjhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDIxNTA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2M2JiZjFiMzY5NjdhYmQwMGJhNzhiNTRjOGRjOWQ3YzE3YWU4MGY4YWU5Y2NhMjg2YTk5ZDlmZWIxNjA1MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m4qE4Xb2Zk9Xcl2WOZC_JWNFungSQoOHva_Uqujzjc0)

the mode where it is stream put hls

**Comment by C0la149** [comment]
> the mode where it is stream put hls


https://github.com/ffplayout/ffplayout/assets/64633686/9f001e65-195a-4a27-a4a6-d91fc23da846

Didn't really help. Most likely the broadcast was broken.

**Comment by LuizStSantos** [comment]
> > o modo onde está o stream coloque hls
> 
>  bandicam.2024-02-25.00-53-54-920.mp4 
> Realmente não ajudou. Provavelmente a transmissão foi interrompida.

Have you seen the error log?

**Comment by LuizStSantos** [comment]
Another way you can do this is to put "stream" mode and transmit to the restreamer via RTMP

![Captura de tela 2024-02-24 191513](https://github.com/ffplayout/ffplayout/assets/73047610/e64d145c-2656-4726-9a31-666ad548c9f7)

```
-c:v libx264
-level 41
-b:v: 6000k
-maxrate: 6500k
-bufsize: 6600k
-delay 0
-c:a aac
-ar 48000
-b:a 128k
-flags +global_header
-f flv "rtmp://key"
```

**Comment by C0la149** [comment]
> Another way you can do this is to put "stream" mode and transmit to the restreamer via RTMP
> 
> ![Captura de tela 2024-02-24 191513](https://private-user-images.githubusercontent.com/73047610/307554388-e64d145c-2656-4726-9a31-666ad548c9f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4MTMyOTQsIm5iZiI6MTcwODgxMjk5NCwicGF0aCI6Ii83MzA0NzYxMC8zMDc1NTQzODgtZTY0ZDE0NWMtMjY1Ni00NzI2LTlhMzEtNjY2YWQ1NDhjOWY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDIyMTYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4ZTc1ZWMyYTUyNWUzYzg5ZGU1YzdlN2Y5ZjA5Y2ZhNmI0NGJkMTAwYTUzNTE0MDk5ODM1MTViYzJiODg3MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KNxXDNYTK5QPOUx_sgfaFmGzHWXse2cPAg5A_3ffGrE)
> 
> ```
> -c:v libx264
> -level 41
> -b:v: 6000k
> -maxrate: 6500k
> -bufsize: 6600k
> -delay 0
> -c:a aac
> -ar 48000
> -b:a 128k
> -flags +global_header
> -f flv "rtmp://key"
> ```


https://github.com/ffplayout/ffplayout/assets/64633686/ccf285a4-1df3-4c26-89c0-5ba352a034d6

**Comment by C0la149** [comment]
Are there any other options?

**Comment by JunioCalu** [comment]
> I have 3 channels there, and 1 of them lags. What to do?

Several performance factors are involved in your issue; your CPU appears to be an AMD model, which might be less powerful than an Intel CPU. In my case, I have two channels, and they perform well without much delay in transmission. As for the freezes in the restreamer, I also experience them, but they do not interfere with the broadcast end (YouTube, VK, Twitch, etc.). To improve performance, in some cases, it's necessary to lower the transmission resolution to 720p or lower. In your case, having three channels requires a more powerful hardware setup than average. The additional processing load could be reduced by using hardware acceleration through legacy vaapi codecs or more current h264_qsv codecs for onboard video cards (Intel or AMD) or the h264_nvenc codec for offboard video cards.

https://trac.ffmpeg.org/wiki/Hardware/QuickSync

https://trac.ffmpeg.org/wiki/Hardware/VAAPI

https://docs.nvidia.com/video-technologies/video-codec-sdk/12.0/ffmpeg-with-nvidia-gpu/index.html

**Comment by C0la149** [comment]
> > I have 3 channels there, and 1 of them lags. What to do?
> 
> Several performance factors are involved in your issue; your CPU appears to be an AMD model, which might be less powerful than an Intel CPU. In my case, I have two channels, and they perform well without much delay in transmission. As for the freezes in the restreamer, I also experience them, but they do not interfere with the broadcast end (YouTube, VK, Twitch, etc.). To improve performance, in some cases, it's necessary to lower the transmission resolution to 720p or lower. In your case, having three channels requires a more powerful hardware setup than average. The additional processing load could be reduced by using hardware acceleration through legacy vaapi codecs or more current h264_qsv codecs for onboard video cards (Intel or AMD) or the h264_nvenc codec for offboard video cards.
> 
> https://trac.ffmpeg.org/wiki/Hardware/QuickSync
> 
> https://trac.ffmpeg.org/wiki/Hardware/VAAPI
> 
> https://docs.nvidia.com/video-technologies/video-codec-sdk/12.0/ffmpeg-with-nvidia-gpu/index.html

If we take into account 3 channels that operate at 1080p 30 fps, then I don’t know. The 8-core processor is only 60~70 percent loaded. But why does it still lag?
@JunioCalu

**Comment by C0la149** [comment]
Yes, and if you take it into account. This is a VDS, well, a server without a video card. But in theory, everything should go perfectly in terms of broadcasting. I checked 1 channel 1080p 30 fps and everything is going fine, but if I launch 3 channels then freezing occurs on the live broadcast.
@JunioCalu

**Comment by JunioCalu** [comment]
> If we take into account 3 channels that operate at 1080p 30 fps, then I don’t know. The 8-core processor is only 60~70 percent loaded. But why does it still lag? @JunioCalu

Lower the resolutions of the 3 channels to 720p. I recommend switching to a server that has an Intel CPU.

**Comment by C0la149** [comment]
> > If we take into account 3 channels that operate at 1080p 30 fps, then I don’t know. The 8-core processor is only 60~70 percent loaded. But why does it still lag? @JunioCalu
> 
> Lower the resolutions of the 3 channels to 720p. I recommend switching to a server that has an Intel CPU.

I don't think it would be a good idea to replace a server with an Intel processor. The result is much worse.
The most optimal thing I have at the moment is this:
AMD Ryzen 9 5950X (8 cores) @ 3.393GHz
8 GB RAM
Is it possible to do it somehow without reducing the quality of the broadcasts?

**Comment by C0la149** [comment]
Yes, and if we are talking about changing a server with an Intel processor. then what kind of processor do I need for my purposes?
@JunioCalu

**Comment by JunioCalu** [comment]
> I don't think it would be a good idea to replace a server with an Intel processor. The result is much worse. The most optimal thing I have at the moment is this: AMD Ryzen 9 5950X (8 cores) @ 3.393GHz 8 GB RAM Is it possible to do it somehow without reducing the quality of the broadcasts? @JunioCalu

Check if the processor has an integrated GPU:

```bash
sudo apt-get update
sudo apt-get install vainfo mesa-va-drivers

vainfo
```

I also recommend looking into whether your server supports hardware acceleration, which you can check by reviewing the first two links in my previous comment.

**Comment by C0la149** [comment]
> > I don't think it would be a good idea to replace a server with an Intel processor. The result is much worse. The most optimal thing I have at the moment is this: AMD Ryzen 9 5950X (8 cores) @ 3.393GHz 8 GB RAM Is it possible to do it somehow without reducing the quality of the broadcasts? @JunioCalu
> 
> Check if the processor has an integrated GPU:
> 
> ```shell
> sudo apt-get update
> sudo apt-get install vainfo mesa-va-drivers
> 
> vainfo
> ```
> 
> I also recommend looking into whether your server supports hardware acceleration, which you can check by reviewing the first two links in my previous comment.

![изображение](https://github.com/ffplayout/ffplayout/assets/64633686/edbf8eea-a9e8-4e00-a8fb-653c7bcdaa7c)
![изображение](https://github.com/ffplayout/ffplayout/assets/64633686/f3c6af22-5dee-4792-870d-63db010663fb)

**Comment by C0la149** [comment]
@JunioCalu 
![изображение](https://github.com/ffplayout/ffplayout/assets/64633686/54d12f36-c12b-466c-a950-b29727c04f67)
I provide you with the current load at the moment.
![изображение](https://github.com/ffplayout/ffplayout/assets/64633686/c90e68fb-fd24-44a0-a33c-efce8821e43b)

**Comment by JunioCalu** [comment]
From what I've researched about your CPU model, it is not an APU. AMD processors that support an integrated GPU are known as APUs (Accelerated Processing Units). These units combine a traditional CPU with a Radeon GPU on the same chip. Therefore, it does not support hardware acceleration in ffmpeg. To confirm, I recommend you search the web to see if your specific CPU model has an integrated GPU.

**Comment by C0la149** [comment]
I thought it was unlikely that the GPU would be there. This is VDS. It is unlikely that this will happen there. What can you think of?
@JunioCalu

**Comment by C0la149** [comment]
![изображение](https://github.com/ffplayout/ffplayout/assets/64633686/4dd9b95b-1c7a-4b6f-94b8-1dc74f54dcab)
@JunioCalu

**Comment by JunioCalu** [comment]
> Yes, and if we are talking about changing a server with an Intel processor. then what kind of processor do I need for my purposes? @JunioCalu

So far, I haven't worked with your workload (three TV channels), so I don't have empirical experience to accurately state which hardware configuration is most suitable in your case. But in all cases, it's always better to work with a dedicated GPU, Nvidia or another option. Regarding the Intel processor, I think perhaps a processor with 8 cores or more, supporting Intel Quick Sync Video hardware acceleration, would do the job.

**Comment by C0la149** [comment]
> So far, I haven't worked with your workload (three TV channels), so I don't have empirical experience to accurately state which hardware configuration is most suitable in your case. But in all cases, it's always better to work with a dedicated GPU, Nvidia or another option. Regarding the Intel processor, I think perhaps a processor with 8 cores or more, supporting Intel Quick Sync Video hardware acceleration, would do the job.

@JunioCalu 
I certainly don't have the option to use an Intel processor at the moment. But I will take this fact into account. But could the problem be due to my incorrect ffplayout settings?
If you have a telegram, then one of these days we can check all this together in practice so that you can understand in more detail what is missing.

**Comment by JunioCalu** [comment]
> @JunioCalu I certainly don't have the option to use an Intel processor at the moment. But I will take this fact into account. But could the problem be due to my incorrect ffplayout settings? If you have a telegram, then one of these days we can check all this together in practice so that you can understand in more detail what is missing.

I think the best solution for now is to lower the video resolution and FPS (to 25, which is standard). If you haven't made many changes to the default settings of ffplayout, I don't think there's much to be done. My Telegram nick is the same as my GitHub one, you can leave a message, I'll respond when I have time.

**Comment by C0la149** [comment]
I wrote to you in a telegram.
Here are my broadcast settings.
@JunioCalu 
![изображение](https://github.com/ffplayout/ffplayout/assets/64633686/7163bcd0-9123-4ce1-baf1-b56cb94c2018)
These settings are available everywhere, on all channels.

**Comment by LuizStSantos** [comment]
Oops I'm back I had to leave
Cadu said an important point, I myself am using datarhei with an old DELL T110 II server
My stream pc is an i7 12700k 16 GB DDR6 RAM and a Quadro T400 video card

**Comment by C0la149** [comment]
> Oops I'm back I had to leave
> Cadu said an important point, I myself am using datarhei with an old DELL T110 II server
> My stream pc is an i7 12700k 16 GB DDR6 RAM and a Quadro T400 video card

Hmm, what does that mean then?
@LuizStSantos

**Comment by LuizStSantos** [comment]
> > Opa, voltei, tive que sair 
> > Cadu falou um ponto importante, eu mesmo estou usando datarhei com um servidor DELL T110 II antigo 
> > Meu stream pc é um i7 12700k 16 GB de RAM DDR6 e uma placa de vídeo Quadro T400
> 
> Hmm, o que isso significa então? @LuizStSantos

This is an example that I use without problems, but following the information from Cadu and your processor does not have integrated video, it could be one of the problems, he will have a better idea of ​​what could be happening

**Comment by LuizStSantos** [comment]
> Mas você consegue realmente pensar em alguma coisa? @LuizStSantos


I have some questions?
Is your Datarhei software on the same machine as ffplayout, if not what machine is it on?

**Comment by C0la149** [comment]
Yes. That's right. ffplayout is in the same place as restreamer. On one VDS.
@LuizStSantos

**Comment by LuizStSantos** [comment]
> Sim. Isso mesmo. ffplayout está no mesmo lugar que restreamer. Em um VDS. @LuizStSantos

We have a small problem, datarhei restreamer uses libx264, and ffpllayout is also using it, and because your machine does not have integrated video it may be causing this problem, think of datarhei restremaer as a game and CSGO and FFPLAYOUT and LOL both being executed at the same time, this would be causing the bottleneck that causes this problem to occur, that would be my intuition, but it could be another

**Comment by C0la149** [comment]
Hmm, well, if this is really the case, then let’s install the panel on another server and check it for real.
@LuizStSantos

**Comment by LuizStSantos** [comment]
> Hmm, bem, se for realmente esse o caso, então vamos instalar o painel em outro servidor e verificar de verdade. @LuizStSantos

Yes you can take this test

**Comment by C0la149** [comment]
I moved the panel to another server. Yes, it gave results. but not for long, when checking 2 channels out of 3 channels, they lag. Well, there are lags, like it loads and then it just runs normally. And then it loads again. It seems like there are fewer lags, but I’ll say it didn’t really help.
@LuizStSantos

**Comment by C0la149** [comment]
If you have a telegram, I can show you in more detail what it looks like. This is simply a weight limit based on file size.
@LuizStSantos

**Comment by cooliobr** [comment]
![Captura de Tela 2024-02-29 às 19 58 11](https://github.com/ffplayout/ffplayout/assets/4358538/b86dfcfa-8d02-4497-817d-c49046b1b3bc)
![Captura de Tela 2024-02-29 às 19 59 47](https://github.com/ffplayout/ffplayout/assets/4358538/cced02b8-b89f-4673-aab8-30d8bcd23501)
I made some modifications to my version to work with acceleration on input

**Comment by JunioCalu** [comment]
> I made some modifications to my version to work with acceleration on input

Does the current version of FFplayout support acceleration on input?

**Comment by cooliobr** [comment]
> > I made some modifications to my version to work with acceleration on input
> 
> Does the current version of FFplayout support acceleration on input?

yes, I can do modifications and give access.

**Comment by JunioCalu** [comment]
> > > I made some modifications to my version to work with acceleration on input
> > 
> > 
> > Does the current version of FFplayout support acceleration on input?
> 
> yes, I can do modifications and give access.
> 
> this is my old [cooliobr@071bddf](https://github.com/cooliobr/ffplayout2/commit/071bddf0b9e8ed91fa35dd5b75a91e8e12c2e16a)

Great, I will apply your customization here later. Does limiting the number of threads to 4 improve processing performance? Wouldn't it be better to use "-threads 0"? You are decoding (-hwaccel", "cuvid") with hw acceleration and re-encoding (h264_cuvid) the output. Wouldn't it be better to just re-encode the output?

**Comment by cooliobr** [comment]
> Great, I will apply your customization here later. Does limiting the number of threads to 4 improve processing performance? Wouldn't it be better to use "-threads 0"? You are decoding (-hwaccel", "cuvid") with hw acceleration and re-encoding (h264_cuvid) the output. Wouldn't it be better to just re-encode the output?

The h264_cuvid codec isn't for output; it's for specifying the input codec of the video. I could have left it blank to support more types of input videos, but I only have h264. As for the output, I also need to modify some things in the filters. My final ffplayout call looks like this: "ffmpeg -hide_banner -threads 4 -hwaccel cuvid -c:v h264_cuvid -fix_sub_duration -drop_second_field true -nostats -v level+error -stream_loop 6 -i /var/lib/ffplayout/media1G/hm/SPOT/HALLO_MOVIES_NEW.mp4 -t 60 -filter_complex [0:v:0]scale_npp=format=yuv420p,scale_npp=1280:720:interp_algo=super:force_original_aspect_ratio=decrease,hwdownload,pad=1280:720:(ow-iw)/2:(oh-ih)/2:color=black,setdar=16:9,setsar=1:1,hwupload[v];movie=/usr/share/ffplayout/HALLO_Movies_2.png[l0];[l0]format=rgba,colorchannelmixer=aa=0.7,scale=iw*0.4:-1,hwupload_cuda[l];[v][l]overlay_cuda=main_w-overlay_w-50:33,realtime=speed=1.0004316593661566[vout0];[0:a:0]anull[aout0] -map [vout0] -map [aout0] -c:v h264_nvenc -aspect 16:9 -r:v 30 -b:v 2200k -maxrate 2700k -bufsize 3100k -profile:v main -preset p4 -level 41 -delay 0 -ar 48000 -b:a 128k -c:a libfdk_aac -muxdelay 0 -colorspace:v bt709 -color_primaries:v bt709 -color_trc:v bt709 -color_range:v tv -f hls -hls_time 6 -hls_list_size 10 -g 60 -keyint_min 60 -hls_flags second_level_segment_index+append_list+omit_endlist+delete_segments+program_date_time -strftime 1 -hls_segment_filename /usr/share/ffplayout/public/live/ch3/stream-%v-%%04d.ts /usr/share/ffplayout/public/live/ch3/playlist.m3u8" Regarding the threads, I really limited them to be able to add more channels, and this way was smoother. I have another server with 16 channels working fine.

**Comment by JunioCalu** [comment]
> The h264_cuvid codec isn't for output; it's for specifying the input codec of the video. I could have left it blank to support more types of input videos, but I only have h264. As for the output, I also need to modify some things in the filters. My final ffplayout call looks like this: "ffmpeg -hide_banner -threads 4 -hwaccel cuvid -c:v h264_cuvid -fix_sub_duration -drop_second_field true -nostats -v level+error -stream_loop 6 -i /var/lib/ffplayout/media1G/hm/SPOT/HALLO_MOVIES_NEW.mp4 -t 60 -filter_complex [0:v:0]scale_npp=format=yuv420p,scale_npp=1280:720:interp_algo=super:force_original_aspect_ratio=decrease,hwdownload,pad=1280:720:(ow-iw)/2:(oh-ih)/2:color=black,setdar=16:9,setsar=1:1,hwupload[v];movie=/usr/share/ffplayout/HALLO_Movies_2.png[l0];[l0]format=rgba,colorchannelmixer=aa=0.7,scale=iw*0.4:-1,hwupload_cuda[l];[v][l]overlay_cuda=main_w-overlay_w-50:33,realtime=speed=1.0004316593661566[vout0];[0:a:0]anull[aout0] -map [vout0] -map [aout0] -c:v h264_nvenc -aspect 16:9 -r:v 30 -b:v 2200k -maxrate 2700k -bufsize 3100k -profile:v main -preset p4 -level 41 -delay 0 -ar 48000 -b:a 128k -c:a libfdk_aac -muxdelay 0 -colorspace:v bt709 -color_primaries:v bt709 -color_trc:v bt709 -color_range:v tv -f hls -hls_time 6 -hls_list_size 10 -g 60 -keyint_min 60 -hls_flags second_level_segment_index+append_list+omit_endlist+delete_segments+program_date_time -strftime 1 -hls_segment_filename /usr/share/ffplayout/public/live/ch3/stream-%v-%%04d.ts /usr/share/ffplayout/public/live/ch3/playlist.m3u8" Regarding the threads, I really limited them to be able to add more channels, and this way was smoother. I have another server with 16 channels working fine.

I see, there is a notable difference in the filter configuration. I presume that the drawtext filter for subtitle insertion in conjunction with zmq does not work in this configuration, or did you not find it interesting to keep it?

**Comment by cooliobr** [comment]
> > The h264_cuvid codec isn't for output; it's for specifying the input codec of the video. I could have left it blank to support more types of input videos, but I only have h264. As for the output, I also need to modify some things in the filters. My final ffplayout call looks like this: "ffmpeg -hide_banner -threads 4 -hwaccel cuvid -c:v h264_cuvid -fix_sub_duration -drop_second_field true -nostats -v level+error -stream_loop 6 -i /var/lib/ffplayout/media1G/hm/SPOT/HALLO_MOVIES_NEW.mp4 -t 60 -filter_complex [0:v:0]scale_npp=format=yuv420p,scale_npp=1280:720:interp_algo=super:force_original_aspect_ratio=decrease,hwdownload,pad=1280:720:(ow-iw)/2:(oh-ih)/2:color=black,setdar=16:9,setsar=1:1,hwupload[v];movie=/usr/share/ffplayout/HALLO_Movies_2.png[l0];[l0]format=rgba,colorchannelmixer=aa=0.7,scale=iw*0.4:-1,hwupload_cuda[l];[v][l]overlay_cuda=main_w-overlay_w-50:33,realtime=speed=1.0004316593661566[vout0];[0:a:0]anull[aout0] -map [vout0] -map [aout0] -c:v h264_nvenc -aspect 16:9 -r:v 30 -b:v 2200k -maxrate 2700k -bufsize 3100k -profile:v main -preset p4 -level 41 -delay 0 -ar 48000 -b:a 128k -c:a libfdk_aac -muxdelay 0 -colorspace:v bt709 -color_primaries:v bt709 -color_trc:v bt709 -color_range:v tv -f hls -hls_time 6 -hls_list_size 10 -g 60 -keyint_min 60 -hls_flags second_level_segment_index+append_list+omit_endlist+delete_segments+program_date_time -strftime 1 -hls_segment_filename /usr/share/ffplayout/public/live/ch3/stream-%v-%%04d.ts /usr/share/ffplayout/public/live/ch3/playlist.m3u8" Regarding the threads, I really limited them to be able to add more channels, and this way was smoother. I have another server with 16 channels working fine.
> 
> I see, there is a notable difference in the filter configuration. I presume that the drawtext filter for subtitle insertion in conjunction with zmq does not work in this configuration, or did you not find it interesting to keep it?

I've never used drawtext, but it's possible to maintain it. You can upload and download the GPU to process it in different ways.

this example can help 
ffmpeg 
    -hwaccel_device 0              
    -hwaccel cuvid                
    -c:v h264_cuvid
    -i $sourcePath 
    -vf hwdownload,format=nv12,drawtext=text='$txt':fontfile='$fontPath':fontcolor='red':fontsize='40':x=w-mod(max(t-1\,0)*(w+tw)/30\,(w+tw)):y=main_h/2,hwupload
    -acodec copy 
    $targetPath

**Comment by cooliobr** [comment]
https://superuser.com/questions/1730420/ffmpeg-rotate-drawtext-with-hwaccel

**Comment by JunioCalu** [comment]
> this example can help ffmpeg -hwaccel_device 0 -hwaccel cuvid -c:v h264_cuvid -i $sourcePath -vf hwdownload,format=nv12,drawtext=text='$txt':fontfile='$fontPath':fontcolor='red':fontsize='40':x=w-mod(max(t-1,0)*(w+tw)/30,(w+tw)):y=main_h/2,hwupload -acodec copy $targetPath

Thank you for the example! I was indeed having a doubt about how to configure it in the most efficient way.

**Comment by LuizStSantos** [comment]
@jb-alvarado I liked this idea of ​​using cuda acceleration, I would have the possibility of installing it with the option of these parameters, for example "apt install /tmp/ffplayout_<VERSION>_amd64.deb --cuda"

**Comment by jb-alvarado** [comment]
I'm not against GPU features in ffplayout, but I'm not so skilled in that area and last time when I have look to it I found it very difficult to found good solutions. ffmpeg provides different types of GPU decoder/encoder/filters and not all of them brings always a benefit. I had tests where some of them performed more bad then CPU.

Then the other question is: how to support all kinds of GPU types, sticking only on NVIDIA is not convenient for all users.

I personally would tent to something like an advanced config file, where user can set special decoding an filtering option. In that way, I would let things untouched for normal users, but give more power to advanced users.

**Comment by LuizStSantos** [comment]
> I'm not against GPU features in ffplayout, but I'm not so skilled in that area and last time when I have look to it I found it very difficult to found good solutions. ffmpeg provides different types of GPU decoder/encoder/filters and not all of them brings always a benefit. I had tests where some of them performed more bad then CPU.
> 
> Then the other question is: how to support all kinds of GPU types, sticking only on NVIDIA is not convenient for all users.
> 
> I personally would tent to something like an advanced config file, where user can set special decoding an filtering option. In that way, I would let things untouched for normal users, but give more power to advanced users.

The option where we define it ourselves would be great, and so normal users can simply install and use it normally while advanced users can define it. I really liked the idea
