### ISSUE TITLE
System restart modal dialog does not work on additional channels.

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#550]
**Describe the bug**

I created a second channel for testing and found that the modal dialog for system restart after changes in the configuration file does not work.

![Screenshot_20240228_110638](https://github.com/ffplayout/ffplayout/assets/8952225/2949bae1-3e6d-49b7-844b-7deb438b7476)

**Desktop/Server/Software:**

 - OS: Manjaro 23.1.3
- ffplayout 0.20.5
- ffmpeg 6.1.1
- are you using the current master of ffplayout? Yes

**Config Settings:**

- command line arguments
- config file: [ffplayout.0.20.5.yml.txt](https://github.com/ffplayout/ffplayout/files/14434245/ffplayout.0.20.5.yml.txt)

**Logging:**

- content of:  [ffplayout.log.0.20.5.txt](https://github.com/ffplayout/ffplayout/files/14434200/ffplayout.log.0.20.5.txt)

**Comment by jb-alvarado** [comment]
Was this channel running? The modal pops up only if the playout is running.

**Comment by JunioCalu** [comment]
> Was this channel running? The modal pops up only if the playout is running.

You're right, I had tested with the second channel stopped. I started the channel and the modal dialog worked.
