### ISSUE TITLE
Debug log level does not work for the live ingest function

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#551]
**Describe the bug**

As can be seen in the images below, I set the "debug" level for live ingest, but the setting is not applied; the level remains "info".

![Screenshot_20240228_152725](https://github.com/ffplayout/ffplayout/assets/8952225/2a137373-9ed5-4f10-85e8-9f50bc21d771)

![Screenshot_20240228_152103](https://github.com/ffplayout/ffplayout/assets/8952225/f2eddd16-c8da-4969-99c0-3e80a144aa3c)

**Desktop/Server/Software:**

 - OS: Manjaro 23.1.3
- ffplayout 0.20.5
- ffmpeg 6.1.1
- are you using the current master of ffplayout? Yes

**Config Settings:**

- command line arguments
- config file: [ffplayout.0.20.5.yml.txt](https://github.com/ffplayout/ffplayout/files/14434245/ffplayout.0.20.5.yml.txt)

**Logging:**

- content of:  [ffplayout.log.0.20.5.txt](https://github.com/ffplayout/ffplayout/files/14434200/ffplayout.log.0.20.5.txt)

**Comment by jb-alvarado** [comment]
The help text says that `ffmpeg_level` can be **info, warning, error**, same matches for `ingest_level`. I updated the help text.

**Comment by JunioCalu** [comment]
I think having a debug level in live_ingest mode would be useful too, but okay.

**Comment by JunioCalu** [comment]
> The help text says that `ffmpeg_level` can be **info, warning, error**, same matches for `ingest_level`. I updated the help text.

I have just found out that the warning and error levels also do not work for live ingest.

**Comment by jb-alvarado** [comment]
How did you find out, that is not working? `level+info` is hard coded, but ffplayout should print messages according to the given level.

**Comment by JunioCalu** [comment]
> How did you find out, that is not working? `level+info` is hard coded, but ffplayout should print messages according to the given level.

I applied the configuration changes in the web interface, then restarted the system. But as can be seen in the sequence of images below, the web interface configuration is not being applied.

![Screenshot_20240301_083510](https://github.com/ffplayout/ffplayout/assets/8952225/fede11f5-fb6e-475f-ae80-09d7c459cf37)

![Screenshot_20240301_083407](https://github.com/ffplayout/ffplayout/assets/8952225/40357c4c-f7f4-442d-9a35-6bfc85bc1f33)

**Comment by jb-alvarado** [comment]
Yes, that is what I say ;-), is hard coded, but it will filter messages according to you given level: https://github.com/ffplayout/ffplayout/blob/84653e3b12988d95dae60ee56c32d565392d59ff/ffplayout-engine/src/utils/mod.rs#L135-L153

The engine need infos from logging to prevent unauthorized streams be published, and that I only get with log level+info. But your to your log file or console should print only the given level.

**Comment by JunioCalu** [comment]
> The engine need infos from logging to prevent unauthorized streams be published, and that I only get with log level+info. But to your log file or console should print only the given level.

I understand now.
