### ISSUE TITLE
Broadcast failure. It is impossible to play a video file on live.

### ISSUE THREAD

**Issue by C0la149** [ffplayout/ffplayout#556]
ffplayout cannot play the video file properly. Writes this.
![изображение](https://github.com/ffplayout/ffplayout/assets/64633686/265d8141-ffe6-4be5-94d4-67c5fada4e06)
![изображение](https://github.com/ffplayout/ffplayout/assets/64633686/65b47137-7584-46bc-943d-e2fa896e8fe0)
![изображение](https://github.com/ffplayout/ffplayout/assets/64633686/a5612dd5-beb3-427b-a3d4-a12519f963a0)
![изображение](https://github.com/ffplayout/ffplayout/assets/64633686/a914fc32-2bad-4d36-b9dc-57591cd4652c)
![изображение](https://github.com/ffplayout/ffplayout/assets/64633686/4384707b-6995-4716-9aa9-83137e08ce7a)

**Comment by jb-alvarado** [comment]
Maybe the file has some issues? Can you play it normal with ffplay?

**Comment by C0la149** [comment]
Everything is fine with the file, it also cannot play other files. And what does it mean to lose using ffplay?
@jb-alvarado 
I would continue this topic, but I’m wondering how we can raise ffplayout. It's broken for me.
https://github.com/ffplayout/ffplayout/issues/557

**Comment by C0la149** [comment]
![изображение](https://github.com/ffplayout/ffplayout/assets/64633686/9d23a10f-cd47-48cd-a874-c06187f89433)

**Comment by jb-alvarado** [comment]
> And what does it mean to lose using ffplay?

ffplay is a command line player which comes with ffmpeg. When the file can be played there (completely) the chance is high, that ffmpeg and so also ffplayout can handle it.

Beside that it would be helpful, when you provide more logging informations. But please as text in a code block, not as a screenshot. Code blocks starts and end with: **```**

**Comment by C0la149** [comment]
How can I play this file using ffplay?
@jb-alvarado

**Comment by C0la149** [comment]
@jb-alvarado 
I tried something. It seems like it



root@ColaServer:/Video/Torrent# ffplay Artur.I.Miniputy.2007.RUS.BDRip.XviD.AC3.-HQ-ViDEO.avi
ffplay version 5.1.4-0+deb12u1 Copyright (c) 2003-2023 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr --extra-version=0+deb12u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
pci id for fd 15: 1234:1111, driver (null)
MESA-LOADER: failed to open bochs-drm: /usr/lib/dri/bochs-drm_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
failed to load driver: bochs-drm
pci id for fd 16: 1234:1111, driver (null)
kmsro: driver missing
Failed to create window or renderer: EGL not initialized
root@ColaServer:/Video/Torrent#

**Comment by jb-alvarado** [comment]
Just run: `ffplay /path/to/file.avi`, but muxt be local, not on your server. There is also so [shortcuts](https://ffmpeg.org/ffplay.html#While-playing) you can use.

If you have to test the file remote, you could run something like: `ffmpeg -i file.avi -c:v libx264 -preset veryfast -f null -`

**Comment by C0la149** [comment]
@jb-alvarado 
[ffplayout_file.txt](https://github.com/ffplayout/ffplayout/files/14484502/ffplayout_file.txt)

**Comment by C0la149** [comment]
What can you say?
@jb-alvarado

**Comment by C0la149** [comment]
@jb-alvarado 
[filevideo.txt](https://github.com/ffplayout/ffplayout/files/14498516/filevideo.txt)
I also noticed another file that ffplayout could not play. Here I present it to you.

**Comment by C0la149** [comment]
@jb-alvarado What can you say about this? What should I do in my case?

**Comment by jb-alvarado** [comment]
When is only some files that are not playing, then the best is to try to recompress in a new format, when they are not to corrupt.

**Comment by C0la149** [comment]
@jb-alvarado So these files are normal. Not damaged. But not every file can be converted to a different format...

**Comment by C0la149** [comment]
@jb-alvarado So these files are normal. Not damaged. But not every file can be converted to a different format...

**Comment by jb-alvarado** [comment]
ffplayout just needs files that ffmpeg can handle. ffmpeg with all its libraries can handle a lot of formats and codec.

You can try this files: https://github.com/ffplayout/ffplayout/tree/master/tests/assets/media_sorted

When playout works with this ones, the chance is high that something is wrong with your files, or you ffmpeg version.

**Comment by C0la149** [comment]
I'll actually check your files. But how can my files be broken? If I downloaded them from the server to my main laptop and everything opens fine from the laptop.

**Comment by C0la149** [comment]
@jb-alvarado I can give you these files for testing.

**Comment by jb-alvarado** [comment]
Maybe they have an old codec, or little errors that a not come up on playing. I really don't know.

**Comment by C0la149** [comment]
@jb-alvarado I can give you the files to test. So you can make sure that they don't work.

**Comment by C0la149** [comment]
Should I give you these files? @jb-alvarado

**Comment by jb-alvarado** [comment]
Sorry, I don't have the capacity for that kind of support. When other files are working, then is not an ffplayout issue. You can compress that file in a h264/mp4 and test again. Then you will see, it that was the case.

**Comment by C0la149** [comment]
Yes, even if I do compression. What will this change? Not all files are compressed this way every time. Come up with something, or fix it in an update. I have no more options. Think about it somehow. Yes, even I will check the files a little later that were not played in ffplayout By ffmpeg. And I’ll try to run the file on air for a test. And I'll record it on video. @jb-alvarado

**Comment by jb-alvarado** [comment]
I have tried to explain this to you, there is not much I can do, there are no updates from ffplayout. I develop ffplayout and not ffmpeg. ffplayout uses ffmpeg to decode and encode and if ffmpeg can't read a file properly, it looks bad. I also have files from 2013 that have defects, sometimes I'm lucky and they still play, with artifacts and others it crashes.

I also don't think you need to recompress all the files, but maybe some of them do. 

There are various tools on the internet to check the videos, e.g.: https://github.com/nhershy/CorruptVideoFileInspector
Just give it a try.

**Comment by C0la149** [comment]
@jb-alvarado 
Where can I find the ffplayout log file? I also provide you with a record that everything is working correctly with ffmpeg. Of course, ChatGPT helped me, but still.

https://github.com/ffplayout/ffplayout/assets/64633686/242c60fb-b95e-45ea-9dac-5bcfc450b666

 ffmpeg -re -i Bleyd.1998.BDRip.DVO-TV1000.avi -c:v libx264 -preset veryfast -tune zerolatency -c:a aac -strict experimental -f flv 
 
Perhaps he started using other codes. But why don’t you add this too?

![изображение](https://github.com/ffplayout/ffplayout/assets/64633686/e7b8c0d0-a641-44bf-8026-f0bb3dc18159)
![изображение](https://github.com/ffplayout/ffplayout/assets/64633686/ea2d046b-e20c-4c12-adba-590f209b42b6)

**Comment by C0la149** [comment]
I just checked another file. There's no sound there. Right now I’m downloading the file from the server to make sure that everything is okay with it.
@jb-alvarado 

https://github.com/ffplayout/ffplayout/assets/64633686/d4537411-f0f7-4194-93ad-65d3deb49000

**Comment by C0la149** [comment]
@jb-alvarado 

https://github.com/ffplayout/ffplayout/assets/64633686/661b90d9-6e05-4fef-92f3-6adef767e3d7

I just downloaded a file from the server. And I checked it on my laptop, there is sound. The file is not broken.

**Comment by jb-alvarado** [comment]
> @jb-alvarado Where can I find the ffplayout log file? 

Is under `/var/log/ffplayout` need to be that file where the error exists.

You can also post you config again.

**Comment by C0la149** [comment]
[ffplayout.log](https://github.com/ffplayout/ffplayout/files/14549776/ffplayout.log)

**Comment by C0la149** [comment]
@jb-alvarado

**Comment by jb-alvarado** [comment]
You don't need to add my name to every post.

The content of the log says not much, only the end is interesting, but then there is more logging missing. 

The message: `Failed to spawn ffmpeg/ffprobe. stream did not contain valid UTF-8` can be understand in that way, the the first part `Failed to spawn ffmpeg/ffprobe` comes from ffplayout, which says that it can not start the ffmpeg process, because of the second part `stream did not contain valid UTF-8` which says that something is not right with the file. Maybe the metadata has issues, or filename, or there is a bad subtitle.

For the future please also pay attention to the [contribution guideline](https://github.com/ffplayout/ffplayout/blob/master/CONTRIBUTING.md).
