### ISSUE TITLE
The entire ffplayout does not start.

### ISSUE THREAD

**Issue by C0la149** [ffplayout/ffplayout#557]
After I started clearing the playlist live and thereby broadcasting to ffplayout itself via OBS, then after clearing the playlist and saving everything disappeared.
![изображение](https://github.com/ffplayout/ffplayout/assets/64633686/11330865-0f1e-4a46-92c9-b8673f33ca3c)
![изображение](https://github.com/ffplayout/ffplayout/assets/64633686/6f691c42-7508-474e-a7f5-64974de8fabf)
![изображение](https://github.com/ffplayout/ffplayout/assets/64633686/b442d714-7bd9-4ce9-8a2a-e9c5c7e7dd72)
And after restarting the VDS, ffplayout does not start at all.
![изображение](https://github.com/ffplayout/ffplayout/assets/64633686/ef55ca4f-82bf-4b0f-94f8-752dac220a7b)
![изображение](https://github.com/ffplayout/ffplayout/assets/64633686/0c445c6b-7972-45a1-87f4-32c1fb37b7bd)

**Comment by C0la149** [comment]
![изображение](https://github.com/ffplayout/ffplayout/assets/64633686/1cf65cd7-9a16-4044-bf91-aa551a722a35)
I tried to restart. Did not work out.

**Comment by C0la149** [comment]
Version ffplayout 0.20.5

**Comment by jb-alvarado** [comment]
What says: `ls -alh /etc/ffplayout`? and how is the content of `/etc/ffplayout/ffplayout.yml`?

**Comment by C0la149** [comment]
@jb-alvarado 
![изображение](https://github.com/ffplayout/ffplayout/assets/64633686/7da57cb5-5484-4214-9c8f-696f052738f1)
![изображение](https://github.com/ffplayout/ffplayout/assets/64633686/be54a078-b43f-460a-aabe-9f6fca4efd95)

**Comment by C0la149** [comment]
![изображение](https://github.com/ffplayout/ffplayout/assets/64633686/27aecce7-0d78-404d-962e-7c5a9772e73a)

**Comment by jb-alvarado** [comment]
To be honest, I'm at a bit of a loss. I suspect that the config has an error. Either it is damaged or it cannot be read correctly because a parameter is incorrect. This could happen if you edit it manually.

You could start ffplayout directly from the terminal, if you get a panic because of the config, you either have to repair the file or replace it with the original.

**Comment by C0la149** [comment]
I didn't edit it manually. I can provide you with the complete file.
@jb-alvarado

**Comment by C0la149** [comment]
[ffplayout.zip](https://github.com/ffplayout/ffplayout/files/14477950/ffplayout.zip)

**Comment by C0la149** [comment]
@jb-alvarado 

> [ffplayout.zip](https://github.com/ffplayout/ffplayout/files/14477950/ffplayout.zip)

**Comment by C0la149** [comment]
@jb-alvarado If you have a telegram, we can go there so I can show you everything in more detail. or even we could go to TeamViewer to see more precisely what is broken there.

**Comment by jb-alvarado** [comment]
Check your `day_start` parameter, the format is wrong.

**Comment by C0la149** [comment]
Okay, I'll fix it now!
@jb-alvarado

**Comment by C0la149** [comment]
![изображение](https://github.com/ffplayout/ffplayout/assets/64633686/d9fe45f8-0d17-4eda-8bd6-34b2e3a3b43a)
Thank you! It really helped! @jb-alvarado 
Of course after commands like:
 systemctl start ffplayout
systemctl enable ffplayout
ffplayout didn't start.
Therefore, I had to restart the VDS. But now ffplayout works.
It remains to solve the problem here https://github.com/ffplayout/ffplayout/issues/556

**Comment by C0la149** [comment]
https://private-user-images.githubusercontent.com/64633686/309821373-9d23a10f-cd47-48cd-a874-c06187f89433.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NjkwNTQsIm5iZiI6MTcwOTU2ODc1NCwicGF0aCI6Ii82NDYzMzY4Ni8zMDk4MjEzNzMtOWQyM2ExMGYtY2Q0Ny00OGNkLWE4NzQtYzA2MTg3Zjg5NDMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDE2MTIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjOGI3ZWJkZmE0NDliYThkYzg5ZGE5YmJkNTE4OTJiYjVhYmQxMDMxYzhiZGQ4OWMyYzkxZjY2MTE1YmM2NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aQ5Q3rBC4-xO3n1zlWkPyLMBl5OMl9QfeV4-3P9KdAo
