### ISSUE TITLE
Try to Import a JSON Playlist and not working playlist

### ISSUE THREAD

**Issue by gihan353** [ffplayout/ffplayout#560]
I attach the log file and my playlist screenshot
![log file](https://github.com/ffplayout/ffplayout/assets/44135989/03381d49-e57d-4f16-ad1d-37725c11cddd)
![playlist](https://github.com/ffplayout/ffplayout/assets/44135989/d85b4029-5437-4de0-a3d1-76950a625a45)

**Comment by tommygothamwest** [comment]
Check the source in the last item in the playlist.

**Comment by gihan353** [comment]
I changed the source but error coming
![log file](https://github.com/ffplayout/ffplayout/assets/44135989/e3132368-1899-4eef-b686-4e5f11b70fa2)
![playlist](https://github.com/ffplayout/ffplayout/assets/44135989/3970d968-e43f-4dbe-ab8a-9cf1417ab5ac)

**Comment by LuizStSantos** [comment]
There are punctuation errors in the json you made ","

**Comment by LuizStSantos** [comment]
What version of your ffmpeg? Have you checked if your system is compatible?

**Comment by gihan353** [comment]
ffmpeg version 4.4.2
Ubuntu 0.22.04.1

**Comment by jb-alvarado** [comment]
Hello @gihan353, I don't know if your problem still exists, you should update to last version and you also need ffmpeg >=  5.0.
