### ISSUE TITLE
GPU acceleration support

### ISSUE THREAD

**Issue by Nejooo** [ffplayout/ffplayout#561]
Hello, I'd like to ask if it would be possible to add gpu acceleration for pre-processing/processing .
Currently I am running into an issue where I am unable to do that,
See, I would like to specify ffmpeg params used for processing such as : -c:v h264_nvenc
I am able to this for output buut I if I can do that for processing, output could just do -c:v copy -c:a copy.

Thanks !

**Comment by jb-alvarado** [comment]
Hello @Nejooo, there is already a open issue with that topic, you can follow that one: https://github.com/ffplayout/ffplayout/issues/558
