### ISSUE TITLE
Remote source stream without known time

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#562]
Is there any way to make ffplayout ignore the end time (output) of a remote source that does not have a determinable or known end time? That is, to make the system condition the jump to the next video on the trigger of the cessation of the stream flow from the remote source, at the moment when the termination, the cessation of the remote stream occurs? Calculating the total time in seconds of a video from a remote source ends up being inefficient in production environments.

**Comment by jb-alvarado** [comment]
No, that is not possible. It would take away the possibility of having any information about temporal synchronicity.

It would be also very kind of you if you would not create questions as bug reports.

**Comment by C0la149** [comment]
@jb-alvarado I apologize for interfering with your topic. But can you tell me the solution to my problem? When can I expect a response?

**Comment by JunioCalu** [comment]
Shortly after posting the question, I came to the same conclusion regarding the synchronicity of time. Sorry for cluttering the issue session with the question, it's just that in other repositories the issue session also serves this purpose.

**Comment by jb-alvarado** [comment]
I you think a issue fits better then a discussion, you can also create that without the bug label.
