### ISSUE TITLE
"Infinit" not being respected

### ISSUE THREAD

**Issue by Raketemensch** [ffplayout/ffplayout#567]
**Describe the bug**

Despite having "Infinit" checked, the stream restarts every 24 hours

**To Reproduce**

1. Go to Configure -> Playout -> Playlist
2. Click on "Infinit"
3. Load a multi-day playlist
4. See that the stream restarts anyway

**Expected behavior**

The stream should continue through the playlist

**Desktop/Server/Software (please complete the following information):**

 - OS: ubuntu 22.04
- ffplayout version: 0.20.2
- ffmpeg version: 4.4.2
- are you using the current master of ffplayout? yes

**Config Settings:**

- command line arguments

**Logging:**

- attached
[ffplayout.log](https://github.com/ffplayout/ffplayout/files/14668756/ffplayout.log)
[
<img width="1140" alt="Screenshot 2024-03-20 at 11 24 39 AM" src="https://github.com/ffplayout/ffplayout/assets/1781323/a41597f7-adf2-45ac-9027-f44d29be727d">
](url)

**Comment by jb-alvarado** [comment]
Currently there is a limitation, where a infinit playlist can only be 24 hours long. I'm working on a new version where this is changed,but the next release is pending on #558.

But I see also some other issues:
- your length value is not correct, should be in timecode format **HH:mm:ss**.
- your error mail messages are not working, maybe you need to setup a app password in gmail
- a file makes problems and can lead to a crash.

**Comment by Raketemensch** [comment]
Thanks, I will follow #558!

**Comment by jb-alvarado** [comment]
n my dev repo is a new version with the updated infinit function. If you want you can give it a try.

It is not battle testet and in some situations the behavior is maybe different then suspected. For example when the playlist is shorter then 24 hours and the playout starts before `day_start`. Or when the playout restarts, maybe it does not continue on the last position.

**Comment by jb-alvarado** [comment]
There is now a beta release with the functionality.

**Comment by Raketemensch** [comment]
Thanks! I was just about to pull your branch and give it a shot, this seems even easier.
