### ISSUE TITLE
The ingest server crashes after a random number of connections or connection attempts

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#568]
After a random number of connection establishments with the ingest server, it ends up crashing, freezing, or refusing new connections. I suggest adding an exception handler that analyzes the standard error numerical exit codes left during the exit of the ingest server's process during a crash. Once this crash is detected, the ingestion server process should be either restarted.

This error can be easily reproduced with the help of OBS Studio by making connection and disconnection attempts for a few minutes; after a low number of attempts, the ingestion server will start refusing any connection attempts. I hope to be able to send the log file related to this problem later.

OS: Manjaro 23.1.3
ffplayout 0.20.5
ffmpeg 6.1.1
are you using the current master of ffplayout? Yes

**Comment by jb-alvarado** [comment]
The ingest has definitely its weaknesses and fast re connections is one of them. Is it for sure that the ingest instances hangs? 

In our setup we also stream not directly to ffplayout, but to SRS, there is a parameter:

```
 publish {
    normal_timeout      20000;
}
```

Which holds the connection a live, even when the stream disconnect for a short moment. This makes it a bit more stabe.

**Comment by JunioCalu** [comment]
> Which holds the connection a live, even when the stream disconnect for a short moment. This makes it a bit more stabe.

Interesting. So, in this case, what would be the configuration to integrate SRS as the ingestion server for ffplayout? When the ingestion server is heavily used, as in cases where multiple presenters go live daily at certain times of the day, this issue of freezing becomes definitively a problem.

**Comment by jb-alvarado** [comment]
You just stream to SRS and there you forward to ffplayout. But this is only useful if you are using a unstable network. When your network is stable, you don't need this setup.

A log file, what you wrote at the beginning, would be good, and when this error is happening the output from:

```BASH
ps aux | grep ffmpeg
```
would be also good.

**Comment by JunioCalu** [comment]
> Um arquivo de log, o que você escreveu no início, seria bom, e quando esse erro estiver acontecendo a saída de:
> 
> ```shell
> ps aux | grep ffmpeg
> ```

Right now I'm testing the following command line as an alternative solution:

`-rw_timeout 20000000 -thread_queue_size 512 -f live_flv -listen 1 -i rtmp://127.0.0.1:1942/live/stream`

**Comment by jb-alvarado** [comment]
I have try to reproduce this issue, but it was not possible to crash ffplayout. I uses this command to stream to the ingest:

```
while true; do ffmpeg -re -i input.mp4 -t 1 -c:v libx264 -c:a aac -f flv rtmp://127.0.0.1:1936/live/stream; done
```

**Comment by JunioCalu** [comment]
> Tentei reproduzir esse problema, mas não foi possível travar o ffplayout. Eu uso este comando para transmitir para a ingestão:

I'll have to test it in a real production environment, with more than one channel active, a 24-hour playlist. When I find some time to do that. I'm not sure, but I'm also considering the possibility that it might be an error related to the server's lack of processing power or something similar.  I ended up reinstalling the system and lost the related logs.
