### ISSUE TITLE
variable problem for live broadcast recording

### ISSUE THREAD

**Issue by djgaby7** [ffplayout/ffplayout#592]
Debian GNU/Linux 12
6.1.0-18-arm64
ffplayout version: 0.20.5

I tried to save the live broadcast in an mp4 file, the problem is that I can't create ex file.mp4, file1.mp4 and so on.

to this variable it saves my variable in the name (RegionalTv-%d.mp4)
-f live_flv -listen 1 -i rtmp://xxx.xxx.xxx.xx:1935/live/rtvdiamant  -acodec copy -vcodec copy -strftime 1 "/var/lib/ffplayout/tv-media/RegionalTv-%d.mp4"

if someone can help me with this problem I would be grateful, I searched on the net no variable worked

**Comment by jb-alvarado** [comment]
Normally it should work. What says the logging?

When I use:

```
-f live_flv -listen 1 -i rtmp://127.0.0.1:1936/live/stream -c copy -strftime 1 -segment_time 600 -f segment /home/user/Videos/tv-media/record_%Y-%m-%d_%H-%M-%S.mkv
```

it records fine. I would also not recommend mp4 as a container format. When something is happen and the playout crashes for example, the hole file is damaged.

**Comment by LuizStSantos** [comment]
Taking advantage of the information, could it be possible to record transmissions by date? with hls output?

```
-c:v h264_nvenc -aspect 16:9 -r:v 30 -b:v 3200k -maxrate 3700k -bufsize 3800k -profile:v main -preset p4 -level 41 -delay 0 -ar 48000 -b:a 128k -c:a aac -muxdelay 0 -colorspace:v bt709 -color_primaries:v bt709 -color_trc:v bt709 -color_range:v tv -f hls -hls_time 2 -hls_list_size 6 -g 60 -keyint_min 60 -hls_flags iframes_only+append_list+omit_endlist+delete_segments+program_date_time+split_by_time+append_list+round_durations -hls_segment_filename /usr/share/ffplayout/public/live/stream-%v-%01d.ts -master_pl_name playlist.m3u8 /usr/share/ffplayout/public/live/stream_%v.m3u8
```

**Comment by djgaby7** [comment]
thank you, now it works, there is a possibility to write in April
