### ISSUE TITLE
[Enhancement] Playlist | for future

### ISSUE THREAD

**Issue by LuizStSantos** [ffplayout/ffplayout#594]
The possibility of making a subplaylist where I can place it within the playlist scheduler example

Name 
```
rural program
``` 
within this playlist

``` 
opening.mp4
program.mp4
break.mp4
program.mp4
opening.mp4
``` 

within the ffplayout schedule it will only be recognized as rural program [PLAYLIST]

![exemplo 2](https://github.com/ffplayout/ffplayout/assets/73047610/66413e32-1609-4ed0-a548-b0bd90104e9f)
![EXEMPLO](https://github.com/ffplayout/ffplayout/assets/73047610/39ed345c-64f6-4389-b110-08c1edfa951b)

The playlist workspace can only be the scheduler assembly part with file folder and save and copy button

**Comment by jb-alvarado** [comment]
I think we already had that request. I understand that there is a need for it, but at the moment I don't see any way to integrate it. The reasons are

- it would need a big change in the code base and that on parts where is very critical
- Those critical parts in the code base are still not 100% bulletproof, and adding new functionality to them will add more complexity, which makes it even more difficult to stabilize the code.
- To me, this looks more like a workaround than a solid feature that a broader audience would need. If we ever found someone to write a more advanced playlist generator, this feature would no longer be needed.

**Comment by tommygothamwest** [comment]
I may have been one of the people that requested this at some point too. 

FWIW, I think the real goal is: group several files together to be placed in the main playlist. It doesn't have to be an m3u8, but it can be something that allows you to create and store a playlist of file entries that can be drag-dropped into the playlist for repeatable "blocks" of programming (maybe something that can just be done in the Media section).

For the moment, using the APIs I was able to build something for my own needs by building the playlist outside ffplayout and then sending it back to ffplayout as a day's playlist.

**Comment by LuizStSantos** [comment]
> I may have been one of the people that requested this at some point too.
> 
> FWIW, I think the real goal is: group several files together to be placed in the main playlist. It doesn't have to be an m3u8, but it can be something that allows you to create and store a playlist of file entries that can be drag-dropped into the playlist for repeatable "blocks" of programming (maybe something that can just be done in the Media section).
> 
> For the moment, using the APIs I was able to build something for my own needs by building the playlist outside ffplayout and then sending it back to ffplayout as a day's playlist.

That would be the idea, because one of the programs I have has 10 items and every day I have to add them one by one, it is a weekly program, it would be much easier to make this playlist and put it in the player as if it were a video, but in fact it is a video set, as if it were an item.

**Comment by jb-alvarado** [comment]
Maybe I have a compromise for you, more I can not do :-).

Currently there is a bug, but will be fixed in next stable release. Then you can import Text files, and the content will be added to the existing one.
