### ISSUE TITLE
help_text is not displayed for task

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#616]
**Describe the bug:**

The help_text related to the task configuration field is not displayed, even if added to the ffplayout.yml configuration file.

**Desktop/Server/Software:**

OS: Manjaro 23.1.3
ffplayout 0.21.0-beta3
ffmpeg 6.1.1
are you using the current master of ffplayout? No

![image](https://github.com/ffplayout/ffplayout/assets/8952225/19c1481e-5fbb-43b6-a336-de074f65ce94)

**Comment by jb-alvarado** [comment]
It should be there:
![Bildschirmfoto vom 2024-04-22 08-23-35](https://github.com/ffplayout/ffplayout/assets/2212056/73b04fd2-1689-4d98-b47f-d82276ecc088)

But in older versions this value was not readed and in older configs it was missed. Maybe you check again, of the value is missed in the config.

**Comment by JunioCalu** [comment]
There was indeed a misunderstanding. I just checked, one of the binaries in my test development environment was outdated, version 0.21.0-beta3.
