### ISSUE TITLE
Next day's playlist has not been started

### ISSUE THREAD

**Issue by LuizStSantos** [ffplayout/ffplayout#619]
- OS: Debian 12
- ffplayout version v0.21.3
- ffmpeg version 5.1.4-0+deb12u1
- are you using the current master of ffplayout? yes

**Describe the bug**

Next day playlist not started, I make the next day's playlist as always, so I thought it was strange that a program was playing that I hadn't put on and I went to check the log and it didn't show the signal of having started the playlist at 8:00.

![image](https://github.com/ffplayout/ffplayout/assets/73047610/fed6afd0-5513-470d-b90f-1234145911eb)

![image](https://github.com/ffplayout/ffplayout/assets/73047610/872be691-6ee9-4da8-a177-32742af07ca6)

**Comment by jb-alvarado** [comment]
Can you add debugging log please.

**Comment by jb-alvarado** [comment]
I was not exactly able to reproduce this error, but in v0.21 I made a little change in the playlist switch behaviour. I guess that was the problem. I revert this with and apply a new fix. Hopefully that solves this and other issues.
