### ISSUE TITLE
[enhancement] Implementation of a download area for complete system log files.

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#625]
Many beginners in Linux server administration are likely facing difficulties in finding a way to download complete ffplayout log records and share them here on GitHub. It would be useful to implement a download button where typical users could easily download these files with a single click on the web interface, whether it be the file related to the current complete log or older logs.

**Comment by jb-alvarado** [comment]
I think that can be done in frontend only. If you are willing to do it, you can go ahead :-).

**Comment by JunioCalu** [comment]
> I think that can be done in frontend only. If you are willing to do it, you can go ahead :-).

Yes, I think I can do that, but I might have to wait for the completion of the new update (0.22) you're finalizing. Depending on the number of new implementations, it could end up being double the work.

**Comment by jb-alvarado** [comment]
Theoretical there is not much to do, because the logging exist already. So only a save function is needed.

**Comment by jb-alvarado** [comment]
Is done

**Comment by JunioCalu** [comment]
> Is done

Thanks @jb-alvarado! I was going to start implementing today, but either way, thank you!
