### ISSUE TITLE
Error when adding a media item while a playlist is not saved

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#643]
Possible steps to reproduce the error:

1. Delete the currently playing playlist, if one exists.
2. Restart ffplayout if the playlist was deleted while a clip was being displayed.
3. Add a media item to a playlist.
4. Add a title to the playback item.
5. Save the playlist.
6. Navigate to a different settings page, "/message", for example.
7. Return to the player page.
8. Add new items to the playlist.
9. Do not save the playlist.
10. Navigate again to a different settings page.
11. Return to the player page.
12. Attempt to add more media items to the unsaved playlist.

Server information:
OS: Manjaro 23.1.3
ffplayout 0.22.0
ffmpeg 6.1.1
are you using the current master of ffplayout? Yes

Additional settings:

![Screenshot_20240508_170327](https://github.com/ffplayout/ffplayout/assets/8952225/7113d252-e4ef-4bdd-a174-76f97d7919b3)

Error outputs:

![image](https://github.com/ffplayout/ffplayout/assets/8952225/4fc08b6d-d83a-46d0-b661-4e32eff59f26)

![Screenshot_20240508_160302](https://github.com/ffplayout/ffplayout/assets/8952225/f97cd46b-c497-40eb-8d7d-003c03a18358)

**Comment by brixxnatt** [comment]
YES BUGGGGGGGGGG

**Comment by JunioCalu** [comment]
I am "attaching" logs from the processes running on systemd:

    mai 11 03:59:34 junio-pc systemd[1]: Started Rest API for ffplayout.
    mai 11 03:59:34 junio-pc systemd[1]: Started Rust and ffmpeg based playout solution.
    mai 11 03:59:34 junio-pc sudo[528361]: pam_unix(sudo:session): session closed for user root
    mai 11 03:59:34 junio-pc ffpapi[528366]: [ INFO] running ffplayout API, listen on http://0.0.0.0:8787
    mai 11 03:59:34 junio-pc ffpapi[528366]: [ INFO] starting 4 workers
    mai 11 03:59:34 junio-pc ffpapi[528366]: [ INFO] Actix runtime found; starting in Actix runtime
    mai 11 03:59:35 junio-pc ffpapi[528366]: [DEBUG] Error in response: Unauthorized("Invalid or expired UUID")
    mai 11 03:59:35 junio-pc ffpapi[528366]: [ INFO] 192.168.42.16 "GET /data/event/1?endpoint=playout&uuid=8b45e503-3c2b-4d0b-9adc-8e6a8f49f70c HTTP/1.1" 401 25 "http://192.168.42.16:8787/pt-br/player" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" 0.000291
    mai 11 03:59:35 junio-pc ffpapi[528366]: [DEBUG] Error in response: Unauthorized("Invalid or expired UUID")
    mai 11 03:59:35 junio-pc ffpapi[528366]: [ INFO] 192.168.42.16 "GET /data/event/1?endpoint=playout&uuid=e1b8bc78-5c49-4651-9efe-9ba18fbaf64f HTTP/1.1" 401 25 "http://192.168.42.16:8787/player" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" 0.000451
    mai 11 03:59:35 junio-pc ffpapi[528366]: [DEBUG] Error in response: Unauthorized("Invalid or expired UUID")
    mai 11 03:59:35 junio-pc ffpapi[528366]: [ INFO] 192.168.42.16 "GET /data/event/1?endpoint=playout&uuid=e1b8bc78-5c49-4651-9efe-9ba18fbaf64f HTTP/1.1" 401 25 "http://192.168.42.16:8787/player" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" 0.000124
    mai 11 03:59:35 junio-pc ffpapi[528366]: [DEBUG] Error in response: Unauthorized("Invalid or expired UUID")
    mai 11 03:59:35 junio-pc ffpapi[528366]: [ INFO] 192.168.42.16 "GET /data/event/1?endpoint=playout&uuid=e1b8bc78-5c49-4651-9efe-9ba18fbaf64f HTTP/1.1" 401 25 "http://192.168.42.16:8787/player" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" 0.000153
    mai 11 03:59:35 junio-pc ffpapi[528366]: [DEBUG] Error in response: BadRequest("invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `n` at 1")
    mai 11 03:59:35 junio-pc ffpapi[528366]: [ INFO] 192.168.42.16 "GET /data/event/1?endpoint=playout&uuid=null HTTP/1.1" 400 104 "http://192.168.42.16:8787/player" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" 0.001500
    mai 11 03:59:36 junio-pc ffpapi[528366]: [DEBUG] Error in response: Unauthorized("Invalid or expired UUID")
    mai 11 03:59:36 junio-pc ffpapi[528366]: [ INFO] 192.168.42.16 "GET /data/event/1?endpoint=playout&uuid=8b45e503-3c2b-4d0b-9adc-8e6a8f49f70c HTTP/1.1" 401 25 "http://192.168.42.16:8787/pt-br/player" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" 0.000156
    mai 11 03:59:37 junio-pc ffpapi[528366]: [DEBUG] Error in response: BadRequest("invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `n` at 1")
    mai 11 03:59:37 junio-pc ffpapi[528366]: [ INFO] 192.168.42.16 "GET /data/event/1?endpoint=playout&uuid=null HTTP/1.1" 400 104 "http://192.168.42.16:8787/player" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" 0.000194
    mai 11 03:59:37 junio-pc ffpapi[528366]: [DEBUG] Error in response: BadRequest("invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `n` at 1")
    mai 11 03:59:37 junio-pc ffpapi[528366]: [ INFO] 192.168.42.16 "GET /data/event/1?endpoint=playout&uuid=null HTTP/1.1" 400 104 "http://192.168.42.16:8787/player" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" 0.000101
    mai 11 03:59:37 junio-pc ffpapi[528366]: [DEBUG] Error in response: BadRequest("invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `n` at 1")
    mai 11 03:59:37 junio-pc ffpapi[528366]: [ INFO] 192.168.42.16 "GET /data/event/1?endpoint=playout&uuid=null HTTP/1.1" 400 104 "http://192.168.42.16:8787/player" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" 0.000143
    mai 11 03:59:37 junio-pc ffpapi[528366]: [DEBUG] Error in response: BadRequest("invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `n` at 1")
    mai 11 03:59:37 junio-pc ffpapi[528366]: [ INFO] 192.168.42.16 "GET /data/event/1?endpoint=playout&uuid=null HTTP/1.1" 400 104 "http://192.168.42.16:8787/player" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" 0.000209
    mai 11 03:59:37 junio-pc ffpapi[528366]: [DEBUG] Error in response: Unauthorized("Invalid or expired UUID")
    mai 11 03:59:37 junio-pc ffpapi[528366]: [ INFO] 192.168.42.16 "GET /data/event/1?endpoint=playout&uuid=8b45e503-3c2b-4d0b-9adc-8e6a8f49f70c HTTP/1.1" 401 25 "http://192.168.42.16:8787/pt-br/player" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" 0.000219
    mai 11 03:59:38 junio-pc ffpapi[528366]: [DEBUG] Error in response: Unauthorized("Invalid or expired UUID")
    mai 11 03:59:38 junio-pc ffpapi[528366]: [ INFO] 192.168.42.16 "GET /data/event/1?endpoint=playout&uuid=8b45e503-3c2b-4d0b-9adc-8e6a8f49f70c HTTP/1.1" 401 25 "http://192.168.42.16:8787/pt-br/player" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" 0.000118
    mai 11 03:59:39 junio-pc ffpapi[528366]: [DEBUG] Error in response: BadRequest("invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `n` at 1")
    mai 11 03:59:39 junio-pc ffpapi[528366]: [ INFO] 192.168.42.16 "GET /data/event/1?endpoint=playout&uuid=null HTTP/1.1" 400 104 "http://192.168.42.16:8787/player" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" 0.000232
    mai 11 03:59:39 junio-pc ffpapi[528366]: [DEBUG] Error in response: BadRequest("invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `n` at 1")
    mai 11 03:59:39 junio-pc ffpapi[528366]: [ INFO] 192.168.42.16 "GET /data/event/1?endpoint=playout&uuid=null HTTP/1.1" 400 104 "http://192.168.42.16:8787/player" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" 0.000318
    mai 11 03:59:39 junio-pc ffpapi[528366]: [DEBUG] Error in response: BadRequest("invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `n` at 1")
    mai 11 03:59:39 junio-pc ffpapi[528366]: [ INFO] 192.168.42.16 "GET /data/event/1?endpoint=playout&uuid=null HTTP/1.1" 400 104 "http://192.168.42.16:8787/player" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" 0.000350
    mai 11 03:59:39 junio-pc ffpapi[528366]: [DEBUG] Error in response: BadRequest("invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `n` at 1")
    mai 11 03:59:39 junio-pc ffpapi[528366]: [ INFO] 192.168.42.16 "GET /data/event/1?endpoint=playout&uuid=null HTTP/1.1" 400 104 "http://192.168.42.16:8787/player" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" 0.000310

**Comment by JunioCalu** [comment]
Additional observations:

1. After each page switch between "/message" and "/player", the "/player" page should be refreshed using the F5 keyboard shortcut.

2. In this case, the ffpapi was compiled with the "embed_frontend" feature disabled.

3. It appears that this bug is overwriting the web frontend installation files, and the only way to remedy it is to uninstall and reinstall the ffplayout installation package each time it occurs.

**Comment by jb-alvarado** [comment]
I found some other little issues, but I was not able to reproduce this one.

**Comment by JunioCalu** [comment]
New error:

Possible steps to reproduce:

1. Add a media item to the playlist.
2. Set a title for the item.
3. Do not change the "duration".
4. Set "in" to 00:01:000.000.
5. Set "out" to 0:01:59:000.00 (the missing last "0" is intentional).
6. Save the item.
7. Save the playlist.
8. Refresh the page (press F5).
9. Try to add another media item to the playlist.

Additional configuration:

    {
      "channel": "Channel 1",
      "date": "2024-05-13",
      "program": [
        {
          "title": "jjjjjjjjjjjjjj",
          "in": 0.0,
          "out": 119.071927,
          "duration": 119.071927,
          "source": "/var/lib/ffplayout/tv-media/filler/filler.mp4"
        },
        {
          "in": 60.0,
          "out": 119.0,
          "duration": 119.071927,
          "source": "/var/lib/ffplayout/tv-media/filler/filler.mp4"
        },
        {
          "in": 0.0,
          "out": 119.071927,
          "duration": 119.071927,
          "source": "/var/lib/ffplayout/tv-media/filler/filler.mp4"
        }
      ]
    }

Console log:

![image](https://github.com/ffplayout/ffplayout/assets/8952225/6b75617d-28b7-4ea1-9309-61e9eb578297)

![Screenshot_20240513_043317](https://github.com/ffplayout/ffplayout/assets/8952225/f0448ed7-9f75-4ea0-9d1d-1d7176361270)

**Comment by JunioCalu** [comment]
Update, another way to trigger the same bug:

1. Add a single media item to the playlist.
2. Save the playlist.
3. Exit the "/player" page and navigate to different pages such as "/message" "/logging".
4. Return to the "/player" page.
5. Refresh the page by pressing F5.
6. Result: The playlist disappears from the screen and it is not possible to add any more items.

**Comment by jb-alvarado** [comment]
I don't know why, but I can't reproduce this error. Not in a released version, and not in dev mode.

**Comment by JunioCalu** [comment]
> I don't know why, but I can't reproduce this error. Not in a released version, and not in dev mode.

![image](https://github.com/ffplayout/ffplayout/assets/8952225/869317db-a84a-44d7-a00b-4940bbdfa461)

**Comment by JunioCalu** [comment]
> I don't know why, but I can't reproduce this error. Not in a released version, and not in dev mode.

In my tests, this bug is linked to the configuration in the image below, while the default installation configuration seems to be working fine.

![image](https://github.com/ffplayout/ffplayout/assets/8952225/75ebcca1-2d7b-4e16-8791-5b4be92e71c9)

**Comment by jb-alvarado** [comment]
Ah that brings light in this issue.
