### ISSUE TITLE
The second channel does not work except the first.

### ISSUE THREAD

**Issue by C0la149** [ffplayout/ffplayout#647]
Debian 12
ffmpeg version 5.1.4-0+deb12u1
ffplayout: v0.22.0

https://github.com/ffplayout/ffplayout/assets/64633686/37bb6fa4-fb9f-492a-ab3e-c5f46d3ccfd4

[channel002.zip](https://github.com/ffplayout/ffplayout/files/15262712/channel002.zip)
![изображение](https://github.com/ffplayout/ffplayout/assets/64633686/aaa14bd7-7eec-42a9-8a56-4991963632be)
I can't give you the logs. Because there is no file. The system didn't make him.

**Comment by jb-alvarado** [comment]
There was a little bug, which should be fixed now. For existing installations you need to rename the config extension in the frondend settings.
