### ISSUE TITLE
Bug  - cant add video to playlist

### ISSUE THREAD

**Issue by brixxnatt** [ffplayout/ffplayout#656]
**Describe the bug**

delete the playlist , try to add now videos , it will not be added if you are making a new playlist , cleared browser cache , also try another browser , nothing pannening  , its not taking 

error in console   - Uncaught (in promise) TypeError: Cannot read properties of null (reading 'item')

ffplayout latest version , Ubuntu 22

**Comment by jb-alvarado** [comment]
#643
