### ISSUE TITLE
[enhancement] Reordering of -ss (seek start) and -t (duration) parameters to reduce issues with desynchronization and timing variation.

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#660]
For faster seeking, the FFmpeg [documentation](https://trac.ffmpeg.org/wiki/Seeking) recommends placing "-ss" before the "-i" parameter. Another section of the [documentation](https://ffmpeg.org/ffmpeg.html#:~:text=%2Dt%20duration%20(input/output)) also advises positioning the "-t" parameter before the "-i" parameter. This repositioning may help decrease desynchronization and timing problems.

**Comment by jb-alvarado** [comment]
`-ss` is already before `-i` and with `-t` as output parameter I feel more save. The documentation makes here no recommendation, it depends on the situation and there is no benefit in terms of speed.

What desynchronization and timing problems do you have?

If you want you can test the changing and share your experience.

**Comment by jb-alvarado** [comment]
Yes, `-ss` after the input is definitely slower, it would create problem if ffplayout uses that way. Only `-t` should not be slower.
