### ISSUE TITLE
[Enhancement] Add interactive seek bar functionality to advance/rewind video in time

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#665]
### Description:
Currently, ffplayout has a progress bar (seek bar) that is purely informational, not allowing the user to interact with it to advance or rewind the video. An interactive seek bar functionality would significantly improve the TV operator's experience, providing greater control over the playback of TV programming.

**Example of Functionality:**
The YouTube seek bar allows users to click on any point of the bar to jump to that specific position in the video. By clicking on a specific point, video playback advances or rewinds to the position corresponding to the clicked point.

**When is this useful?**
In my tests, after ending a live ingest transmission, the video that was playing in the playlist programming does not return to the exact point in time where it was interrupted by the live ingest transmission. Instead, the video starts playing from the fixed start ("in") point determined in the playlist.

**Proposal:**
Add an interactive seek bar functionality to ffplayout, allowing users to:

- Click on any point of the seek bar to advance or rewind video playback to that specific position.

**Comment by jb-alvarado** [comment]
That is technically not possible. I a TV setting every video/ingest normally has his fixed time. That means, when you plan a live event you know at which time it starts and how long it goes. In this situations we use dummy/placeholder clips in our playlist, so that after the live event the offline TV program continue at the right time.

**Comment by JunioCalu** [comment]
Sometimes, there are unplanned "breaking news" events during the day. If there were a way to track and capture the time progression second by second until the final second of the broadcast, it would be possible to capture that exact moment when the offline transmission was overlaid by the live ingest, and then return to that exact second after the live ingest ends.
