### ISSUE TITLE
Ignoring advanced.toml

### ISSUE THREAD

**Issue by Nejooo** [ffplayout/ffplayout#669]
Hello, after latest update, my channels are ignoring advanced.toml.

**Comment by jb-alvarado** [comment]
I am afraid that the file has been overwritten.
Perhaps you should check again whether the file is in its original state.

This should no longer happen in the next update.

**Comment by Nejooo** [comment]
Hello, it left the original advanced.yml there, I moved my setting to advanced.toml  but it's not ignoring those settings for some reason.

**Comment by Nejooo** [comment]
My bad, it's ignoring them for some reason.

**Comment by Nejooo** [comment]
[decoder]
input_param = "-thread_queue_size 1024 -hwaccel_device 0 -hwaccel cuvid -hwaccel_output_format cuda"
# output_param get also applied to ingest instance.
output_param = "-c:v h264_nvenc -preset p2 -tune ll -b:v 50000k -minrate 50000k -maxrate 50000k -bufsize 25000k -c:a s302m -strict -2 -sample_fmt s16 -ar 48000 -ac 2"

[filters]
deinterlace = "" # yadif=0:-1:0
pad_scale_w = "" # scale={}:-1
pad_scale_h = "" # scale=-1:{}
pad_video = "" # pad=max(iw\\,ih*({0}/{1})):ow/({0}/{1}):(ow-iw)/2:(oh-ih)/2
fps = "" # fps={}
scale = "scale_cuda={}:{}:interp_algo=lanczos:force_original_aspect_ratio=decrease" # scale={}:{}
set_dar = "" # setdar=dar={}
fade_in = "" # fade=in:st=0:d=0.5
fade_out = "" # fade=out:st={}:d=1.0
overlay_logo_scale = "" # scale={}
overlay_logo_fade_in = "fade=in:st=0:d=1.0" # fade=in:st=0:d=1.0:alpha=1
overlay_logo_fade_out = "fade=out:st={}:d=1.0" # fade=out:st={}:d=1.0:alpha=1
overlay_logo = "format=nv12,hwupload_cuda[l];[v][l]overlay_cuda=W-w-12:12:shortest=1,hwdownload,format=nv12" # null[l];[v][l]overlay={}:shortest=1
tpad = "" # tpad=stop_mode=add:stop_duration={}
drawtext_from_file = "" # drawtext=text='{}':{}{}
drawtext_from_zmq = "" # zmq=b=tcp\\\\://'{}',drawtext@dyntext={}
aevalsrc = "" # aevalsrc=0:channel_layout=stereo:duration={}:sample_rate=48000
afade_in = "" # afade=in:st=0:d=0.5
afade_out = "" # afade=out:st={}:d=1.0
apad = "" # apad=whole_dur={}
volume = "" # volume={}
split = "" # split={}{}

[encoder]
input_param = ""

[ingest]
input_param = "-thread_queue_size 1024 -hwaccel_device 0 -hwaccel cuvid -hwaccel_output_format cuda"

**Comment by Nejooo** [comment]
Hello, any idea how I could fix this issue ?

**Comment by jb-alvarado** [comment]
Is a bug, later comes an update. The config has to be change to a bit:

Instead if `[filters]` it needs to be `[decoder.filters]`.
