### ISSUE TITLE
Storage not exist!

### ISSUE THREAD

**Issue by C0la149** [ffplayout/ffplayout#675]
https://github.com/ffplayout/ffplayout/assets/64633686/5cdc3718-b4bd-48fe-a1f2-e39478910566

why is that? There is a folder. There are files, what else do you need? The rights to the folder have been granted.

![изображение](https://github.com/ffplayout/ffplayout/assets/64633686/3b923412-915a-4c91-b086-312bac2b42dc)

**Comment by jb-alvarado** [comment]
Currently there are only some folder [whitelisted](https://github.com/ffplayout/ffplayout/blob/69c08308a1715ca1e39f7960de4fd63940fc5c09/ffplayout-api/src/utils/files.rs#L66).

This was introduced in [v0.23.0](https://github.com/ffplayout/ffplayout/releases/tag/v0.23.0).

**Comment by C0la149** [comment]
May I know why you decided to do this? @jb-alvarado

**Comment by C0la149** [comment]
Another interesting bug was found with playlists. Please take a look at the recording.
[https://youtu.be/Ph_B4Kl_hBM](url)

@jb-alvarado

**Comment by jb-alvarado** [comment]
> May I know why you decided to do this? @jb-alvarado

Is a security problem. Without this a use would be able to read almost every text file on the server.

In next version this will be more free, but only for the system administrator.

**Comment by jb-alvarado** [comment]
> Another interesting bug was found with playlists. Please take a look at the recording.
> 
> https://youtu.be/Ph_B4Kl_hBM

screen recording can help, but most time I prefer a step by step reproducible instruction. Here I don't get exactly the problem.

**Comment by C0la149** [comment]
@jb-alvarado Can you come with me to AnyDesk? so I can show you.

**Comment by C0la149** [comment]
If you talk there, the playlist in the interface is reset. Although in theory it exists. Also, if the playlist is compiled in the interface, if you go to another channel that has its own playlist, then it does not show its playlist. Stupidly shows from the previous channel.

@jb-alvarado

**Comment by jb-alvarado** [comment]
I'm at work and can not take the time for that. Does the current playling information not correct switching between channels? That problem I find out yesterday and was not sure if this is happen in v0.23.1 already.

**Comment by C0la149** [comment]
Well, it will be more accurate for you if you look for yourself)

And so yes. There is a problem. ffplayout 0.23.1 is just right.

@jb-alvarado

**Comment by JunioCalu** [comment]
> Another interesting bug was found with playlists. Please take a look at the recording.
> 
> https://youtu.be/Ph_B4Kl_hBM
> 

From your screen recording, it seems that the channel playlists are disappearing from the web panel when you have multiple channels. However, you didn't specify which version of ffplayout you are using in the recording, and you haven't displayed the web browser console's debug log, which could give us a hint about what's really happening under the hood of the code.

**Comment by C0la149** [comment]
> > Another interesting bug was found with playlists. Please take a look at the recording.
> > https://youtu.be/Ph_B4Kl_hBM
> 
> From your screen recording, it seems that the channel playlists are disappearing from the web panel when you have multiple channels. However, you didn't specify which version of ffplayout you are using in the recording, and you haven't displayed the web browser console's debug log, which could give us a hint about what's really happening under the hood of the code.

ffplayout version 0.23.1 

If we put it this way. Then everything else works except the playlist.

**Comment by JunioCalu** [comment]
> ffplayout version 0.23.1
> 
> If we put it this way. Then everything else works except the playlist.

Please send the debug log from your web browser's console or take a screenshot of the log. The procedure for doing this is as follows:

**Google Chrome or Microsoft Edge**
- Press Ctrl + Shift + J on Windows/Linux or Cmd + Option + J on macOS to open the Developer Console.
- Click on the "Console" tab to view the logs.

**Mozilla Firefox**
- Press Ctrl + Shift + K on Windows/Linux or Cmd + Option + K on macOS to open the Developer Tools.
- Select the "Console" tab to view the logs.

**Safari (macOS)**
- First, make sure that the developer tools are enabled: go to Safari > Preferences > Advanced and check the box next to "Show Develop menu in menu bar."
- Press Cmd + Option + C to open the console.

After opening the console, you can refresh the page to capture relevant logs while replicating the issue. This can provide useful information for troubleshooting the problem.

**Comment by C0la149** [comment]
> > ffplayout version 0.23.1
> > If we put it this way. Then everything else works except the playlist.
> 
> Please send the debug log from your web browser's console or take a screenshot of the log. The procedure for doing this is as follows:
> 
> **Google Chrome or Microsoft Edge**
> 
>     * Press Ctrl + Shift + J on Windows/Linux or Cmd + Option + J on macOS to open the Developer Console.
> 
>     * Click on the "Console" tab to view the logs.
> 
> 
> **Mozilla Firefox**
> 
>     * Press Ctrl + Shift + K on Windows/Linux or Cmd + Option + K on macOS to open the Developer Tools.
> 
>     * Select the "Console" tab to view the logs.
> 
> 
> **Safari (macOS)**
> 
>     * First, make sure that the developer tools are enabled: go to Safari > Preferences > Advanced and check the box next to "Show Develop menu in menu bar."
> 
>     * Press Cmd + Option + C to open the console.
> 
> 
> After opening the console, you can refresh the page to capture relevant logs while replicating the issue. This can provide useful information for troubleshooting the problem.

https://youtu.be/HPnMyBJ_79k

**Comment by C0la149** [comment]
@JunioCalu

**Comment by C0la149** [comment]
[Downloads.zip](https://github.com/user-attachments/files/15846476/Downloads.zip)

**Comment by JunioCalu** [comment]
> https://youtu.be/HPnMyBJ_79k

See the image below and based on it, click where the red arrow is pointing to display more details about the bug.

Take a screenshot showing the entire error. If more than one error occurs, take multiple screenshots. I think that's enough for now. For the moment, only the web console log record is needed in the image I provided below.

![image](https://github.com/ffplayout/ffplayout/assets/8952225/6376cc87-e003-453b-b5b2-48c0da85a3b1)

**Comment by C0la149** [comment]
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

/**
 * This @file implements the child side of Conduits, an abstraction over
 * Fission IPC for extension API subject.  See {@link ConduitsParent.sys.mjs}
 * for more details about the overall design.
 *
 * @typedef {object} MessageData
 * @property {ConduitID} [target]
 * @property {ConduitID} [sender]
 * @property {boolean} query
 * @property {object} arg
 *
 * @typedef {import("ConduitsParent.sys.mjs").ConduitAddress} ConduitAddress
 * @typedef {import("ConduitsParent.sys.mjs").ConduitID} ConduitID
 */

/**
 * Base class for both child (Point) and parent (Broadcast) side of conduits,
 * handles setting up send/receive method stubs.
 */
export class BaseConduit {
  /**
   * @param {object} subject
   * @param {ConduitAddress} address
   */
  constructor(subject, address) {
    this.subject = subject;
    this.address = address;
    this.id = address.id;

    for (let name of address.send || []) {
      this[`send${name}`] = this._send.bind(this, name, false);
    }
    for (let name of address.query || []) {
      this[`query${name}`] = this._send.bind(this, name, true);
    }

    this.recv = new Map();
    for (let name of address.recv || []) {
      let method = this.subject[`recv${name}`];
      if (!method) {
        throw new Error(`recv${name} not found for conduit ${this.id}`);
      }
      this.recv.set(name, method.bind(this.subject));
    }
  }

  /**
   * Internal, uses the actor to send the message/query.
   *
   * @param {string} method
   * @param {boolean} query Flag indicating a response is expected.
   * @param {JSWindowActorChild|JSWindowActorParent} actor
   * @param {MessageData} data
   * @returns {Promise?}
   */
  _doSend(method, query, actor, data) {
    if (query) {
      return actor.sendQuery(method, data);
    }
    actor.sendAsyncMessage(method, data);
  }

  /**
   * Internal @abstract, used by sendX stubs.
   *
   * @param {string} _name
   * @param {boolean} _query
   */
  _send(_name, _query, ..._args) {
    throw new Error(`_send not implemented for ${this.constructor.name}`);
  }

  /**
   * Internal, calls the specific recvX method based on the message.
   *
   * @param {string} name Message/method name.
   * @param {object} arg  Message data, the one and only method argument.
   * @param {object} meta Metadata about the method call.
   */
  async _recv(name, arg, meta) {
    let method = this.recv.get(name);
    if (!method) {
      throw new Error(`recv${name} not found for conduit ${this.id}`);
    }
    try {
      return await method(arg, meta);
    } catch (e) {
      if (meta.query) {
        return Promise.reject(e);
      }
      Cu.reportError(e);
    }
  }
}

/**
 * Child side conduit, can only send/receive point-to-point messages via the
 * one specific ConduitsChild actor.
 */
export class PointConduit extends BaseConduit {
  /** @type {ConduitGen} */
  constructor(subject, address, actor) {
    super(subject, address);
    this.actor = actor;
    this.actor.sendAsyncMessage("ConduitOpened", { arg: address });
  }

  /**
   * Internal, sends messages via the actor, used by sendX stubs.
   *
   * @param {string} method
   * @param {boolean} query
   * @param {object?} arg
   * @returns {Promise?}
   */
  _send(method, query, arg = {}) {
    if (!this.actor) {
      throw new Error(`send${method} on closed conduit ${this.id}`);
    }
    let sender = this.id;
    return super._doSend(method, query, this.actor, { arg, query, sender });
  }

  /**
   * Closes the conduit from further IPC, notifies the parent side by default.
   *
   * @param {boolean} silent
   */
  close(silent = false) {
    let { actor } = this;
    if (actor) {
      this.actor = null;
      actor.conduits.delete(this.id);
      if (!silent) {
        // Catch any exceptions that can occur if the conduit is closed while
        // the actor is being destroyed due to the containing browser being closed.
        // This should be treated as if the silent flag was passed.
        try {
          actor.sendAsyncMessage("ConduitClosed", { sender: this.id });
        } catch (ex) {}
      }
    }
    this.closeCallback?.();
    this.closeCallback = null;
  }

  /**
   * Set the callback to be called when the conduit is closed.
   *
   * @param {Function} callback
   */
  setCloseCallback(callback) {
    this.closeCallback = callback;
  }
}

/**
 * Implements the child side of the Conduits actor, manages conduit lifetimes.
 */
export class ConduitsChild extends JSWindowActorChild {
  constructor() {
    super();
    this.conduits = new Map();
  }

  /**
   * Public entry point a child-side subject uses to open a conduit.
   *
   * @type {ConduitGen}
   */
  openConduit(subject, address) {
    let conduit = new PointConduit(subject, address, this);
    this.conduits.set(conduit.id, conduit);
    return conduit;
  }

  /**
   * JSWindowActor method, routes the message to the target subject.
   *
   * @param {object} options
   * @param {string} options.name
   * @param {MessageData | MessageData[]} options.data
   * @returns {Promise?}
   */
  receiveMessage({ name, data }) {
    // Batch of webRequest events, run each and return results, ignoring errors.
    if (Array.isArray(data)) {
      let run = data => this.receiveMessage({ name, data });
      return Promise.all(data.map(data => run(data).catch(Cu.reportError)));
    }

    let { target, arg, query, sender } = data;
    let conduit = this.conduits.get(target);
    if (!conduit) {
      throw new Error(`${name} for closed conduit ${target}: ${uneval(arg)}`);
    }
    return conduit._recv(name, arg, { sender, query, actor: this });
  }

  /**
   * JSWindowActor method, ensure cleanup.
   */
  didDestroy() {
    for (let conduit of this.conduits.values()) {
      conduit.close(true);
    }
    this.conduits.clear();
  }
}

/**
 * Child side of the Conduits process actor.  Same code as JSWindowActor.
 */
export class ProcessConduitsChild extends JSProcessActorChild {
  constructor() {
    super();
    this.conduits = new Map();
  }

  openConduit = ConduitsChild.prototype.openConduit;
  receiveMessage = ConduitsChild.prototype.receiveMessage;
  didDestroy = ConduitsChild.prototype.didDestroy;
  
  

https://youtu.be/jAF3IIffaR0


@JunioCalu

**Comment by JunioCalu** [comment]
> https://youtu.be/jAF3IIffaR0

It looks like a Firefox extension is causing the error. Please install the Google Chrome web browser and test ffplayout using it. During the tests, prefer to use incognito mode.

**Comment by JunioCalu** [comment]
> /* This Source Code Form is subject to the terms of the Mozilla Public
>. . .

This code you posted is internal to the Firefox web browser, not ffplayout. You should have posted the full content of the error messages and code from the images below:

![image](https://github.com/ffplayout/ffplayout/assets/8952225/812d1350-0ae3-4864-948a-cb193596e4d9)

![image](https://github.com/ffplayout/ffplayout/assets/8952225/01c4baa0-8e4c-442b-9361-ff854e9b3648)

**Comment by JunioCalu** [comment]
> /* This Source Code Form is subject to the terms of the Mozilla Public
> 
> * License, v. 2.0. If a copy of the MPL was not distributed with this
> * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
> 
> . . .

Delete all the code you sent, it’s useless.

**Comment by C0la149** [comment]
https://youtu.be/xiSsiAwTZ8c

@JunioCalu 

Honestly showed what I could. It will be easier if we go to telegram so that I can give you Remote access. so you can see for yourself what you need.

**Comment by JunioCalu** [comment]
> https://youtu.be/xiSsiAwTZ8c

> Honestly showed what I could. It will be easier if we go to telegram so that I can give you Remote access. so you can see for yourself what you need.

I didn't see any errors this time. The ffplayout file browser hid at the end of the video, but you can make it visible again by clicking on the drag area and pulling it back to the normal position with the mouse pointer. Next time, it's better to set your browser to English, and ffplayout should also be configured in English. Most people here don't understand Russian.

Check the extensions you have installed in your Firefox web browser. A good way to test which extension is causing the problem is to see if the error disappears when you disable one of them. You would need to test each one individually.

Another way to check which extension is causing the problem is to identify the extension by its ID displayed in your web console when the error message appears. The ID looks like this: "moz-extension://f1b30486-cd88-4319-bbb5-d5e387103414/", as shown [here](https://stackoverflow.com/questions/48056506/get-add-on-id-of-extensions-in-firefox).

**Comment by C0la149** [comment]
-> The ffplayout file browser hid at the end of the video, but you can make it visible again by clicking on the drag area and pulling it back to the normal position with the mouse pointer.

Not at all. This is problem.

Because the playlist does not disappear when you switch to another channel. And if you refresh the page, the playlist may disappear altogether. Although it is compiled and exists!


@JunioCalu 

It will be easier for me to show you everything remotely.

**Comment by C0la149** [comment]
@jb-alvarado Can we communicate with you somehow besides Github?

**Comment by jb-alvarado** [comment]
You can check last update, it should work now.

**Comment by JunioCalu** [comment]
> 
>![image](https://github.com/ffplayout/ffplayout/assets/8952225/6376cc87-e003-453b-b5b2-48c0da85a3b1)
>
> ![image](https://private-user-images.githubusercontent.com/8952225/340015508-812d1350-0ae3-4864-948a-cb193596e4d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3OTkzMDYsIm5iZiI6MTcxODc5OTAwNiwicGF0aCI6Ii84OTUyMjI1LzM0MDAxNTUwOC04MTJkMTM1MC0wYWUzLTQ4NjQtOTQ4YS1jYjE5MzU5NmU0ZDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTlUMTIxMDA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmRiMDhjOWI1YWE5NGI1OGIyMWRiOTExYmIzYzA2YjMyNGJjZDBlZmU2ZWU2NTdlYjY0ZTM4NGQzYzQ1M2E0YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jtc48TqP7nGc6bARi5gYmcKsHjoK2jK6xnWWCL8ttJ0)
> 
> ![image](https://private-user-images.githubusercontent.com/8952225/340015608-01c4baa0-8e4c-442b-9361-ff854e9b3648.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3OTkzMDYsIm5iZiI6MTcxODc5OTAwNiwicGF0aCI6Ii84OTUyMjI1LzM0MDAxNTYwOC0wMWM0YmFhMC04ZTRjLTQ0MmItOTM2MS1mZjg1NGU5YjM2NDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTlUMTIxMDA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDYyZWQxOTIwMzU5ZTUzYWQxMDcxZDI2MThjMTc4NWI3MzI5YWUzNmNmZWQyN2ExNjRiZWUyOWIwYjQ5ODc1ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.onMk9ev35juDcyu4dUggdOc5D757paYycN7p4cXCNv8)

@C0la149, can you test this new version 0.23.2 on your Firefox in normal mode with your extensions enabled and check if the issues mentioned above still occur?

**Comment by C0la149** [comment]
@JunioCalu Can. Please wait.

**Comment by C0la149** [comment]
@JunioCalu https://youtu.be/Fybf5wqqiWw

**Comment by JunioCalu** [comment]
> @JunioCalu https://youtu.be/Fybf5wqqiWw

What do you have to say now? Is ffplayout working correctly now or not?

**Comment by JunioCalu** [comment]
> @JunioCalu https://youtu.be/Fybf5wqqiWw

Type or copy the part highlighted in red into a new tab in your browser and take a screenshot of what appears. Just take the screenshot to be quicker, without recording a video from the screen for now:

![image](https://github.com/ffplayout/ffplayout/assets/8952225/6ddc5d71-41e4-4aff-b3a2-3cd56a7c5b8a)

**Comment by C0la149** [comment]
> > @JunioCalu https://youtu.be/Fybf5wqqiWw
> 
> What do you have to say now? Is ffplayout working correctly now or not?

Yes. It seems to be working fine.

**Comment by C0la149** [comment]
> > @JunioCalu https://youtu.be/Fybf5wqqiWw
> 
> Type or copy the part highlighted in red into a new tab in your browser and take a screenshot of what appears. Just take the screenshot to be quicker, without recording a video from the screen for now:
> 
> ![image](https://private-user-images.githubusercontent.com/8952225/341166511-6ddc5d71-41e4-4aff-b3a2-3cd56a7c5b8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MjA0NjUsIm5iZiI6MTcxODgyMDE2NSwicGF0aCI6Ii84OTUyMjI1LzM0MTE2NjUxMS02ZGRjNWQ3MS00MWU0LTRhZmYtYjNhMi0zY2Q1NmE3YzViOGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTlUMTgwMjQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzJlN2RkYmU2MzJmMzE0ODVjOWNhZjJmYjNhYzdiZjM1OTVjZTMxYTVlZDI5YTMzNWE0ZWQ4NDlmN2FmZDc2MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.piZ47kQmjpd6nuGh5_t0DXaRAfBPQVSi4MajQ9otcK0)

[новый 3.txt](https://github.com/user-attachments/files/15904447/3.txt)

**Comment by C0la149** [comment]
![изображение](https://github.com/ffplayout/ffplayout/assets/64633686/8c807b7c-7ed8-44ad-b79a-fc6d30aeae14)
I'm sorry. This is because of my browser extension. So everything is fine!

![изображение](https://github.com/ffplayout/ffplayout/assets/64633686/7113b021-f89e-4e58-9a4c-0710c251844a)


Here with it disabled

![изображение](https://github.com/ffplayout/ffplayout/assets/64633686/9638029a-49eb-4434-ab92-fee59d363fc8)
