### ISSUE TITLE
Multiple channels configured in "playlist mode" do not correctly display their playlists on the screen when trying to switch between them via the web interface.

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#676]
A bug was identified in @C0la149 setup (ffplayout version 0.23.1). This issue occurs in a scenario where four channels are active.

Steps to reproduce the bug:

1. Configure four channels: X, Y, Z, W.
2. Set channels X, Z, and W to operate in Playlist mode.
3. Set channel Y to operate in "Folder" mode.
4. Create a distinct individual playlist for each channel X, Z, and W.
5. Select channel X, and then switch to channel Z.
6. Result: The playlist for channel X will continue to be displayed on channel Z, even though channel Z has been selected.
7. While on channel Z, switch to channel Y.
8. Result: The playlist for channel Y (in folder mode) will be displayed correctly.
9. If channel X's schedule remains in the field and you save it while on channel W, channel X's schedule will be saved immediately.

System informations:
* OS: Debian 12
* ffplayout version v0.23.1
* ffmpeg version 5.1.4-0+deb12u1
* are you using the current master of ffplayout? yes

**Comment by C0la149** [comment]
Yes that's right. I'm waiting for the fix.

**Comment by JunioCalu** [comment]
@JB-alvarado, have you managed to replicate this issue? I’m testing out version 0.24.0 that you’re working on, and it looks like it might take a while to get stable—probably gonna need a lot of real-world testing. But in the meantime, it would be awesome if we could have a stable release like 0.23.1, or something as rock-solid as version 0.20.5, which was fantastically stable in my opinion.

**Comment by jb-alvarado** [comment]
Should be fixed now.

**Comment by JunioCalu** [comment]
Thanks a lot, @JB-alvarado.

**Comment by JunioCalu** [comment]
I'm updating the ffplayout port I fixed for Arch Linux. According to this fix, I use tags for it, but I noticed that the changes applied to the branch 0.23.x were not passed on to the tag 0.23.2.

![Captura de imagem_20240619_085906](https://github.com/ffplayout/ffplayout/assets/8952225/3932c88a-7510-43ba-afb4-95b0bdc984db)

**Comment by jb-alvarado** [comment]
The download files where correct, but not the branch :-).

**Comment by jacomeTv** [comment]
cordial saludo, tu me podrias orientar que servidor o hosting es minimo necesario para su buen funcionamiento, economico o cual me recomiendas para yo poder utilizar ffplayout que sea estable y buen funcionamiento.
