### ISSUE TITLE
no config on tom version

### ISSUE THREAD

**Issue by cooliobr** [ffplayout/ffplayout#679]
After switching to ffplayout with TOML, I can no longer update ffplayout. Every time I try to update, I only get the following message: No config file 
![Captura de Tela 2024-06-19 às 16 54 20](https://github.com/ffplayout/ffplayout/assets/4358538/6702eb73-3fe8-465c-85ce-8b10e1cffa99)

**Comment by jb-alvarado** [comment]
Have you change to config path in the first GUI tap (channel configuration)?

**Comment by cooliobr** [comment]
Sorry, my bad, I didn't notice that earlier.
