### ISSUE TITLE
how to fix this URGENT

### ISSUE THREAD

**Issue by brixxnatt** [ffplayout/ffplayout#685]
--- db_path: "/usr/share/ffplayout/db/ffplayout.db"
thread 'main' panicked at ffplayout-api/src/utils/mod.rs:103:13:
error returned from database: (code: 1) trigger global_row_count already exists
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by JunioCalu** [comment]
then send the output messages of these commands:

```
sudo systemctl stop ffplayout

sudo -u ffpu RUST_BACKTRACE=1 /usr/bin/ffplayout -l 0.0.0.0:8787

sudo -u ffpu RUST_BACKTRACE=full /usr/bin/ffplayout -l 0.0.0.0:8787
```

**Comment by brixxnatt** [comment]
fixed it thank you my friend

**Comment by brixxnatt** [comment]
thanks
