### ISSUE TITLE
ffplayout 0.24.0-alpha2 - Log files are not being created automatically, the embedded player is not playing.

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#698]
Describe the bug

Log files are not being created automatically, the embedded player is not playing.

Desktop/Server/Software:

OS: Manjaro 24.0.3
ffplayout 0.24.0-alpha2
ffmpeg 6.1.1
are you using the current master of ffplayout? Yes

Additional information:

ffplayout was compiled with the "embed_frontend" option disabled. This was the command used to initialize the database.

    sudo -u ffpu ffplayout -i
    Global admin: admin
    Password: 
    Mail: contact@example.org        
    Storage path [/var/lib/ffplayout/tv-media]: /var/lib/ffplayout/tv-media
    Playlist path [/var/lib/ffplayout/playlists]: /var/lib/ffplayout/playlists
    Logging path [/var/log/ffplayout]: /var/log/ffplayout
    HLS path [/usr/share/ffplayout/public]: /usr/share/ffplayout/public/live
    Shared storage [Y/n]: Y
    Set global settings...
    Create global admin user "admin" done...

Missing log:
![image](https://github.com/user-attachments/assets/cef21d99-1ef7-4164-b8e4-be7c444694b0)

Player error:
![image](https://github.com/user-attachments/assets/58adb137-381a-45b4-83ab-7cfda30992d1)

**Comment by JunioCalu** [comment]
Update:

1. The old URL is working: http://192.168.42.16:8787/live/stream.m3u8. For a second channel, the URL is: http://192.168.42.16:8787/live/2/stream.m3u8

2. The initial log is created when a playlist is played.

**Comment by jb-alvarado** [comment]
I understood that your issue was fixed? When not you can create a new one.
