### ISSUE TITLE
auto start stream

### ISSUE THREAD

**Issue by cooliobr** [ffplayout/ffplayout#702]
I don't know if this is happening to anyone else, but since I'm using Docker, it might be just my problem. When I need to restart Docker with "docker-compose down" and "docker-compose up -d", ffplayout [alpha2](https://github.com/ffplayout/ffplayout/releases/tag/v0.24.0-alpha2) does not start the stream. It only starts after I press the restart button in the frontend.

**Comment by jb-alvarado** [comment]
I will release another alpha version, with that I was not able to reproduce this error. So hopefully is fixed :-).
