### ISSUE TITLE
ffplayout 0.23.2 - Playlists created at certain times of day cannot be played

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#705]
**Describe the bug**

Today at 3:19 AM (in my timezone), I tried to create a playlist on the ffplayout frontend, but when I attempted to play it, I received the following error:

    [2024-07-21 03:19:57.88395] [ INFO] Move to next clip
    [2024-07-21 03:19:58.08802] [ERROR] "File  not exist!"
    [2024-07-21 03:19:58.08975] [ERROR] Playlist /var/lib/ffplayout/playlists/2024/07/2024-07-20.json not exist!

The log indicates that ffplayout attempted to play a playlist from the previous day (the 20th) when it should have been playing the playlist for the current day (the 21st, today's date). On the frontend, I confirmed that ffplayout successfully created the playlist for the 21st and stored it on disk; it just did not play it.

After identifying this issue, I left ffplayout "paused" for a few hours, and conducted a new test at 10:02 AM today (the 21st), finding that from this time onward ffplayout was able to correctly play the list created earlier at 3 AM.

**Desktop/Server:**

 - OS: Manjaro 24.0.4
- ffplayout 0.23.2
- ffmpeg 7.0.1
- are you using the current master of ffplayout? No.

**Config Settings:**

- config file: [ffplayout.toml.txt](https://github.com/user-attachments/files/16325053/ffplayout.toml.txt)

**Logging:**

- content of: [ffplayout.log.txt](https://github.com/user-attachments/files/16325047/ffplayout.log.txt)

**Comment by jb-alvarado** [comment]
That is happen because you worked after midnight and before playlist day_start time. In this situations you have to go one day back and create your playlist.

For the next version I added a warning for this case and switch the date. But this will happen only ones when page is loaded, as soon as the calendar is changed there will be no warning any more.

**Comment by JunioCalu** [comment]
Thanks, Could you apply this patch to version 0.23.2? I am using this version in my production environment.
