### ISSUE TITLE
issue with logo filter

### ISSUE THREAD

**Issue by Nejooo** [ffplayout/ffplayout#709]
Hello, so I'm attempting to input the logo purely via nvenc and I've came access this issue 
```
"ffmpeg -hide_banner -nostats -v level+error -readrate 1 -ss 819.3724304970092 -i /mnt/tvsobrance/EXPORTY/SOBRANSKY MAGAZIN/SOBRANSKY_MAGAZIN_499.mp4 -filter_complex \
[0:v:0]null,fade=in:st=0:d=0.5,null[v];movie=/usr/share/ffplayout/logo.png:loop=0,setpts=N/(FRAME_RATE*TB),format=rgba,colorchannelmixer=aa=0.7,format=nv12,hwupload_cuda[l];[v][l]overlay_cuda=W-w-12:12:shortest=1,hwdownload,format=nv12[vout0];[0:a:0]anull,afade=in:st=0:d=0.5[aout0] \
-map [vout0] -map [aout0] -c:v libx264 -crf 23 -x264-params keyint=50:min-keyint=25:scenecut=-1 \
-maxrate 1300k -bufsize 2600k -preset faster -tune zerolatency -profile:v Main -level 3.1 \
-c:a aac -ar 44100 -b:a 128k -flags +cgop -f hls -hls_time 6 -hls_list_size 600 -hls_flags append_list+delete_segments+omit_endlist \
-hls_segment_filename /usr/share/ffplayout/public/live/stream-%d.ts /usr/share/ffplayout/public/live/stream.m3u8" 
```

You see it's adding forma as rgba for some reason while I need it to be nv12 like this 
```
ffmpeg -hide_banner -nostats -v level+error -readrate 1 -ss 819.3724304970092 -i /mnt/tvsobrance/EXPORTY/SOBRANSKY MAGAZIN/SOBRANSKY_MAGAZIN_499.mp4 -filter_complex \
"[0:v:0]null,fade=in:st=0:d=0.5,format=nv12,hwupload_cuda[v];movie=/usr/share/ffplayout/logo.png:loop=0,setpts=N/(FRAME_RATE*TB),format=rgba,colorchannelmixer=aa=0.7,format=nv12,hwupload_cuda[l];[v][l]overlay_cuda=W-w-12:12:shortest=1,hwdownload,format=nv12[vout0];[0:a:0]anull,afade=in:st=0:d=0.5[aout0]" \
-map "[vout0]" -map "[aout0]" -c:v libx264 -crf 23 -x264-params keyint=50:min-keyint=25:scenecut=-1 \
-maxrate 1300k -bufsize 2600k -preset faster -tune zerolatency -profile:v Main -level 3.1 -c:a aac -ar 44100 -b:a 128k -flags +cgop -f hls -hls_time 6 -hls_list_size 600 -hls_flags append_list+delete_segments+omit_endlist -hls_segment_filename /usr/share/ffplayout/public/live/stream-%d.ts \
/usr/share/ffplayout/public/live/stream.m3u8"
```
It's when I use advanced.toml.

**Comment by cooliobr** [comment]
Sure, here is the translation:

As I have posted earlier, my best experience is with the filter in this command line "``ffmpeg -hide_banner -threads 4 -hwaccel cuvid -c:v h264_cuvid -fix_sub_duration -drop_second_field true -nostats -v level+error -i /var/lib/ffplayout/tv-media/Suits/S01/Suits_S01E10_Vida de fachada.mp4 -filter_complex [0:v:0]scale_npp=format=yuv420p,scale_npp=1280:720:interp_algo=super:force_original_aspect_ratio=decrease,hwdownload,pad=1280:720:(ow-iw)/2:(oh-ih)/2:color=black,setdar=16:9,setsar=1:1,hwupload[v];movie=/usr/share/ffplayout/HALLO_Plus.png[l0];[l0]format=rgba,colorchannelmixer=aa=0.7,scale=iw*0.6:-1,hwupload_cuda[l];[v][l]overlay_cuda=main_w-overlay_w-50:33,realtime=speed=1.0002503581304953[vout0];[0:a:0]anull,volume=5[aout0];[0:a:1]anull,volume=5[aout1] -map [vout0] -map [aout0] -map [aout1] -c:v h264_nvenc -aspect 16:9 -r:v 30 -b:v 1700k -maxrate 1700k -bufsize 1700k -profile:v main -preset p4 -level 41 -delay 0 -ar 48000 -b:a 128k -c:a aac -colorspace:v bt709 -color_primaries:v bt709 -color_trc:v bt709 -color_range:v tv -f hls -hls_time 6 -hls_list_size 10 -g 30 -keyint_min 30 -hls_flags second_level_segment_index+append_list+omit_endlist+delete_segments+program_date_time -strftime 1 -hls_segment_filename /usr/share/ffplayout/public/live/ch10/stream-%v-%%04d.ts /usr/share/ffplayout/public/live/ch0/playlist.m3u8``" the logo looks perfect with the transparency.

**Comment by jb-alvarado** [comment]
Can you share your **advanced.toml**?

**Comment by Nejooo** [comment]
[decoder]
input_param = "-hwaccel cuda -hwaccel_output_format cuda"
# output_param get also applied to ingest instance.
output_param = "-c:v h264_nvenc -preset:v p7 -tune:v lossless -b:v 5M -c:a aac"

[encoder]
input_param = ""

[filters]
deinterlace = "" # yadif=0:-1:0
pad_scale_w = "" # scale={}:-1
pad_scale_h = "" # scale=-1:{}
pad_video = "" # pad=max(iw\\,ih*({0}/{1})):ow/({0}/{1}):(ow-iw)/2:(oh-ih)/2
fps = "" # fps={}
scale = "" # scale={}:{}
set_dar = "" # setdar=dar={}
fade_in = "" # fade=in:st=0:d=0.5
fade_out = "" # fade=out:st={}:d=1.0
overlay_logo_scale = "" # scale={}
overlay_logo_fade_in = "fade=in:st=0:d=1.0" # fade=in:st=0:d=1.0:alpha=1
overlay_logo_fade_out = "fade=out:st=0:d=1.0" # fade=out:st={}:d=1.0:alpha=1
overlay_logo = "format=nv12,hwupload_cuda[l];[v][l]overlay_cuda=W-w-12:12:shortest=1,hwdownload,format=nv12" # null[l];[v][l]overlay={}:shortest=1
tpad = "" # tpad=stop_mode=add:stop_duration={}
drawtext_from_file = "" # drawtext=text='{}':{}{}
drawtext_from_zmq = "" # zmq=b=tcp\\\\://'{}',drawtext@dyntext={}
aevalsrc = "" # aevalsrc=0:channel_layout=stereo:duration={}:sample_rate=48000
afade_in = "" # afade=in:st=0:d=0.5
afade_out = "" # afade=out:st={}:d=1.0
apad = "" # apad=whole_dur={}
volume = "" # volume={}
split = "" # split={}{}

[ingest]
input_param = ""

**Comment by jb-alvarado** [comment]
When I compare your both ffmpeg commands it differs only in fade filter, not in logo filter. Maybe you need to try:

```TOML
fade_in = "fade=in:st=0:d=0.5,format=nv12,hwupload_cuda"
```

A full error message could help to.

**Comment by cooliobr** [comment]
In my various tests, this was the best result.

`` [decoder]
input_param = "-thread_queue_size 256 -hwaccel_device 0 -hwaccel cuvid -hwaccel_output_format cuda -drop_second_field true"

output_param = "-g 30 -keyint_min 30 -c:v h264_nvenc -preset p3 -tune ll -b:v 10000k -minrate 10000k -maxrate 10000k -c:a s302m -strict -2 -sample_fmt s16 -ar 48000 -ac 2"

[encoder]
input_param = ""

[filters]
deinterlace = "null" # yadif=0:-1:0
pad_scale_w = "null" # scale={}:-1
pad_scale_h = "null" # scale=-1:{}
pad_video = "null" # pad=max(iw\\,ih*({0}/{1})):ow/({0}/{1}):(ow-iw)/2:(oh-ih)/2
fps = "null" # fps={}
scale = "scale_npp=format=yuv420p,scale_npp={}:{}:interp_algo=super:force_original_aspect_ratio=decrease,hwdownload,pad=1280:720:(ow-iw)/2:(oh-ih)/2:color=black,setdar=16:9,setsar=1:1,hwupload" # scale={}:{}
set_dar = "null" # setdar=dar={}
fade_in = "null" # fade=in:st=0:d=0.5
fade_out = "null" # fade=out:st={}:d=1.0
overlay_logo_scale = "null" # scale={}
overlay_logo_fade_in = "null" # fade=in:st=0:d=1.0:alpha=1
overlay_logo_fade_out = "null" # fade=out:st={}:d=1.0:alpha=1
overlay_logo = "hwupload_cuda[l];[v][l]overlay_cuda=main_w-overlay_w-30:30:shortest=1,hwdownload,hqdn3d=3.0:3.0:6.0:6.0,hwupload" # null[l];[v][l]overlay={}:shortest=1
tpad = "hwdownload,tpad=stop_mode=add:stop_duration={},hwupload" # tpad=stop_mode=add:stop_duration={}
drawtext_from_file = "" # drawtext=text='{}':{}{}
drawtext_from_zmq = "" # zmq=b=tcp\\\\://'{}',drawtext@dyntext={}
aevalsrc = "" # aevalsrc=0:channel_layout=stereo:duration={}:sample_rate=48000
afade_in = "" # afade=in:st=0:d=0.5
afade_out = "" # afade=out:st={}:d=1.0
apad = "" # apad=whole_dur={}
volume = "" # volume={}
split = "" # split={}{}

[ingest]
input_param = "-thread_queue_size 256 -hwaccel_device 0 -hwaccel cuvid -hwaccel_output_format cuda"``
