### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by tiagoventura7** [ffplayout/ffplayout#711]
hi,

how to run tasks? is there any tutorial on how to do it?

**Comment by jb-alvarado** [comment]
Currently there is no tutorial, but you can take a look in the example scripts. 

There is a python version: https://github.com/ffplayout/ffplayout/blob/master/scripts/task_runner.py 

And a bash version: https://github.com/ffplayout/ffplayout/blob/master/scripts/task-runner.sh

**Comment by tiagoventura7** [comment]
fine... i havea question...

**Comment by tiagoventura7** [comment]
fine, i have two questions (my english is not so good as i wanted, so thank you for your patience)

1. running in folder mode, random, is that possible to change the way of engine to "randomize" the content in order to alternate play random files from "directory 1", "directory 2", then again "directory 1", "directory 2" and so on...?
(i know this could be tricky...)

2. is there a way to write a script to play a random file from a specific directory, at specific days of week and specific hours of day, even the need of use cron?

thank you very much in advance for your answers

**Comment by jb-alvarado** [comment]
For this I would recommend using playlist mode and [generator](https://github.com/ffplayout/ffplayout/blob/master/docs/playlist_gen.md). In the frontend the generation is more comfortable.

**Comment by tiagoventura7** [comment]
the reason im asking this is because i have 2 directories to play random content, no matter whats playing, all the directories content doesn't need an order specificaly an order to play... but i need to play some stuff from a specific directory at specific hours of the day, at specific days of week... the work arround i found for this was setting up the Advanced Scene Switcher plugin for OBS an go live throught live ingest... i would like to avoid live ingest for this

**Comment by jb-alvarado** [comment]
Yes, for that you could use the playlist template to generate your random content with the control you need. This you could automate to with cron.
