### ISSUE TITLE
RPC Server

### ISSUE THREAD

**Issue by C0la149** [ffplayout/ffplayout#714]
What do they eat with what? What is this? And how to work with this? how to receive what is on the air via RPC?
![firefox_VEuZa7sZsc](https://github.com/user-attachments/assets/d11a62fb-679c-49a6-bb1b-85c023248930)

**Comment by jb-alvarado** [comment]
In the coming release the RPC will be obsolete. For the current version you can read about it in the readme from 0.23.x branch.
