### ISSUE TITLE
RE: Installation 

### ISSUE THREAD

**Issue by tickideas** [ffplayout/ffplayout#719]
Hello, I need your help, I have tried to install ffplayout on Ubuntu 22.04 following the [https://github.com/ffplayout/ffplayout/blob/master/docs/install.md](https://github.com/ffplayout/ffplayout/blob/master/docs/install.md) but it seems not to be working. Do I need to install RUST on the machine for this to work?

**Comment by jb-alvarado** [comment]
Hello @tickideas, when you are not using then current [0.24 beta](https://github.com/ffplayout/ffplayout/releases/tag/v0.24.0-beta1), you have to follow the older instruction:

https://github.com/ffplayout/ffplayout/blob/v0.23.x/docs/install.md

When this still not work, I need more details.
