### ISSUE TITLE
how to save space in disk

### ISSUE THREAD

**Issue by tecnicosya** [ffplayout/ffplayout#720]
**Describe the bug**

Streaming a Channel use a lot of disk space.

**To Reproduce**

Just stream a channel an monitoring the disk space, I have low space in my test pc then the system notify again and again the space is less and less.
**Expected behavior**

If I'm making an streaming from OBS to FFplayout or from playlist, I just want to streaming and dont use disk space or small disk, in my test was more than 10gb on streaming, totally innecesary. 
I try to check the code by my selft.

 - OS: [e.g. debian 12]
- ffplayout version ffplayout_0.24.0-beta1-1_amd64
- ffmpeg version 4.4.2-0ubuntu0.22.04.1+esm4
- are you using the current master of ffplayout?

**Config Settings:**

- command line arguments
- config fie

**Logging:**

- content of: ffplayout.log

Ok comparing the streaming with same streaming but from other media server, I see in the other I have only 30 seconds of cache in player, but with ffplayou have 1 hour and 1 hour in FHD need more space than 30 seconds.

Is possible to have this 30 seconds only in memory to dont kill the nvme?

**Comment by tecnicosya** [comment]
Ok in my way I change this lines on the output_params:
-f hls -hls_time 6 
-hls_list_size 10 

The first is the size in seconds of every segment of hls, here is 6 seconds.
The second line is the number of segments saved, by default was 600 segmends (6*600=3600 seconds or 60 minutes), now I set to 6*10 equal to 1 minute.

**Comment by tecnicosya** [comment]
Is possible to use this config?
Just change the location file to serve from ram and dont pass to the hard disk.
    -c:v libx264 -crf 23 
    -x264-params keyint=50:min-keyint=25:scenecut=-1 
    -maxrate 3600k 
    -bufsize 2600k 
    -preset faster 
    -tune zerolatency 
    -profile:v Main 
    -level 3.1 
    -c:a aac 
    -ar 44100 
    -b:a 128k 
    -flags +cgop 
    -f hls 
    -hls_time 6 
    -hls_list_size 10 
    -hls_flags append_list+delete_segments+omit_endlist 
    -hls_segment_filename /dev/shm/live/stream-%d.ts /dev/shm/live/stream.m3u8 
    -c:v copy 
    -c:a copy

**Comment by tecnicosya** [comment]
Or is possible to run this configuration? This iis using something called pipes
ffmpeg -i input_file.mp4 -f mpegts - | ffmpeg -i - \
    -c:v libx264 -crf 23 \
    -x264-params keyint=50:min-keyint=25:scenecut=-1 \
    -maxrate 3600k \
    -bufsize 2600k \
    -preset faster \
    -tune zerolatency \
    -profile:v Main \
    -level 3.1 \
    -c:a aac \
    -ar 44100 \
    -b:a 128k \
    -flags +cgop \
    -f hls \
    -hls_time 6 \
    -hls_list_size 10 \
    -hls_flags append_list+delete_segments+omit_endlist \
    -hls_segment_filename live/stream-%d.ts live/stream.m3u8

**Comment by jb-alvarado** [comment]
Yes you can create a [ramdisk](https://www.linuxbabe.com/command-line/create-ramdisk-linux) and use it as target. But it should be big enough.

I don't think piping is working but I have not tried it.
