### ISSUE TITLE
[enhancement] Highlight Ad Track in Red in the Playlist

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#731]
Currently, when a track in the playlist is marked as an ad (Adsense), it is displayed in the same color as other tracks (green color). To improve visibility and management, especially during live operations, I propose that all tracks marked as ads be highlighted in red in the playlist, including both ad tracks that are currently playing and those queued for playback.

**Comment by jb-alvarado** [comment]
Red color should be carefully used in video streaming applications. For now I only darken the text color, we can see in practice if this is enough.

**Comment by JunioCalu** [comment]
> Red color should be carefully used in video streaming applications. For now I only darken the text color, we can see in practice if this is enough.

I just tested it, and a stronger color should be used to make it stand out more. The visual difference is still barely noticeable.
