### ISSUE TITLE
Playout Stops When Manually Switching Tracks Using Previous/Next Controls

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#735]
### Describe the bug

The playout stops when the tracks are manually switched using the previous and next playback controls on the frontend. It seems like the desynchronization issue during track changes is still present.

### Desktop/Server/Software:

- OS: [e.g. ubuntu 22.04]
- ffplayout 0.24.0-beta3
- ffmpeg 7.0.1
- are you using the current master of ffplayout? Yes

**Comment by jb-alvarado** [comment]
I have look to it, but the problem is this problem pops up randomly. In my tests it always worked good, but in usage I had that problem one to. I need to know exactly how to repoduce.

**Comment by JunioCalu** [comment]
I'll check if this new update fixed the issue. The failure is pretty random, so I'll try to find some time to do a more in-depth debugging session using rust-gdb to identify the problem if it still persists.
