### ISSUE TITLE
Unable to set a custom directory for the 'public' folder

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#738]
### Describe the bug

It is not possible to set an alternative folder for the public folder using the "--public" parameter.

### To Reproduce

1. Create database:

```shell
sudo ./pkg/ffplayout-git/usr/bin/ffplayout --db=./db --log-path=./log --public-root=./pkg/ffplayout-git/usr/share/ffplayout/public --storage-root=/var/lib/ffplayout/tv-media --shared-storage -u admin -p admin -m contact@example.org
``` 

2. Start ffplayout
```shell
sudo ./pkg/ffplayout-git/usr/bin/ffplayout --db=./db --public=./pkg/ffplayout-git/usr/share/ffplayout/public/ -l 0.0.0.0:8787
``` 
3. Access the ffplayout URL

![image](https://github.com/user-attachments/assets/c4f85384-caed-4d49-9503-b9a1930f2251)

### Desktop/Server/Software:
* OS: manjaro 24.0.8
* ffplayout 0.24.0-beta4
* ffmpeg 7.0.1
* are you using the current master of ffplayout? Yes

### Logging:

```shell

sudo ./pkg/ffplayout-git/usr/bin/ffplayout --db=./db --public=./pkg/ffplayout-git/usr/share/ffplayout/public/ -l 0.0.0.0:8787
[ INFO] Running ffplayout API, listen on http://0.0.0.0:8787
[ INFO] starting 2 workers
[ INFO] Actix runtime found; starting in Actix runtime
[ INFO] starting service: "actix-web-service-0.0.0.0:8787", workers: 2, listening on: 0.0.0.0:8787
[ INFO] 127.0.0.1 "GET / HTTP/1.1" 404 45 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" 0.000206
[ INFO] 127.0.0.1 "GET /favicon.ico HTTP/1.1" 200 8653 "http://127.0.0.1:8787/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" 0.003940
[ INFO] 127.0.0.1 "GET / HTTP/1.1" 404 45 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" 0.000128
[ INFO] 127.0.0.1 "GET / HTTP/1.1" 404 45 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" 0.000156
[ INFO] 127.0.0.1 "GET / HTTP/1.1" 404 45 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" 0.003823

```

**Comment by jb-alvarado** [comment]
There is a `--public` and `--public_root` option, `--public` is for static files, `--public_root` for HLS files.

**Comment by JunioCalu** [comment]
It seems that these two parameters are not working.

**Comment by jb-alvarado** [comment]
Good that you have point this out. There is general problem in this hole logic: https://github.com/ffplayout/ffplayout/blob/1b79b7bbda4d43c93e365768ffb148e4386ea190/ffplayout/src/main.rs#L173-L203

Routes with same targets don't work correctly together. Here we have two time a route with "/" as target, so actix only select the first one.

At the moment I tent to the direction of removing `--public` argument.

**Comment by JunioCalu** [comment]
I think it would be useful to keep this parameter. It's helpful when you want to test different versions of ffplayout simultaneously on the same host. In my case, when testing different versions with '[embed_frontend]' disabled, they all end up pointing to /usr/share/ffplayout/public, causing conflicts.

**Comment by jb-alvarado** [comment]
Then I could move the argument to the `public_path()` function: 

https://github.com/ffplayout/ffplayout/blob/1b79b7bbda4d43c93e365768ffb148e4386ea190/ffplayout/src/utils/mod.rs#L197-L211

**Comment by JunioCalu** [comment]
Great, that would be good.

**Comment by JunioCalu** [comment]
The unified `--public` parameter is working now, but the path `"frontend/.output/public/"` is being skipped and redirected to `/usr/share/ffplayout/public`. It seems like the `./` is missing at the beginning of that path, meaning it should be `./frontend/.output/public/`. I'm assuming that, but I'm not sure.

**Comment by JunioCalu** [comment]
.ts and .m3u8 files are not being saved in the HLS path defined by the '--public' flag.

**Comment by JunioCalu** [comment]
> .ts and .m3u8 files are not being saved in the HLS path defined by the '--public' flag.

This issue still persists.

**Comment by jb-alvarado** [comment]
At the moment I'm fine with that. In a multi channel setup, every channel can have it's own path, so it makes no sense to override them.

**Comment by JunioCalu** [comment]
> At the moment I'm fine with that. In a multi channel setup, every channel can have it's own path, so it makes no sense to override them.

The problem is that when "--public" is set, it seems that the default HLS path /usr/share/public/live/ is disabled, and no HLS files are written to it.

**Comment by jb-alvarado** [comment]
Which path is set in the channel configuration?
