### ISSUE TITLE
[Enhancement] Support for UDP protocol in the embedded player of the ffplayout frontend

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#741]
### Feature description

It would be possible to use the UDP protocol in the ffplayout player through the tee muxer, and since this protocol is faster for real-time viewing compared to the native HLS protocol of ffplayout, it would be great to have playback support for it in the embedded ffplayout player.

### The problem in the current version

The HLS protocol used in the native embedded player of ffplayout is slow for real-time viewing of the TV schedule and causes the player to freeze at certain times.

### Alternative ways

Combine tee muxer and UDP to achieve a more stable playback stream

**Comment by jb-alvarado** [comment]
Browsers don't support UDP streams.
