### ISSUE TITLE
Unable to set a custom directory path for the 'log' folder

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#742]
### Describe the bug

It is not possible to set a custom directory path for the "log" folder using the "--log-path" command line option.

### To Reproduce

1.
```shell
sudo ./pkg/ffplayout-unstable-git/usr/bin/ffplayout --db=./db --log-path=./log --public-root=./pkg/ffplayout-git/usr/share/ffplayout/public --storage-root=/var/lib/ffplayout/tv-media --shared-storage -u admin -p admin -m ffplayout@example.org
```
2. 
```shell
sudo ./pkg/ffplayout-unstable-git/usr/bin/ffplayout --db=./db -l 0.0.0.0:8787
``` 
3. No log file is generated in the ./log path, the log continues to write to /var/log/ffplayout/ffplayout_1.log

### Desktop/Server/Software:
* OS: manjaro 24.0.8
* ffplayout 0.24.0-beta4
* ffmpeg 7.0.1
* are you using the current master of ffplayout? Yes

**Comment by jb-alvarado** [comment]
Have you try to set a absolut path to a existing folder? I can't reproduce this error. ffplayout only switch to the default path, when the setted path not exists.

**Comment by JunioCalu** [comment]
The directory was created, and the permissions were set, but it still defaults to the standard directory. This issue doesn't occur with the database parameter "--db".

**Comment by JunioCalu** [comment]
Now it's working, there's just a small detail: it's creating 2 files initially, ffplayout_1.log and ffplayout.log. The second file is extra.

**Comment by JunioCalu** [comment]
Now it's working.
