### ISSUE TITLE
Incorrect HLS path displayed in output_param

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#743]
### Describe the bug

Incorrect HLS path displayed in output_param

### To Reproduce

![image](https://github.com/user-attachments/assets/5deacd8d-4918-4712-bde5-12fa206c1d22)

### Desktop/Server/Software:

- OS: manjaro 24.0.8
- ffplayout 0.24.0-beta4
- ffmpeg 7.0.1
- are you using the current master of ffplayout? Yes

**Comment by jb-alvarado** [comment]
The path is correct because it should be relative to hls path from channel settings.

**Comment by JunioCalu** [comment]
I see, it's because in versions prior to 0.24.0, an absolute directory path was displayed.

**Comment by JunioCalu** [comment]
It's not possible to manually set directory paths in output_param, like with hls_segment_filename /usr/share/ffplayout/public/live/stream-%d.ts /usr/share/ffplayout/public/live/stream.m3u8. The full paths are not being added, and a 'directory not found' error is returned.

**Comment by jb-alvarado** [comment]
No, the paths must be relative. One of the most voted feature requests was multi-channel support. To make this more secure, paths need to be strictly separated. This means that it should not be possible to set paths completely free like before.

**Comment by JunioCalu** [comment]
Great, this new detail could be documented because this type of configuration in output_param is more intuitive in earlier versions.

**Comment by jb-alvarado** [comment]
Yes the documentation needs some improvements!
