### ISSUE TITLE
Undefined media directory path

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#746]
### Describe the bug

Undefined media directory path.

### To Reproduce

![image](https://github.com/user-attachments/assets/05b7be9e-a37c-4c69-b8d5-779b30ea7fcc)

### Desktop/Server/Software:

- OS: manjaro 24.0.8
- ffplayout 0.24.0-beta4
- ffmpeg 7.0.1
- are you using the current master of ffplayout? Yes

**Comment by jb-alvarado** [comment]
You can try the new source code. When it still not work, I need reproducible steps.

**Comment by JunioCalu** [comment]
I’m going to test the new source code. The step is to drag the media item from the media files panel and drop it into the playlist.

**Comment by JunioCalu** [comment]
The issue hasn't been resolved yet. Here are the steps to reproduce:

1.
```shell
sudo ./target/x86_64-unknown-linux-musl/release/ffplayout --db=./db --log-path=./log --storage-root=/var/lib/ffplayout/tv-media --shared-storage -u admin -p admin -m contact@example.org
``` 
2.
```shell
sudo ./target/x86_64-unknown-linux-musl/release/ffplayout --public=./frontend/.output/public --db=./db --log-path=./log -l 0.0.0.0:8787
``` 
3.
https://github.com/user-attachments/assets/e12a1968-3322-4442-a839-02d7437c37f9

**Comment by JunioCalu** [comment]
The issue is now fixed, but I don't understand why the file field can no longer be edited:

![image](https://github.com/user-attachments/assets/14702868-57ea-46f5-ae7c-c46c4f0b7fd5)

**Comment by JunioCalu** [comment]
I encountered another issue: the green outline on the player's play button is not removed when the playlist is stopped. You need to reload the page by pressing F5 to update the play button's state:

https://github.com/user-attachments/assets/48ea21d4-e712-4784-b89c-1229a56da1e9
