### ISSUE TITLE
Playlist generator

### ISSUE THREAD

**Issue by cooliobr** [ffplayout/ffplayout#756]
I got a error when try to generate a playlist

### To Reproduce

ffplayout -c 2 -g 2024-08-27 - 2025-01-30 --template ./schedule.json    

```
Error: Custom { kind: Other, error: "BadRequest: no rows returned by a query that expected to return at least one row" }
```

 ffplayout --version
ffplayout 0.24.0-beta4

json file

```JSON
{
    "sources": [
        {
            "start": "05:59:00",
            "duration": "23:59:59",
            "shuffle": true,
            "paths": [
                "/var/lib/ffplayout/tv-media/6"
            ]
        }
    ]
}
```

**Comment by jb-alvarado** [comment]
To me it looks like that the channel not exists. Did you give the right ID? I changed now the error message, to make it more clear.

**Comment by cooliobr** [comment]
> To me it looks like that the channel not exists. Did you give the right ID? I changed now the error message, to make it more clear.

Yes, the channel ID exists. I had already run this same template in the previous beta versions (beta2 and beta3), and it worked fine. However, it's not functioning in the current beta4 version

**Comment by jb-alvarado** [comment]
Hm, I'm still not able to reproduce this issue. What is the result from: `ffplayout --list-channels`?

**Comment by cooliobr** [comment]
> Hm, I'm still not able to reproduce this issue. What is the result from: `ffplayout --list-channels`?

![tela](https://github.com/user-attachments/assets/41d9709b-d905-4e01-a4af-6ce6c7c1928c)
![tela2](https://github.com/user-attachments/assets/d98f2e8b-12bc-4a85-9276-b11e38e5e942)

**Comment by jb-alvarado** [comment]
Is it possible, that you try the code from current master?

**Comment by cooliobr** [comment]
> Is it possible, that you try the code from current master?

no, not yet!
