### ISSUE TITLE
[Enhancement] Add "Delete Items" Button and Display Media Selection Panel in Mobile Player Layout

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#760]
### Feature description

Add a "Delete Items" button to the playlist and display the "Media Selection Panel for Playlist" when the player's page layout is resized for mobile devices, smartphones, and tablets.

### The problem in the current version

As can be seen in the image below, the buttons to delete items from the playlist and the media selection panel are missing in mobile layouts.

![image](https://github.com/user-attachments/assets/c1de08aa-3a10-4934-8939-a3d23fed6a16)

The same problem can be seen in the media addition form and in the text and m3u file import menu:

![image](https://github.com/user-attachments/assets/6edb0719-e14a-4f28-8625-b2a5978cbf2f)

![image](https://github.com/user-attachments/assets/1562be4f-1b02-47e7-b75f-44a2a418fccf)

**Comment by JunioCalu** [comment]
**Updates:**

The home page, which displays system monitoring information, is also not configured for mobile screens:

![image](https://github.com/user-attachments/assets/ff361e6e-c6e9-4baa-9ae1-f75d93c78552)

The buttons to delete playlist items and the media selection panel are still not appearing on the playout player's page. However, the media page correctly displays these functions, as highlighted in red in the image below:

![image](https://github.com/user-attachments/assets/51085e68-075e-4ec1-a8e5-dc1591799f52)

**Comment by jb-alvarado** [comment]
I have fix the layout issues, but I'm not planing to add the remove button to the playlist items in mobile portrait mode. If you need it, rotate to landscape view.

**Comment by JunioCalu** [comment]
For the screen type shown below, the "delete buttons" do not appear in landscape view mode:

![image](https://github.com/user-attachments/assets/c0b73791-16aa-4347-a264-dc2654451b22)

**Comment by jb-alvarado** [comment]
I'm not planing to support every Device, the frontend was always Desktop first.

**Comment by JunioCalu** [comment]
Coming back to this topic, I think it would be helpful to fix this issue: the media form cannot be scrolled to the "title" field on mobile screens in landscape mode, or on desktop screens when the browser's viewport is reduced by resizing the window.

![image](https://github.com/user-attachments/assets/9db5c557-d62a-4ba0-880c-1d3d2468ad5b)

![image](https://github.com/user-attachments/assets/f453b796-9fd5-4a18-a0f3-da5d280a9339)

**Comment by JunioCalu** [comment]
It's almost perfect, just this small detail came up now:

![image](https://github.com/user-attachments/assets/25b92d42-249f-4826-8637-fbeb530b0993)
