### ISSUE TITLE
HELP, who can teach me how to install ffplayout, I have tried and it always shows me an error, thanks, I pay for you to teach me thanks -- ///-- AYUDA , quien me puede enseñar a instalar ffplayout ,he intentado y siempre me marca error , gracias , pago para que me enseñe gracias -- --- 

### ISSUE THREAD

**Issue by jacomeTv** [ffplayout/ffplayout#767]
HELP, who can teach me how to install ffplayout, I have tried and it always shows me an error, thanks, I pay for you to teach me thanks -- ///-- AYUDA , quien me puede enseñar a instalar ffplayout ,he intentado y siempre me marca error , gracias , pago para que me enseñe gracias -- ---

**Comment by cooliobr** [comment]
> HELP, who can teach me how to install ffplayout, I have tried and it always shows me an error, thanks, I pay for you to teach me thanks -- ///-- AYUDA , quien me puede enseñar a instalar ffplayout ,he intentado y siempre me marca error , gracias , pago para que me enseñe gracias -- ---

Hi, i can help you,
whatsapp +55 48998535017
