### ISSUE TITLE
[Enhancement] It is not possible to edit the "file" field in the media creation/editing form

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#775]
### Feature description

The "file" field in the media creation/editing form is inaccessible in the current beta5 version. Will it be editable again in the final version?

### The problem in the current version

![image](https://github.com/user-attachments/assets/3c87c0f9-7055-44a4-932b-e63d70ad933d)

**Comment by jb-alvarado** [comment]
To me there is no good reason to me to make this field editable. When you create a new source you can edit it, also when you have a http source. Is only gray out when a item is dragged into the playlist.

The less users have direct contact with the file system, the better.
