### ISSUE TITLE
Duplicate channel label

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#776]
### Describe the bug

When adding more than one channel, the label of the first channel is duplicated, as shown below:

![image](https://github.com/user-attachments/assets/11b91283-d379-4cc4-b6e4-10971d2d067d)

### To Reproduce

1. Add two channels and a non-administrative user.

### Desktop/Server/Software (please complete the following information):
OS: manjaro 24.0.8
ffplayout 0.24.0-beta5
ffmpeg 7.0.1
are you using the current master of ffplayout? Yes

**Comment by jb-alvarado** [comment]
On top it shows the current selected channel... Most drop downs works like that.
