### ISSUE TITLE
Error when triggering the Previous/Next playback controls multiple times in quick succession.

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#781]
### Describe the bug

When triggering the Previous/Next playback controls multiple times in quick succession, the following error is presented: "Reach fatal error count, terminate channel!". The execution logs are attached.

### To Reproduce

1. Click the Previous/Next button 10 or 20 times in quick succession.

### Desktop/Server/Software (please complete the following information):

- OS: ubuntu 22.04
- ffplayout 0.24.0-beta5
- ffmpeg 7.0.1
- are you using the current master of ffplayout? Yes

### Logging:

- content of: [playout_2024-09-30.log.txt](https://github.com/user-attachments/files/17191918/playout_2024-09-30.log.txt)

**Comment by jb-alvarado** [comment]
Not a bug, but a suspected error.
