### ISSUE TITLE
Problem installing version v0.24.0-beta5

### ISSUE THREAD

**Issue by C0la149** [ffplayout/ffplayout#783]
OS: Ubuntu 24.04.1 LTS 
ffplayout: v0.24.0-beta5
I have a problem when trying to install ffplayout.
At the stage (systemctl enable --now ffpapi) It says that there is no such thing. How to install that version?

**Comment by JunioCalu** [comment]
> OS: Ubuntu 24.04.1 LTS ffplayout: v0.24.0-beta5 I have a problem when trying to install ffplayout. At the stage (systemctl enable --now ffpapi) It says that there is no such thing. How to install that version?

Please return here to report your usage experience and test in all possible ways. Installation steps for this version:

```shell
sudo rm -rv /usr/share/ffplayout/db/*
``` 

```shell
sudo -u ffpu ffplayout -i --db=/usr/share/ffplayout/db --logs=/var/log/ffplayout --storage=/var/lib/ffplayout/tv-media --playlists=/var/lib/ffplayout/playlists --public=/usr/share/ffplayout/public --shared -u admin -p admin -m contact@example.org
``` 

```shell
sudo systemctl enable --now ffplayout
```
