### ISSUE TITLE
unexpected argument '-d' found during installation

### ISSUE THREAD

**Issue by skitvandarken** [ffplayout/ffplayout#795]
### Describe the bug

encountered an error during the installation of the ffplayout package

### To Reproduce

apt install /etc/ffplayout_0.24.0-rc1-1_amd64.deb

### Expected behavior

Sucessfull installation prompting to global user creation prompt

### Desktop/Server/Software (please complete the following information):

- OS: debian 12
- ffplayout version: 0.24.0-rc1-1_amd64.deb
- ffmpeg version:  5.1.6-0+deb12u1 
![Captura de ecrã 2024-10-06 175151](https://github.com/user-attachments/assets/73ac20e0-19a2-4d71-b477-cdc975bfe63c)

**Comment by jb-alvarado** [comment]
Thanks, will be fixed in RC2
