### ISSUE TITLE
 [ERROR] [Decoder] [mpeg2video @ 0x55e75116ec80] stuffing too large, [ERROR] [Decoder] Error submitting video frame to the encoder, [ERROR] Clip begin out of sync 

### ISSUE THREAD

**Issue by skitvandarken** [ffplayout/ffplayout#796]
### Describe the bug

When attempting to process an MPEG-2 video stream, the following errors occur in the logs:
[mpeg2video @ 0x55a00c1c09c0] stuffing too large
Error submitting video frame to the encoder
Clip begin out of sync for 196.557 seconds

These errors seem to indicate issues with decoding, frame submission to the encoder, and video synchronization.

### To Reproduce

Run ffplayout with an MPEG-2 video file as the input stream.
The errors are encountered during playback or processing.
Check the logs for the listed error messages.

### Expected behavior
The MPEG-2 video stream should be decoded and processed without stuffing errors or out-of-sync issues. Video frames should be submitted to the encoder properly, and the clip should start in sync.

### Desktop/Server/Software (please complete the following information):

- OS: debian 12
- ffplayout  v0.24.0-rc1
- ffmpeg version  5.1.6-0+deb12u1 
- using the current master of ffplayout

![Captura de ecrã 2024-10-06 183844](https://github.com/user-attachments/assets/7b18cef3-9e67-46ea-b59a-c747637c2195)

- content of: ffplayout.log
[2024-10-06 17:36:23.688070] [ERROR] [Decoder] [mpeg2video @ 0x55e75116ec80] stuffing too large
[2024-10-06 17:36:23.689393] [ERROR] [Decoder] Error submitting video frame to the encoder
[2024-10-06 17:36:24.106427] [ERROR] Clip begin out of sync for 114.318 seconds.

**Comment by skitvandarken** [comment]
I believe that the problems lies in the generation of the filler 
I tested playing an empty playlist, here is the result

` Playlist  not exist!
  Filler error: File  not exist!
  Generate filler with  seconds length!
  Play for : 
  [Decoder][2024-10-06 19:31:44.809014][ERROR]/var/lib/ffplayout/playlists/2024/10/2024-10-06.json[2024-10-06 19:31:44.938562][ERROR]/var/lib/ffplayout/tv-media/filler/filler.mp4[2024-10-06 19:31:44.939441][ WARN]60.00[2024-10-06 19:31:44.942046][ INFO]00:01:00.000color=c=#121212:s=720x576:d=60  [2024-10-06 19:31:45.092564][ERROR] [mpeg2video @ 0x5556b0ae38c0] stuffing too large
  [Decoder][2024-10-06 19:31:45.093767][ERROR] Error submitting video frame to the encoder
  Reach fatal error count, terminate channel![Decoder][2024-10-06 19:31:45.102451][ERROR]`
  
  Please test it there too

**Comment by skitvandarken** [comment]
Yet i get strange peaks in CPU usage  on the filler creation process

![Uploading Captura de ecrã 2024-10-06 203934.jpg…]()

**Comment by jb-alvarado** [comment]
Minimum requirements are 4 Threads and 3gb ram.

**Comment by skitvandarken** [comment]
Testing it exhautively today

**Comment by jb-alvarado** [comment]
Something with your output parameters are not correct.
