### ISSUE TITLE
v0.24.0-rc2

### ISSUE THREAD

**Issue by ramcesrene** [ffplayout/ffplayout#801]
I like to know how can I covert in https ?

**Comment by cooliobr** [comment]
> I like to know how can I covert in https ?

you need to install a certificate ...

**Comment by ramcesrene** [comment]
I did and nginx work fine Sent from my iPhoneOn Oct 10, 2024, at 12:04 PM, cooliobr ***@***.***> wrote:﻿

I like to know how can I covert in https ?

you need to install a certificate ...

**Comment by ramcesrene** [comment]
But I don’t now how to change in playout Sent from my iPhoneOn Oct 10, 2024, at 12:04 PM, cooliobr ***@***.***> wrote:﻿

I like to know how can I covert in https ?

you need to install a certificate ...
