### ISSUE TITLE
[Enhancement] Add justified text formatting to the help text.

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#804]
### Feature description

Add justified text formatting to the help text.

<table>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/f2ff3738-71cc-4b78-8415-92816b66e85f" alt="Image 1" width="500"></td>
    <td><img src="https://github.com/user-attachments/assets/71bef74b-0611-4e3e-8338-30842d3026c7" alt="Image 2" width="500"></td>
  </tr>
</table>

### The problem in the current version

None of the system's long texts are formatted in a justified manner.

**Comment by jb-alvarado** [comment]
I think, that should be fine now.
