### ISSUE TITLE
upload  >>  support types  

### ISSUE THREAD

**Issue by dimage** [ffplayout/ffplayout#824]
### Describe the bug
![Screenshot From 2024-11-05 22-29-06](https://github.com/user-attachments/assets/7a4fc877-521a-44e0-9fe6-a55fdf8c2d47)

### To Reproduce

1. Go to '0.0.0.0:8787/media'
2. Click on 'Media'
3. Click on 'Upload Files'

### Desktop/Server/Software (please complete the following information):

- OS: [e.g. debian 12]
- ffplayout version
- ffmpeg version
- are you using the current master of ffplayout?

### Config Settings:

- command line arguments
- config fie

### Logging:

- content of: ffplayout.log

**Comment by JunioCalu** [comment]
I think the issue here is that the File Picker isn’t showing all file types for selection by default when trying to upload files on the media page

**Comment by jb-alvarado** [comment]
Definitely a bug... Thanks for report.
