### ISSUE TITLE
error on ffpapi

### ISSUE THREAD

**Issue by tiagoventura7** [ffplayout/ffplayout#828]
hi,

on a clean system install (wattOS and Xubuntu), right after ffplayout install, tried to "systemctl enable --now ffpapi" it returns ""Failed to enable unit: Unit File ffpapi.service does not exist"

this occours with the latest version only.

am i doing anything wrong?

**Comment by JunioCalu** [comment]
> OS: Ubuntu 24.04.1 LTS ffplayout: v0.24.0-beta5 I have a problem when trying to install ffplayout. At the stage (systemctl enable --now ffpapi) It says that there is no such thing. How to install that version?

Installation steps for this version:

```shell
sudo rm -rv /usr/share/ffplayout/db/*
``` 
Setting the login username as "admin" and the password as "admin":

```shell
sudo ffplayout -i -u admin -p admin -m contact@example.com --storage "/var/lib/ffplayout/tv-media" --playlists "/var/lib/ffplayout/playlists" --public "/usr/share/ffplayout/public" --logs "/var/log/ffplayout" --mail-smtp "mail.example.org" --mail-user "admin@example.org" --mail-password "" --mail-starttls
``` 

```shell
sudo systemctl enable --now ffplayout
```
