### ISSUE TITLE
do not display in files in the folder.

### ISSUE THREAD

**Issue by dimage** [ffplayout/ffplayout#829]
do not display in files in the folder.

### Describe the bug
![Screenshot From 2024-11-06 19-59-12](https://github.com/user-attachments/assets/18740c62-6337-4179-b552-eac245ce7933)

![Screenshot From 2024-11-06 20-00-41](https://github.com/user-attachments/assets/96effd82-af50-4cbc-aab3-180ec817bc87)

### Desktop/Server/Software (please complete the following information):

- OS: docker
- ffplayout version 0.24.1
- localhost/ffplayout-image nvidia
- are you using the current master of ffplayout? yes

### Config Settings:

- command line arguments
- config fie

### Logging:

- content of: ffplayout.log

**Comment by jb-alvarado** [comment]
Some how ffprobe build missed something to work correctly. You can get dockerfile from master, that should work now.

**Comment by dimage** [comment]
same problem with nonfree.dockerfile

**Comment by jb-alvarado** [comment]
Ok, I will look to it. I think it has to do with the parameter `--enable-small`.
