### ISSUE TITLE
[Enhancement] Implement S3-Compatible Storage Input

### ISSUE THREAD

**Issue by emdiple** [ffplayout/ffplayout#865]
## Feature description

This feature proposes directly supporting reading media files from S3-compatible object storage services (e.g., AWS S3, MinIO, Wasabi, Backblaze B2). This will enable users to leverage cloud-based storage as a primary media source, streamlining workflows and eliminating the need for local downloads.

**Specifically, the feature should allow users to:**

*   Configure S3 connection details (endpoint, access key, secret key, etc.) within the application's settings.
*   Select "S3" as a media source when importing.
*   Browse or enter the S3 object's path.
*   The application should then stream the media directly from S3 for processing.

## The problem in the current version

Currently, the application only supports importing media from local files. This presents several problems for users who store their media in cloud object storage:

*   **Inefficiency:** Users must download files locally before importing them, which is time-consuming and consumes bandwidth, especially for large files.
*   **Workflow Disruption:** This extra step disrupts cloud-based workflows and makes integrating the application with existing cloud infrastructure difficult.
*   **Scalability Limitations:** Relying on local storage limits scalability and makes it harder to manage large media libraries efficiently.
*   **Cost Inefficiency:** Maintaining local storage for large media datasets can be more expensive than using cloud object storage.

## Alternative ways

Currently, there are no direct alternatives within the application to import media directly from S3-compatible storage. Users are forced to use indirect workarounds, which are not practical or efficient. These workarounds include:

1.  **Manual Download:** The user must use a separate tool (like the AWS CLI, a web browser, or a third-party S3 client) to download the desired media file from their S3 bucket to their local machine. This is cumbersome, especially for large files, and negates many of the benefits of using cloud storage.

2.  **Mounting S3 with FUSE:** Users can use tools like `s3fs-fuse` or `goofys` to mount their S3 bucket as a local file system using FUSE (Filesystem in Userspace). This allows the application to access the S3 objects as if they were local files. However, this approach has several drawbacks:

    *   **Performance Overhead:** FUSE-based file systems often introduce significant performance overhead compared to native file systems, especially for random access and large files. This can lead to slow import times and poor application performance.
    *   **Complexity:** Setting up and configuring FUSE can be complex for non-technical users.
    *   **System Dependencies:** Requires additional software installation (FUSE and the specific S3 mounting tool) and may not be available on all operating systems.
    *   **Stability Issues:** FUSE mounts can sometimes be unstable or prone to errors, which can disrupt the application's workflow.

These workarounds are inefficient and add unnecessary complexity to the user's workflow. The proposed feature would provide a much more streamlined and performant solution for importing media from S3-compatible storage.

**Comment by arxyzan** [comment]
+1
